### PR TITLE
Minor update to properly reflect supported macros

### PR DESCRIPTION
**Pull request by brbrahm**

### CODE REVIEW

**Comment by e0i** [comment]
@mdsakibMSFT A PR for a document of your authorship that introduces a minor update to the document is available for review. Thanks.

**Comment by illfated** [comment]
Visual view of the PR changes (rich text diff):
https://github.com/MicrosoftDocs/windows-itpro-docs/pull/4575/files?short_path=52d1e5e#diff-52d1e5e2a05a6fdcf25cb37b1bcae5c1

**Comment by e0i** [comment]
@mdsakibMSFT Following up for updates.

**Comment by mdsakibMSFT** [comment]
The change looks good to me

**Comment by illfated** [comment]
@mdsakibMSFT : Thank you for the positive feedback. Would you also be able to merge this PR, or is this a preferred task for @Justinha to perform?

**Comment by mdsakibMSFT** [comment]
I dont have privileges to merge in the master docs branch. Justin or one if the other writers needs to help

Get Outlook for Android<https://aka.ms/ghei36>

________________________________

**Pull request merged**
