### PR TITLE
Update windows-autopilot-requirements.md

### PR DESCRIPTION
**Pull request by mtniehaus**
Separated the Windows Autopilot deployment service and Windows Activation items into two separate rows to make it easier to read.

### CODE REVIEW

**Comment by e0i** [comment]
@greg-lindsay Would you be able to review this PR created by a MS contributor that introduces a minor styling fix to make the page more readable? Thank you.

**Comment by illfated** [comment]
Rich Text Diff view to see the effective changes:
https://github.com/MicrosoftDocs/windows-itpro-docs/pull/4794/files?short_path=9309861#diff-9309861f761730800fcad5490f0a51e7

**Comment by e0i** [comment]
@greg-lindsay Following up for updates.

**Comment by e0i** [comment]
@greg-lindsay Following up for updates.

**Pull request merged**
