### PR TITLE
Update security-compliance-toolkit-10.md

### PR DESCRIPTION
**Pull request by jmunck**
Updated list to remove 1903 as it went EoS in December, forgot to update it

### CODE REVIEW

**Comment by illfated** [comment]
Fair enough. I guess I have missed out on what sets 1903 apart from 1507, 1607 (Anniversary Update), 1803 (April 2018 Update), 1809 (October 2018 Update), 1903 (May 2019 Update), 1909 (November 2019 Update), 2004 (May 2020 Update), 20H2 (October 2020 Update). It just looks a bit odd that 1903 is removed and not the older ones. What is the most obvious page(s) I should read to get myself up to date on this detail?

**Comment by jmunck** [comment]
LOL yeah it gets confusing.  Some of the builds have LTSC channels associated with them also which makes it more complicated but the best page is https://docs.microsoft.com/en-us/lifecycle/products/windows-10-enterprise-and-education.  On the Wiki site there is a good cheat sheet as well: https://en.wikipedia.org/wiki/Template:Windows_10_versions

**Comment by illfated** [comment]
👍🏻 Thanks, that is very useful to know. If nothing else, at least to stop feeling lost in the dark and not knowing what sets those editions apart from the newer one to be removed.

**Review by illfated — APPROVED** [review]
Looks good to me.

**Comment by illfated** [comment]
#sign-off

**Review by JohanFreelancer9 — APPROVED** [review]

**Pull request merged**
