### PR TITLE
IPv4 is not optional

### PR DESCRIPTION
**Pull request by joinimran**
For WIP, IPv4 is not optional, but mandatory to be configured. 

Problem: https://github.com/MicrosoftDocs/windows-itpro-docs/issues/9208

### CODE REVIEW

**Comment by joinimran** [comment]
@JohanFreelancer9 - kindly do the copy editor review for this PR. Thanks.

**Review by JohanFreelancer9 — APPROVED** [review]

**Review by illfated — APPROVED** [review]
Looks good to me.

**Comment by illfated** [comment]
#sign-off

**Comment by nam31** [comment]
@Dansimp PR has been copyedited and is ready for final review, could you please check and merge? Thanks!

**Pull request merged**
