### PR TITLE
Update virus-initiative-criteria.md

### PR DESCRIPTION
**Pull request by adamoboe**
Updated to match current license requirements

### CODE REVIEW

**Comment by hashtag2949** [comment]
Facebook drive enter-media issues marked network D~(drive/F:>D:)  <G_:>Xbox One Drive
latter branch C:>(){}[]\dir /p                  Bi_latterial~' (Hashtag\2949)
cd then file name()[]{} E:>_BD-RE Drive
 (\Q.filer;[> X-]{/+)  ((:/(A:>} /B:>_))  (((hersh-)) x 
((hold)) /break~((`Xq x Q))x')))               Field>C:\   Large codx- field+e

**Comment by mypil** [comment]
@levinec- can you please assist to check, approve and merge the content for this PR? 

Thank you.

**Comment by mypil** [comment]
@levinec - I would like to follow up on this.  Can you please assist to check, approve and merge the content for this PR?

Thank you.

**Comment by levinec** [comment]
@mypil Sorry I didn't see this earlier, I don't think it tagged me correctly the first time. Merged now, thank you!

**Pull request merged**
