### PR TITLE
Adding error codes

### PR DESCRIPTION
**Pull request by theznerd**
It appears that some error codes were added to the deployment script after this document was created. This PR documents those new error codes and the best effort understanding of remediation paths.

### CODE REVIEW

**Comment by e0i** [comment]
@dariomws306 @get-itips @tseward

Peer review needed for this PR. Thanks.

**Comment by tseward** [comment]
Rather than using `==`, can you use the word 'equals'? And please fix the !NOTE section below the Exit Code tables.

**Comment by theznerd** [comment]
Would you like me to change all instances of `==` to equals? I did `==` to match the formatting elsewhere in the table.  Also not sure how you would like me to fix the !NOTE section - it appears that same way in the master branch unless I'm missing something.

**Comment by theznerd** [comment]
@tseward Would you like me to change all instances of `==` in the table to the word equals'? I only used `==` in the PR because it matched the rest of the table.

Also, not sure what to fix on the !NOTE section - it appears that same way in the master branch.

**Comment by tseward** [comment]
I think that would be appropriate, yes. And disregard my comment on the !NOTE. It looks fine in the live article.

**Comment by theznerd** [comment]
@tseward - new commit added with `==` changed to 'equals' - thank you!

**Comment by dariomws306** [comment]
Looks good.

**Comment by get-itips** [comment]
Ok

**Comment by e0i** [comment]
@AndreaBarr The community contributed PR is ready to be merged. Thanks.

**Pull request merged**
