### PR TITLE
Update hello-hybrid-cert-whfb-settings-adfs.md

### PR DESCRIPTION
**Pull request by MaratMussabekov**
issue #2050

### CODE REVIEW

**Comment by mypil** [comment]
@DulceMontemayor - Can you please assist to check, approve and merge the content of this PR based on issue #2050?

Thank you.

**Comment by mypil** [comment]
@DulceMontemayor - We would like to follow up on this. Can you please assist to check, approve and merge the content of this PR based on issue #2050?

Thank you.

**Comment by mypil** [comment]
@AndreaBarr - Would you be able to merge the content for this PR? Thanks.

**Comment by mypil** [comment]
@DaniHalfin @mapalko - would you be able to help review and merge the content of this PR based on issue #2050?

**Comment by mapalko** [comment]
@DaniHalfin  can you merge this?

**Pull request merged**
