### PR TITLE
add admx info for System/AllowExperimentation

### PR DESCRIPTION
**Pull request by yogeshasalkar**
#6601

### CODE REVIEW

**Comment by yogeshasalkar** [comment]
@JohanFreelancer9  Could you please look into this?

**Comment by e0i** [comment]
cc @ManikaDhiman

**Comment by ManikaDhiman** [comment]
I have reached out to the product team to review the updates. Thanks!

**Comment by e0i** [comment]
@ManikaDhiman Please let us know whenever there are any updates from the product team, thanks.

**Comment by e0i** [comment]
@ManikaDhiman Following up.

**Comment by ManikaDhiman** [comment]
The product team informed that they do not want the ADMX info for this policy to be available in public docs. Thanks!

**Comment by e0i** [comment]
Closing via Author's comments above. Thank you.

**Pull request closed without merging**
