### PR TITLE
format yaml and use dnf as example

### LINKED ISSUE #9348: Several of the yamls are formatted incorrectly
The uninstall files have task unindented, and the yum one has state indented too far.
```yaml
- hosts: servers
tasks:
    - yum:
       name: mdatp
        state: absent
```
The yum install file doesn't indent the yum parameters
```yaml
- hosts: servers
  tasks:
    - include: ../roles/onboarding_setup.yml
    - include: ../roles/add_yum_repo.yml
    - yum:
      name: mdatp
      state: latest
      enablerepo: packages-microsoft-com-prod-[channel]
```
There might have been other yaml issues as well.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 623e0469-826c-5cdf-6dc4-67c80e232d0f
* Version Independent ID: 0f6c33bc-711a-84d6-01bb-04d13f5a85a2
* Content: [Deploy Microsoft Defender ATP for Linux with Ansible - Windows security](https://docs.microsoft.com/en-us/windows/security/threat-protection/microsoft-defender-atp/linux-install-with-ansible)
* Content Source: [windows/security/threat-protection/microsoft-defender-atp/linux-install-with-ansible.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/public/windows/security/threat-protection/microsoft-defender-atp/linux-install-with-ansible.md)
* Product: **m365-security**
* Technology: **mde**
* GitHub Login: @Dansimp
* Microsoft Alias: **dansimp**

### PR DESCRIPTION
**Pull request by konstruktoid**
- Format the YAML files
- Use DNF instead of YUM in the examples
- Update documentation links

Closes #9348 

Signed-off-by: Thomas Sjögren <konstruktoid@users.noreply.github.com>

### CODE REVIEW

**Comment by nam31** [comment]
@JohanFreelancer9 please do the copy editor review for this PR.

**Review by JohanFreelancer9 — APPROVED** [review]

**Comment by konstruktoid** [comment]
https://github.com/MicrosoftDocs/windows-itpro-docs/blob/public/windows/security/threat-protection/microsoft-defender-atp/linux-install-with-ansible.md has been deleted?

**Comment by illfated** [comment]
Actually, it is the directory `/microsoft-defender-atp/` which has been renamed or deleted. I am still trying to trace the changes in https://github.com/MicrosoftDocs/windows-itpro-docs/tree/public/windows/security/threat-protection/ to see if I can find if the file exists at all. Maybe the file needs to be recreated by using the WayBack Machine (https://web.archive.org)?

**Comment by illfated** [comment]
Looks like all the `linux-install-*` files have been removed along with the directory. I don't know how others react to this event, but it seems a bit too destructive to me.

**Comment by illfated** [comment]
As mentioned in the issue ticket: 

"... all of the MDE (formerly known as Defender ATP) documentation [has been moved] to the microsoft-365-docs repo and also [...] updated all of the branding."

https://github.com/MicrosoftDocs/windows-itpro-docs/issues/9348#issuecomment-807608222

**Comment by konstruktoid** [comment]
Thanks @illfated.

**Comment by konstruktoid** [comment]
Replaced by https://github.com/MicrosoftDocs/microsoft-365-docs/pull/4563

**Pull request closed without merging**
