### PR TITLE
updated docs with announcements on perspectives and wdav reporting retirement

### PR DESCRIPTION
**Pull request by cinglis-msft**
- Announcement in "update-compliance-monitoring"

- Announcement in "update-compliance-perspectives"

- Announcement in "update-compliance-wd-av-status"

### CODE REVIEW

**Comment by illfated** [comment]
Looks quite good. May I request the addition of MarkDown indent marker compatibility spacing (add 1 blank space between each "greater-than" character ( `>` ) and any text following that character) for the [!NOTE] and [!IMPORTANT] blobs in these files?

**Comment by illfated** [comment]
BTW, @jaimeo, thank you for making the links language agnostic. Good work.

**Comment by cinglis-msft** [comment]
Thank you for checking and pointing it out. Changed.

**Comment by illfated** [comment]
Thank you for implementing the standard. Good work.

**Comment by jaimeo** [comment]
Looking good then? Shall we merge?

**Comment by cinglis-msft** [comment]
I think the application of the terminology is scenario-specific. Internal comms team did explicitly elect to use Microsoft Endpoint Manager. I believe MEM is more cloud-focused.

**Comment by illfated** [comment]
#sign-off

**Comment by jaimeo** [comment]
Regarding the naming of (former) Configuration Manager (and allied technologies): the over-arching umbrella solution is Microsoft Endpoint Manager. Its elements/features include: Microsoft Endpoint Configuration Manager, Microsoft Intune, Desktop Analytics, Autopilot, and the admin center in Azure portal.

**Comment by illfated** [comment]
Thank you for enlightening me on the subject. I will do my best to keep that in mind, for future needs.

**Pull request merged**
