### PR TITLE
resolves #4409

### LINKED ISSUE #4409: Remove FAQ content and merge with existing dedicated WDAG FAQ page
The main WDAG page has a FAQ and the bottom. There is also a separate FAQ page at https://docs.microsoft.com/en-us/windows/security/threat-protection/windows-defender-application-guard/faq-wd-app-guard Please consider moving the FAQ content from the main page to the dedicated, existing FAQ page. Please consolidate the FAQ content as well as there is some duplicate and some unique content between the two. Leaving these two different FAQs existing with slightly different content is confusing. Retaining a link on this page to the "new" consolidated, separate FAQ could also be beneficial but not required since there's a link in the left hand navigation already.

---

#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: dfb9445a-681d-24b6-5241-4ebe311f5236
* Version Independent ID: aea60f74-212c-e24e-f164-28a555bc1727
* Content: [Windows Defender Application Guard (Windows 10)](https://docs.microsoft.com/en-us/windows/security/threat-protection/windows-defender-application-guard/wd-app-guard-overview)
* Content Source: [windows/security/threat-protection/windows-defender-application-guard/wd-app-guard-overview.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/master/windows/security/threat-protection/windows-defender-application-guard/wd-app-guard-overview.md)
* Product: **w10**
* Technology: **windows**
* GitHub Login: @Dansimp
* Microsoft Alias: **dansimp**

### PR DESCRIPTION
**Pull request by martyav**
**Remove FAQ content and merge with existing dedicated WDAG FAQ page**

> The main WDAG page has a FAQ and the bottom. There is also a separate FAQ page at https://docs.microsoft.com/en-us/windows/security/threat-protection/windows-defender-application-guard/faq-wd-app-guard Please consider moving the FAQ content from the main page to the dedicated, existing FAQ page. Please consolidate the FAQ content as well as there is some duplicate and some unique content between the two. Leaving these two different FAQs existing with slightly different content is confusing. Retaining a link on this page to the "new" consolidated, separate FAQ could also be beneficial but not required since there's a link in the left hand navigation already.

I took a look and the differences were that the FAQ page had some more questions inserted at the end in different places. The WDAG page did not seem to have any additional content, so I removed the questions there, replaced them with a link, and did not add anything to the FAQ page

### CODE REVIEW

**Comment by e0i** [comment]
cc @mypi

**Comment by mypil** [comment]
@nenonix @JohanFreelancer9 - kindly do the copy editor review for this PR. Thanks.

**Comment by mypil** [comment]
@Dansimp - PR has been copy edited and is ready for final review. This is based on issue #4409 

Thank you.

**Comment by iadgovuser1** [comment]
Thanks!

**Pull request merged**
