### PR TITLE
added missing comma

### PR DESCRIPTION
**Pull request by MaratMussabekov**
the last value in the list must be followed by comma as well
https://github.com/MicrosoftDocs/windows-itpro-docs/issues/6973

### CODE REVIEW

**Comment by MaratMussabekov** [comment]
Dear @JohanFreelancer9,
kindly do the copy editor review for this PR.

Dear @nam31, for your information

Thank you

**Review by JohanFreelancer9 — APPROVED** [review]

**Comment by nam31** [comment]
Hi @DulceMontemayor PR has been copyedited and is ready for final review, could you please check and merge? Thanks!

**Review by illfated — APPROVED** [review]
Looks good to me.

**Comment by illfated** [comment]
#sign-off

**Comment by nam31** [comment]
Hi @DulceMontemayor PR has been copyedited and is ready for final review, could you please check and merge? Thanks!

**Comment by illfated** [comment]
@nam31 : From my own experience, Dulce Montemayor can often be busy with other work, taking some time to attend to the GitHub tickets and pull requests. If you want reasonably quicker follow-up and merging, you might want to check with the team who to ask for earlier response (may depend on individual areas of authority, I don't know all the details). The ones I know who usually has merging rights in this repository are the following:
- Daniel Simpson
- Denise Vangel
- MJ Caparas
- Kateyanne
- Jaime Ondrusek

As previously mentioned, their participation may depend on their area of authority. Onur likely knows more, at least enough to decide.

**Pull request merged**
