### PR TITLE
Update autopilot-support.md

### PR DESCRIPTION
**Pull request by brentkendall**
Remove redundant line (PFE was the old term for an Ecosystem PM).  And added new alias for Ecosystem PMs (after discussing all this with the Ecosystem PM managers).

### CODE REVIEW

**Comment by e0i** [comment]
@greg-lindsay Would you be able to review this PR introduced by an internal MS contributor? Thanks.

**Comment by e0i** [comment]
@greg-lindsay  Following up for updates.

**Comment by illfated** [comment]
As usual, the rich text diff view gives the easiest overview of the changes:
https://github.com/MicrosoftDocs/windows-itpro-docs/pull/4713/files?short_path=4b70b9e#diff-4b70b9ee6b7c5bf613625e4a34a791db

**Comment by e0i** [comment]
@greg-lindsay Any chance with this PR? We'd like to follow-up once more before escalations. Thanks.

**Pull request merged**
