### PR TITLE
Adding TPM networking requirements

### PR DESCRIPTION
**Pull request by spshumwa**
@greg-lindsay please review and approve new TPM networking requirements and let the Autopilot team know when doc is live. Thanks.

### CODE REVIEW

**Comment by illfated** [comment]
Suggestion: add the HTML code `<br>` before & after the 3 OEM links at the end of your new section, to get them separated on their own lines for readability/easier to distinguish.
If you don't see what I mean, let me know and I can put suggestions for the change in your source.

**Comment by illfated** [comment]
Well done. Looks a lot easier to notice the OEM URLs now.
My only concern is the way the hyphen is used.
(Trying to think of a better format.)

**Comment by e0i** [comment]
@greg-lindsay Following up for updates.

**Comment by e0i** [comment]
@greg-lindsay Following up for updates.

**Pull request merged**
