### PR TITLE
Update windows-analytics-get-started.md

### PR DESCRIPTION
**Pull request by Reeced40**
https://github.com/MicrosoftDocs/windows-itpro-docs/issues/3551
Changed wording.

### CODE REVIEW

**Comment by e0i** [comment]
@nenonix @JohanFreelancer9 Copy editing is needed for this PR. Thanks.

**Comment by e0i** [comment]
@jaimeo A PR that addresses issue #3551 is available for review. Thanks.

**Comment by jaimeo** [comment]
Let's verify this with a PM....

**Comment by jaimeo** [comment]
Per the PM, "1-2 hours" is not correct. However, neither is "1-2 weeks." Please edit your commit to say "in about 1-2 days" and I'm happy to merge....

**Pull request merged**
