### PR TITLE
Update configure-windows-diagnostic-data-in-your-organization.md

### PR DESCRIPTION
**Pull request by iceorbital**
clarifying diagnostic data endpoints with and without 2018-09 cumulative update or later installed

### CODE REVIEW

**Comment by mypil** [comment]
@nenonix @JohanFreelancer9 - kindly do the copy editor review for this PR. Thanks.

**Comment by JohanFreelancer9** [comment]
Copy edit - no changes required.

**Comment by mypil** [comment]
@DaniHalfin - Can you please assist to check, approve and merge the content for this PR? 

Thank you.

**Comment by DaniHalfin** [comment]
Done. 
Thanks, @iceorbital :)

**Pull request merged**
