### PR TITLE
Update hololens-cortana.md

### PR DESCRIPTION
**Pull request by tmlyon**
Updated some of the language about Cortana support on HL.

### CODE REVIEW

**Comment by v-miegge** [comment]
#sign-off

**Comment by illfated** [comment]
@v-miegge : Seeing that it does not look like you have got merge access, will you notify the doc manager for final review & merge?

**Comment by v-miegge** [comment]
@illfated : I've contacted @jarrettr, the doc manager.

**Comment by illfated** [comment]
Thanks. Well done. Some pull requests tend to lay dormant for weeks before final review, so it is good to know that it has been noted.

**Comment by JarrettRenshaw** [comment]
#sign-off

**Comment by v-miegge** [comment]
@illfated : @JarrettRenshaw has signed-off. Who can approve and merge this?

**Comment by illfated** [comment]
Well, I thought @JarrettRenshaw would be the correct person to approve & merge this PR,
To me, it looks like some MS Docs team members (and maybe managers) are assuming that `#sign-off` can be used in Github comments to produce some form of action.
For all I know, `#sign-off` is only useful in git commits, not in this comment dialogue.
See also https://stackoverflow.com/questions/1962094/what-is-the-sign-off-feature-in-git-for

@Teresa-Motiv & @scooley : Will any of you be able to assist by giving advice regarding which MS Docs team member should use the Github Approve feature and perform the merge?

**Comment by scooley** [comment]
@DaniHalfin - This PR has lots of approval, who has merge perms :)? Is there a process we should follow for getting public -> private -> published?

**Comment by illfated** [comment]
Thank you for merging this PR content, @DaniHalfin . Appreciated.

Also thank you to @scooley for reminding me that this is `windows-itpro-docs`, not `windowsserverdocs`, so I could have asked almost any of the regular handlers.

**Comment by Teresa-Motiv** [comment]
> Well, I thought @JarrettRenshaw would be the correct person to approve & merge this PR,
> To me, it looks like some MS Docs team members (and maybe managers) are assuming that `#sign-off` can be used in Github comments to produce some form of action.
> For all I know, `#sign-off` is only useful in git commits, not in this comment dialogue.
> See also https://stackoverflow.com/questions/1962094/what-is-the-sign-off-feature-in-git-for
> 
> @Teresa-Motiv & @scooley : Will any of you be able to assist by giving advice regarding which MS Docs team member should use the Github Approve feature and perform the merge?

[After the fact] The sign-off bit comes from here: [Pull request comment automation](https://review.docs.microsoft.com/en-us/help/contribute/contribute-how-to-write-pull-request-automation?branch=master)

|#sign-off | When the author of an article types the #sign-off comment in the comment stream, the ready-to-merge label is assigned. This label lets the reviewers in the repo know when a pull request is ready for review/merge.|

**Comment by illfated** [comment]
Aha, thank you for clarifying how that feature works. 👍 
I am fairly sure it is a hidden feature for us regular users.

**Pull request merged**
