### PR TITLE
Adding information on Request Filtering

### PR DESCRIPTION
**Pull request by kenjohnson03**
Documenting the application requirement.

### CODE REVIEW

**Comment by illfated** [comment]
Seeing that there are no links to issue tickets this PR will close, I will start by referencing the default info:

Content: [Planning How to Secure the MBAM Websites](https://docs.microsoft.com/en-us/microsoft-desktop-optimization-pack/mbam-v25/planning-how-to-secure-the-mbam-websites)
Content Source: [mdop/mbam-v25/planning-how-to-secure-the-mbam-websites.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/master/mdop/mbam-v25/planning-how-to-secure-the-mbam-websites.md)

Could you perhaps add some information about your source for the added information?

**Comment by kenjohnson03** [comment]
My source is testing.  It is a problem if the feature is disabled.  I would like to annotate this as a support for organizations that might consider disabling the feature in IIS for this application.

**Comment by mypil** [comment]
@jamiejdt - Can you please assist to check, approve and merge the content for this PR? 

Thank you.

**Comment by mypil** [comment]
@jamiejdt - We would like to follow up. Can you please assist to check, approve and merge the content for this PR?

Thank you.

**Comment by illfated** [comment]
Any chance that @DuncanmaMSFT is still involved in these pages, with the time & ability to review, approve & merge?

**Comment by DuncanmaMSFT** [comment]
I don't know anything about the topic though, I'm just an engineer on the Docs platform, so not sure I should be approving a PR for a content change. @illfated @jamiejdt @mypil

**Comment by mypil** [comment]
@AndreaBarr - Would you be able to merge the content of this PR? Or would you know who we can reach out to get this PR content merged? I checked on the metadata of the article but it does not show who the manager is. Hope you can help. Thank you.

**Pull request merged**
