### PR TITLE
Change required for Command

### PR DESCRIPTION
**Pull request by joinimran**
It was stated that Comma separated issuance of the argument but the examples show semi-colon separated issue of argument. See examples at https://docs.microsoft.com/en-us/windows/client-management/mdm/vpnv2-profile-xsd

Problem# https://github.com/MicrosoftDocs/windows-itpro-docs/issues/734

### CODE REVIEW

**Comment by jdeckerms** [comment]
@joinimran How did you know whether the explanation or the example was correct?

**Comment by joinimran** [comment]
@jdeckerms I have checked the linked document regarding case examples. As per my understanding, I have made the correction. I think it's a docs author's call to ensure the change is correct and should be reflected in the doc or can be discarded with any remarks so that we can communicate the remarks to the user who created this change request via feedback.
Thanks.

**Comment by mypil** [comment]
@jdeckerms - I would like to follow up. Can you please assist to check, approve and merge the content for this PR based on issue #734?

Thank you.

**Comment by mypil** [comment]
@AndreaBarr - would you be able to merge the content of this PR? Thank you.

**Comment by illfated** [comment]
I have no personal problem with the spelling, but apparently, `semicolon` is written as a combined word without a hyphen:
- https://en.wikipedia.org/wiki/Semicolon
- https://www.bing.com/search?q=semi-colon

**Comment by mypil** [comment]
@joinimran - can you possibly make the necessary changes as suggested by @illfated? Thanks.

**Comment by joinimran** [comment]
Spelling updated in the doc.

**Pull request merged**
