### PR TITLE
Technet Gallery is shutting down

### PR DESCRIPTION
**Pull request by desbest**
Technet Gallery is shutting down so I've moved the cmd and powershell files to Github Gists so the page will still work.

### CODE REVIEW

**Comment by illfated** [comment]
While I applaud the effort and idea to make an accessible backup for when the Technet Gallery shuts down, I am pretty certain that any GitHub Gist backup of the Technet Gallery scripts will have to be stored in a location owned by the Microsoft Docs organization to be manageable by the MS Docs team members. I will wait and see what the team says about this. Maybe there already is a storage space accessible to make the backup to, but I have not done any research yet.

**Comment by illfated** [comment]
(ref. #8357 )

**Comment by illfated** [comment]
I am pondering whether to add a folder named "gallery" in the same folder as this document and store some of the gallery scripts there, or if the gallery script backups need to be kept at a centralized and possibly site independent location.

**Comment by illfated** [comment]
See also issue ticket #6841 (**Unclear wording**) where this topic has been discussed from a different angle (descriptive text interpretation).

Notice in particular that this script already has a GitHub page:

> Reading the Q & A section of that TechNet gallery page, I found that the script author has created both an introductory page (README.md) and a wiki page for this script tool, here on GitHub:
>
> - https://github.com/ManuelGil/Reset-Windows-Update-Tool/blob/master/README.md
> - https://github.com/ManuelGil/Reset-Windows-Update-Tool/blob/master/docs/wiki/en/Home.md

**Comment by desbest** [comment]
The script hosted on Technet Gallery is not on the github links provided.

**Comment by illfated** [comment]
Fair enough. I have not checked the contents, so there is that. I guess I just thought it was the same, seeing that the other ticket was created from the exact same page.

I see now that there are 2 separate scripts on the page:
- Reset Windows Update Client settings script - https://gallery.technet.microsoft.com/scriptcenter/Reset-WindowsUpdateps1-e0c5eb78 by Ryan Nemeth
- Reset Windows Update Agent script - https://gallery.technet.microsoft.com/scriptcenter/Reset-Windows-Update-Agent-d824badc by Manuel F. Gil

By the way, I have looked up how this is connected now, finding that the GitHub page is the linked script page from Manuel F. Gil, who is the author of the same script as the one you have linked from your own gist in your PR. I know there is a difference between those scripts, but that is mainly because Manuel F. Gil has developed the script while hosting it on GitHub. Yes, it has changed, but has it changed so much that it doesn't work as described anymore?

Anyway, if the original script works and needs to be hosted somewhere else, I presume we need to wait until the Microsoft Docs team decides on a new hosting page in their own domain or within their own GitHub organization.

**Comment by jaimeo** [comment]
Let me check with the SME about whether they want to host it on Script Center or the Powershell Gallery.

**Comment by e0i** [comment]
@JohanFreelancer9 Copy editing is needed for this PR. Thanks.

**Comment by jaimeo** [comment]
We will find appropriate homes for these scripts.

**Pull request closed without merging**
