### PR TITLE
Update firewall-csp.md

### PR DESCRIPTION
**Pull request by nenonix**
Liine 280 Added tokens not supported by RS4 resolves https://github.com/MicrosoftDocs/windows-itpro-docs/issues/2735
Line 310 Removed "comma separated list"  fixes https://github.com/MicrosoftDocs/windows-itpro-docs/issues/2601
Line 324 Removed "mobile broadband" fixes https://github.com/MicrosoftDocs/windows-itpro-docs/issues/2602

### CODE REVIEW

**Comment by jdeckerms** [comment]
Hi @nenonix What is your source for these changes?

**Comment by nenonix** [comment]
@jdeckerms they are all from @JeffStong , see the issues listed in the PR description

**Comment by jdeckerms** [comment]
@nenonix I see, thanks. I'm going to have to get the engineering team to validate whether the information is correct, so I won't be merging this PR until then. Also, "RS4" is not how we refer to Windows 10 versions in our documentation. Assuming that the changes are correct, it should be written as "The tokens "Intranet", "RmtIntranet", "Internet" and "Ply2Renders" are supported on Windows 10, version 1809, and later."

**Comment by nenonix** [comment]
@jdeckerms Thank you, Changes have been made, and whatever the outcome, this will be a good learning experience for how to deal with the content in this repo.

**Comment by jdeckerms** [comment]
@nenonix Thanks for making that fix! I got confirmation on the comma-separated list part, still working on the rest of it.

**Pull request merged**
