### PR TITLE
update basic-audit-account-management.md

### PR DESCRIPTION
**Pull request by joinimran**
Events updated as per Windows 10 event id.

Problem: https://github.com/MicrosoftDocs/windows-itpro-docs/issues/9483

### CODE REVIEW

**Comment by joinimran** [comment]
@JohanFreelancer9 - kindly do the copy editor review for this PR. Thanks.

**Comment by illfated** [comment]
@joinimran : There is quite a lot of blank space wasted in this table. Do you mind if I copy, edit, and insert a slimmer table, for easier reading and also for easier future editing? Chances are that most of those lines could be short enough to be kept within one single line without line wrap.

**Comment by illfated** [comment]
This is the table edit I had in mind:
```
| Account management events | Description |
| :-----------------------: | ----------- |
| 4720 | A user account was created.      |
| 4723 | A user password was changed.     |
| 4724 | A user password was set.         |
| 4726 | A user account was deleted.      |
| 4727 | A global group was created.      |
| 4728 | A member was added to a global group. |
| 4729 | A member was removed from a global group. |
| 4730 | A global group was deleted. |
| 4731 | A new local group was created. |
| 4732 | A member was added to a local group. |
| 4733 | A member was removed from a local group. |
| 4734 | A local group was deleted.          |
| 4735 | A local group account was changed.  |
| 4737 | A global group account was changed. |
| 4738 | A user account was changed. |
| 4739 | A domain policy was modified. |
| 4740 | A user account was auto locked. |
| 4741 | A computer account was created. |
| 4742 | A computer account was changed. |
| 4743 | A computer account was deleted. |
| 4744 | A local security group with security disabled was created.<br>
         **Note:**  SECURITY_DISABLED in the formal name means that this group cannot be used to grant permissions in access checks |
| 4745 | A local security group with security disabled was changed. |
| 4746 | A member was added to a security-disabled local security group. |
| 4747 | A member was removed from a security-disabled local security group. |
| 4748 | A security-disabled local group was deleted. |
| 4749 | A security-disabled global group was created. |
| 4750 | A security-disabled global group was changed. |
| 4751 | A member was added to a security-disabled global group. |
| 4752 | A member was removed from a security-disabled global group. |
| 4753 | A security-disabled global group was deleted. |
| 4754 | A security-enabled universal group was created. |
| 4755 | A security-enabled universal group was changed. |
| 4756 | A member was added to a security-enabled universal group. |
| 4757 | A member was removed from a security-enabled universal group. |
| 4758 | A security-enabled universal group was deleted. |
| 4759 | A security-disabled universal group was created. |
| 4760 | A security-disabled universal group was changed. |
| 4761 | A member was added to a security-disabled universal group. |
| 4762 | A member was removed from a security-disabled universal group. |
| 4763 | A security-disabled universal group was deleted. |
| 4764 | A group type was changed. |
| 4780 | Set the security descriptor of members of administrative groups. |
|  685 | Set the security descriptor of members of administrative groups.<br>
         **Note:**  Every 60 minutes on a domain controller a background thread searches all members of administrative groups (such as domain, enterprise, and schema administrators) and applies a fixed security descriptor on them. This event is logged. |
```

**Comment by illfated** [comment]
Resulting table view (Rich Text view):

| Account management events | Description |
| :-----------------------: | :---------- |
| 4720 | A user account was created.      |
| 4723 | A user password was changed.     |
| 4724 | A user password was set.         |
| 4726 | A user account was deleted.      |
| 4727 | A global group was created.      |
| 4728 | A member was added to a global group. |
| 4729 | A member was removed from a global group. |
| 4730 | A global group was deleted. |
| 4731 | A new local group was created. |
| 4732 | A member was added to a local group. |
| 4733 | A member was removed from a local group. |
| 4734 | A local group was deleted.          |
| 4735 | A local group account was changed.  |
| 4737 | A global group account was changed. |
| 4738 | A user account was changed. |
| 4739 | A domain policy was modified. |
| 4740 | A user account was auto locked. |
| 4741 | A computer account was created. |
| 4742 | A computer account was changed. |
| 4743 | A computer account was deleted. |
| 4744 | A local security group with security disabled was created.<br> **Note:**  SECURITY_DISABLED in the formal name means that this group cannot be used to grant permissions in access checks |
| 4745 | A local security group with security disabled was changed. |
| 4746 | A member was added to a security-disabled local security group. |
| 4747 | A member was removed from a security-disabled local security group. |
| 4748 | A security-disabled local group was deleted. |
| 4749 | A security-disabled global group was created. |
| 4750 | A security-disabled global group was changed. |
| 4751 | A member was added to a security-disabled global group. |
| 4752 | A member was removed from a security-disabled global group. |
| 4753 | A security-disabled global group was deleted. |
| 4754 | A security-enabled universal group was created. |
| 4755 | A security-enabled universal group was changed. |
| 4756 | A member was added to a security-enabled universal group. |
| 4757 | A member was removed from a security-enabled universal group. |
| 4758 | A security-enabled universal group was deleted. |
| 4759 | A security-disabled universal group was created. |
| 4760 | A security-disabled universal group was changed. |
| 4761 | A member was added to a security-disabled universal group. |
| 4762 | A member was removed from a security-disabled universal group. |
| 4763 | A security-disabled universal group was deleted. |
| 4764 | A group type was changed. |
| 4780 | Set the security descriptor of members of administrative groups. |
|  685 | Set the security descriptor of members of administrative groups.<br> **Note:**  Every 60 minutes on a domain controller a background thread searches all members of administrative groups (such as domain, enterprise, and schema administrators) and applies a fixed security descriptor on them. This event is logged. |

**Review by JohanFreelancer9 — APPROVED** [review]

**Comment by joinimran** [comment]
@illfated - I always welcome your suggestions and changes in the PR,

**Comment by illfated** [comment]
> @illfated - I always welcome your suggestions and changes in the PR,

Thank you, that is nice to know. 🙂

> Edit: I have removed the spaces as suggested but one I save the file, it goes back the way they were before.

You have done very well. The source text is now exactly as I suggested, moving from originally 15 525 characters down to 2 895, meaning that we have removed 12 630 redundant blank spaces. Hooray! 🎉 🥳

**Review by illfated — APPROVED** [review]
Looks very good to me. Thank you for the editing work! 👍🏼

**Comment by illfated** [comment]
#sign-off

**Pull request merged**
