### PR TITLE
Update distribute-offline-apps.md

### PR DESCRIPTION
**Pull request by Reeced40**
https://github.com/MicrosoftDocs/windows-itpro-docs/issues/4022
Changed instructions

### CODE REVIEW

**Comment by e0i** [comment]
@nenonix @JohanFreelancer9 Copy editing is needed for this PR. Thanks.

**Comment by jvsam** [comment]
Thanks @JohanFreelancer9 for reviewing. @Reeced40 can you please verify the steps again? There is an emphasis on **Shop settings** but the screen shows just the **Shop** tab, hence, it's Manage > Settings > Shop > Shopping experience.

image

CC: @nenonix

**Comment by Reeced40** [comment]
@jvsam Done, thank you.

**Comment by jvsam** [comment]
Thank you @Reeced40 .

@nenonix @JohanFreelancer9 final copy review? Or good to go? :-) Thank you!

**Comment by jvsam** [comment]
Hi @TrudyHa this pull request has been copy edited and is ready for your final review and approval. Please let us know if there are outstanding issues to be resolved prior to merge. Thank you very much.

Hi @Dansimp if you can help with the review and merging so we can close the issue, much appreciated! Thank you.

**Comment by jvsam** [comment]
Thank you for the quick action @Dansimp. Much appreciated!

**Pull request merged**
