### PR TITLE
typo: Double word "be"

### PR DESCRIPTION
**Pull request by nschonni**

### CODE REVIEW

**Comment by illfated** [comment]
I presume the change(s) in line 91 through 94 might be that one or more invisible characters have been replaced by a similar invisible character from a different character set.

**Comment by nschonni** [comment]
Looks like it is one that got affected in #4049 so it probably has mixed line endings

**Comment by e0i** [comment]
See #4062

**Comment by illfated** [comment]
Heh, I missed out on making a joke about "Eric the half a Bee" + "To be or not to be" there. Oh well. Good job, Nick.

**Pull request merged**
