### PR TITLE
Update data-collection-for-802-authentication.md

### PR DESCRIPTION
**Pull request by tayasuta**
"netsh lan show all" command does not exist. I replaced that command with netsh lan show interfaces, profiles, settings.
And I replaced all "\_" to "_".

### CODE REVIEW

**Comment by jdeckerms** [comment]
@kaushika-msft Please review.

**Comment by jdeckerms** [comment]
@tayasuta Thank you!

**Comment by tayasuta** [comment]
@jdeckerms 

it looks like the page is not updated yet. Do i need any additional actions ?
https://docs.microsoft.com/en-us/windows/client-management/data-collection-for-802-authentication

**Comment by jdeckerms** [comment]
@tayasuta Nothing you need to do, it can take a few days for a public pull request to make its way to the live site.

**Comment by tayasuta** [comment]
@jdeckerms  OK. Thank you. I'll wait until the update is published, then delete my branch.

**Pull request merged**
