### PR TITLE
Clarifications with notes for issue #940

### PR DESCRIPTION
**Pull request by j0rt3g4**
Space between lines was already fixed it.
Added the 2 ways to remove packages on windows 10.
And added smart links into the "remove packages" so the people can reference what is the common cmdlets to remove packages. #940

### CODE REVIEW

**Comment by jdeckerms** [comment]
@j0rt3g4 Can you rewrite the tip? I don't know what it's trying to say so I can't rewrite it myself.

**Comment by j0rt3g4** [comment]
@jdeckerms  I've tried to do the rewrite.
Basically attending to the issue, I just wanted to be specific that no matter how you remove the packages using one or the other cmdlet, they can reappear if the computer gets updated from win10 1703 or 1709  to 1803 or (1809)

**Comment by jdeckerms** [comment]
@j0rt3g4 Thanks, it helped me understand what it was trying to say, I still needed to rewrite it. Also, it made more sense in the note at the beginning, where the issue is introduced, so I moved it there.

**Comment by j0rt3g4** [comment]
Thank you very much @jdeckerms ! :) 
Yes, I just wanted to add a note to say that :)

**Pull request merged**
