### PR TITLE
update start-layout-troubleshoot.md

### PR DESCRIPTION
**Pull request by MaratMussabekov**
added info about deprecated feature

### CODE REVIEW

**Comment by MaratMussabekov** [comment]
issue #3478

**Comment by mypil** [comment]
@kaushika-msft - Can you please assist to check, approve and merge the content for this PR based on issue #3478?

Thank you.

**Comment by mypil** [comment]
@kaushika-msft - We would like to follow up. Can you please assist to check, approve and merge the content for this PR based on issue #3478?

Thank you.

**Comment by mypil** [comment]
@Justinha @mjcaparas @greg-lindsay @DaniHalfin @jaimeo @kaushika-msft - Can I ask anyone of you to please  assist to check, approve and merge the content for this PR based on issue #3478?

Thank you.

**Pull request merged**
