### PR TITLE
Added Related Items That's an example on how to use this article. #5520

### PR DESCRIPTION
**Pull request by j0rt3g4**
#5520 
Adding an important links to the article.

### CODE REVIEW

**Comment by mypil** [comment]
@ManikaDhiman - PR is ready for final review.  

Thank you.

**Comment by illfated** [comment]
Ref. #5530

**Comment by j0rt3g4** [comment]
Changed to PR #5578

**Comment by illfated** [comment]
Fair enough, that should clear up the incorrect reference in the original commit title. Thank you. 👍

**Pull request closed without merging**
