### PR TITLE
Update endpoint-detection-response-mac-preview.md

### PR DESCRIPTION
**Pull request by jeremie0**
the flag to enable earlyPreview is --earlyPreview, not --early-preview

### CODE REVIEW

**Comment by e0i** [comment]
@jeremie0 Thank you for your contribution. Would you be able to resolve merge conflicts to proceed with the review?

**Comment by jeremie0** [comment]
@e0i merge conflicts fixed. thanks!

**Comment by illfated** [comment]
BTW, this page and issue topic seems to be the exact same as the one in PR #5378 (**Corrected the command line flag**)  and its preceding issue ticket #5368 (**Command shown is incorrect**).

I am guessing that the MS Docs team member Beth Levin might say the exact same thing about this PR too (although I could be wrong).

**Comment by e0i** [comment]
@jeremie0 Interestingly enough, as mentioned by @illfated, the PR is a duplicate of #5378 which had been rejected by the document author with the comment below:

**levinec** wrote:
> According to the PM, this change is not necessary. "There is no need. We added backward supportability so that both modes work. Changing doc at this point would probably cause more confusion since not all customers have the same version."

_(via https://github.com/MicrosoftDocs/windows-itpro-docs/pull/5378#issuecomment-552580165)_

The PR is thus being marked as a duplicate of #5378 and being closed.

Thank you for taking the time to come up with this contribution and being patient with the process.


Duplicate of #5378

**Pull request closed without merging**
