### PR TITLE
Update encrypted-hard-drive.md

### PR DESCRIPTION
**Pull request by msbemba**
Replaced DEK with AK in the Encrypted hard drive architecture section

Per issue#https://github.com/MicrosoftDocs/windows-itpro-docs/issues/10860

### CODE REVIEW

**Comment by msbemba** [comment]
@JohanFreelancer9 Please copy review

**Review by JohanFreelancer9 — APPROVED** [review]

**Comment by yogkumgit** [comment]
@DulceMontemayor Please merge this PR. Thanks

**Comment by tiburd** [comment]
@aczechowski 
Hi! Do you have a moment to please confirm whether this change is accurate, or refer us to who can confirm its accuracy?
Thank you!

**Comment by frankroj** [comment]
Investigating...

**Comment by yogkumgit** [comment]
@frankroj Kindly update.

**Comment by frankroj** [comment]
PM confirmed changes are correcting. Approving request.

**Comment by frankroj** [comment]
Fixes https://github.com/MicrosoftDocs/windows-itpro-docs/issues/10860

**Pull request merged**
