### PR TITLE
Option 4 does not work.

### PR DESCRIPTION
**Pull request by PhilipElder**
Confirmed with no ETA for the fix.

### CODE REVIEW

**Comment by jdeckerms** [comment]
@PhilipElder Who at Microsoft did you confirm this with?

**Comment by PhilipElder** [comment]
> 
> 
> @PhilipElder Who at Microsoft did you confirm this with?

On a Microsoft NDA list. So, maybe the verbage should be changed a bit?

**Comment by jdeckerms** [comment]
@PhilipElder  Yes, the wording needs a bit of work, but I won't merge it unless I can confirm it myself. Do you have a name of someone at Microsoft that provided that info or confirmed it?

**Comment by PhilipElder** [comment]
Question: Is this conversation public? I'm not really up on GitHub.

**Comment by jdeckerms** [comment]
@PhilipElder Yes, anyone can view open pull requests.

**Comment by PhilipElder** [comment]
I don't see a DM type facility in GitHub? I'm not comfortable tabling anything NDA related (am a MVP). Could you e-mail me direct please?

**Comment by PhilipElder** [comment]
Jeanie, Could you delete the pull request and the content I put in please? I think we need to take this offline first. My bad.

**Comment by PhilipElder** [comment]
Need to delete due to wording changes needed.

**Comment by jdeckerms** [comment]
Closing per email.

**Pull request closed without merging**
