### PR TITLE
Restore broken link in windows-analytics-FAQ-troubleshooting.md

### LINKED ISSUE #3211: Broken link
You can now check on the status of your computers within hours of running the deployment script link is broken.  Can the steps on checking the status be included here?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f20e3377-fdbc-ac87-239e-7184db24a685
* Version Independent ID: 0464da82-efa4-b147-bba9-d6802cf9d273
* Content: [Frequently asked questions and troubleshooting Windows Analytics](https://docs.microsoft.com/en-us/windows/deployment/update/windows-analytics-faq-troubleshooting#feedback)
* Content Source: [windows/deployment/update/windows-analytics-FAQ-troubleshooting.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/master/windows/deployment/update/windows-analytics-FAQ-troubleshooting.md)
* Product: **w10**
* Technology: **windows**
* GitHub Login: @jaimeo
* Microsoft Alias: **jaimeo**

### PR DESCRIPTION
**Pull request by illfated**
**Description:**

The Windows Analytics blog page
 "[You can now check on the status of your computers within hours of running the deployment script](https://blogs.technet.microsoft.com/upgradeanalytics/2017/05/12/wheres-my-data/)" is reported as a Broken Link in issue ticket #3211, because the page has been moved from blogs.technet.microsoft.com to techcommunity.microsoft.com and can be found at

- https://techcommunity.microsoft.com/t5/Windows-Analytics-Blog/You-can-now-check-on-the-status-of-your-computers-within-hours/ba-p/187213

**Proposed change:**

Restore the blog page link by replacing the old link with the new one (shown above).

Closes #3211

### CODE REVIEW

**Comment by mypil** [comment]
@jaimeo - can you please assist to check, approve and merge the content for this PR based on issue #3211?

Thank you.

**Comment by jaimeo** [comment]
I don't have merge rights, but I approve this change.

**Comment by mypil** [comment]
@AndreaBarr  - can you please assist to merge the content for this PR as approved by jaimeo? Please refer to the comment above. 

Thank you.

**Comment by illfated** [comment]
I noticed just moments ago that the PR #3218 was opened less than 2 hours before I opened this PR. Please compare and close my PR here if the other PR contains a more useful version to be merged into the docs.

**Comment by AndreaBarr** [comment]
@illfated Please resolve these conflicts so we can get this reviewed.

**Comment by illfated** [comment]
Closing this PR because it has already been resolved with PR #3218 being merged into the docs. The link change is the same, but PR #3218 contained a slightly better wording in addition to the link correction.

**Comment by illfated** [comment]
Sorry, wrong button.

**Pull request closed without merging**
