### PR TITLE
Grammar and typo corrections in enable-attack-surface-reduction.md

### PR DESCRIPTION
**Pull request by illfated**
**Proposed changes:**
- conjuction => conjunction
- , it's owned by =>  is owned by
- microsoft => Microsoft
- admins => administrators
- Microsoft CLoud's Protection => Microsoft Cloud Protection
- which rules or exclusions apply to. => which rules or exclusions apply to them.

Please review and comment, in particular to request any changes, so I can update this PR directly.

Ref. https://github.com/MicrosoftDocs/windows-itpro-docs/issues/1880#issuecomment-479734075

### CODE REVIEW

**Comment by illfated** [comment]
BTW, this PR replaces my previous attempt #3168 (which got mangled by merging updates from master).

**Comment by jdeckerms** [comment]
@illfated Can you take out your changes to the note? It's being fixed in PR #3148  (https://github.com/MicrosoftDocs/windows-itpro-docs/pull/3148) and the information still needs confirmation. If you change the same note, we'll have a merge conflict. Thanks!

**Comment by illfated** [comment]
Thank you for making me aware of the pending PR regarding the same material.
I prefer making a new PR for just the missing letter, indicating the very small change.

**Comment by Justinha** [comment]
Sorry for the hassle, I merged PR #3148 (#3148) and all other changes should be able to converge now.

**Pull request closed without merging**
