### PR TITLE
added missing SAN to the instruction

### PR DESCRIPTION
**Pull request by MaratMussabekov**
#6252

### CODE REVIEW

**Comment by MaratMussabekov** [comment]
Dear @JohanFreelancer9, could you please have a look?
Thank you

**Comment by illfated** [comment]
#sign-off

**Comment by MaratMussabekov** [comment]
Dear @e0i, for your information

**Comment by illfated** [comment]
Ready for final review & merge.

**Comment by e0i** [comment]
@denisebmsft The PR has been approved by the document author can be merged. Thank you.

**Comment by e0i** [comment]
> @denisebmsft The PR has been approved by the document author can be merged. Thank you.

cc @martyav

**Pull request merged**
