### PR TITLE
added Windows Server 2008 R2 to the list

### PR DESCRIPTION
**Pull request by Malind19**

### CODE REVIEW

**Comment by illfated** [comment]
Ref. issue #3208 (Documentation says Server 2012 and above. ATP portal lists Server 2008 R2 as option for onboarding?)

**Comment by mypil** [comment]
@mjcaparas - Can you please assist to check, approve and merge the content for this PR based on issue #3208?

Thank you.

**Comment by mjcaparas** [comment]
Checking with team as this might be appearing on the portal for preview.

**Comment by mypil** [comment]
@mjcaparas - Do you have any updates on this? Thank you.

**Comment by mjcaparas** [comment]
Yes, confirmed that it is in preview. The documentation will be updated when it is officially available.

**Pull request closed without merging**
