### PR TITLE
Update hololens2-autopilot.md

### PR DESCRIPTION
**Pull request by Mizanurra**
Corrected ARC and HoloLens  OS version minimum requirements.

### CODE REVIEW

**Comment by lavinders** [comment]
test

**Comment by Dansimp** [comment]
@Mizanurra, is this PR ready to be merged? Or is this still in progress?

**Comment by scooley** [comment]
@Dansimp ready to merge :)

**Comment by Mizanurra** [comment]
Yes, this is ready to be merged. :)

**Pull request merged**
