### PR TITLE
Include information for behavior when specifying multiple WMI queries…

### PR DESCRIPTION
**Pull request by byteben**
… in the same filter

There seems to be a lot of misinformation in various blogs around the behavior of specifying multiple WMI queries in the same WMI filter.

For example, if I have these two queries on one filter:-

1. Select * from Win32_ComputerSystem WHERE Model = "Optiplex 7060" or Model = "Optiplex 3060"
2. Select * from Win32_OperatingSystem WHERE Version LIKE "10.0.%" and ProductType = "1"

Would both have to return True for the Filter to return True?

An explanation of whether multiple queries on the same filter are treated as AND/OR would be helpful.
Thanks, Ben

### CODE REVIEW

**Comment by e0i** [comment]
@dansimp Would you be able to review this PR contributed by the community? Thanks.

**Comment by e0i** [comment]
@Dansimp Any updates?

**Comment by e0i** [comment]
@Dansimp Following up for updates.

**Comment by e0i** [comment]
@Dansimp Following up for updates.

**Comment by illfated** [comment]
This looks a lot more like a question that could be handled more correctly in an issue ticket instead of a Pull Request. The suggested addition to the page does not really help in making the page better for documentation purposes. I would advise a Feedback ticket on the page itself instead, opening for suggestions to what should be inserted at that point in the document instead.

The related page (and specific section) is:
https://docs.microsoft.com/windows/security/threat-protection/windows-firewall/create-wmi-filters-for-the-gpo#to-create-a-wmi-filter-that-queries-for-a-specified-version-of-windows
**Feedback section:**
https://docs.microsoft.com/windows/security/threat-protection/windows-firewall/create-wmi-filters-for-the-gpo#feedback

**Comment by e0i** [comment]
@byteben Although creating an issue would be more suitable for the intents of creating this PR, we are interpreting this PR as an issue.

The "issue" has thus been noted and the document will be revised in the light of your feedback.

 Thank you for providing feedback.

**Comment by byteben** [comment]
Hey, thanks!

Kind Regards
Ben

Sent from my iPhone

On 10 Sep 2019, at 19:56, Onur <notifications@github.com<mailto:notifications@github.com>> wrote:


@byteben<https://github.com/byteben> Although creating an issue would be more suitable for the intents of creating this PR, we are interpreting this PR as an issue.

The "issue" has thus been noted and the document will be revised in the light of your feedback.

Thank you for providing feedback.

**Comment by DaniHalfin** [comment]
The default branch for this repository has changed. Commenting to remember to merge this to the new default, if this PR gets merged.

**Comment by e0i** [comment]
@byteben 

The default branch for this repository has changed from `master` to `public`. Please edit your pull request to change the merge target to `public` via the `Edit` button at the top right corner. Thanks.

**Comment by byteben** [comment]
Thanks, I don’t see a public base branch...

[image1.jpeg]

Kind Regards
Ben

Sent from my iPhone

On 11 Sep 2019, at 10:40, Onur <notifications@github.com<mailto:notifications@github.com>> wrote:


@byteben<https://github.com/byteben>

The default branch for this repository has changed from master to public. Please edit your pull request to change the merge target to public via the Edit button at the top right corner. Thanks.

**Comment by e0i** [comment]
@byteben Apologies, No such changes necessary for this PR as we are interpreting it as an issue. Just a copy-paste mistake from my part. Thanks.

**Comment by MaratMussabekov** [comment]
Hello, @byteben ,
**For example, if I have these two queries on one filter: Would both have to return True for the Filter to return True?** - yes, both must be TRUE.
I created PR to add this clarification to the article
Thank you

**Comment by byteben** [comment]
Great, thank you! :)

Kind Regards
Ben

Sent from my iPhone

On 24 Sep 2019, at 07:12, MaratMussabekov <notifications@github.com> wrote:

﻿

Hello, @byteben<https://github.com/byteben> ,
For example, if I have these two queries on one filter: Would both have to return True for the Filter to return True? - yes, both must be TRUE.
I created PR to add this clarification to the article
Thank you

**Comment by e0i** [comment]
@byteben 

With the help of your feedback, the content has been updated with relevant changes accordingly, and the PR associated with this issue, #5019 has been merged.Thanks.

**Pull request closed without merging**
