### PR TITLE
Windows/Deployment: rectify image names with uppercase file extension

### PR DESCRIPTION
**Pull request by illfated**
**Changes proposed:**

- Rename file name extensions using uppercase `.PNG` to lowercase `.png` to show the linked images in the Github source code page.

All Github image file name extensions should be lowercase for the source code page to show the images.
(Lookup the PNG file name extensions in [/windows/deployment/images/](https://github.com/MicrosoftDocs/windows-itpro-docs/tree/master/windows/deployment/images) .)

This PR is specific to the file https://github.com/MicrosoftDocs/windows-itpro-docs/blob/master/windows/deployment/deploy-m365.md .
The same solution could be applied to all the other pages missing its images due to wrong uppercase .PNG or .JPG file name extension, unless the Docs team finds a more convenient method of converting the uppercase file extensions to lowercase.

Mentioning @DaniHalfin as requested, for notification of this PR upon creation.

Ref. issue ticket #2909

### CODE REVIEW

**Comment by illfated** [comment]
Renaming the files works, see my local fork version of the affected page:
https://github.com/illfated/windows-itpro-docs/blob/779191c4c2adb0889b2e18ff837d460a5659f294/windows/deployment/deploy-m365.md#microsoft-365-deployment-advisor-example

Compare with the original master branch Github page:
https://github.com/MicrosoftDocs/windows-itpro-docs/blob/master/windows/deployment/deploy-m365.md#microsoft-365-deployment-advisor-example

**Comment by illfated** [comment]
(By the way, if you find this type of solution useful & practical, feel free to ask for another PR with all the image files renamed to their lowercase equivalents.)

**Comment by illfated** [comment]
@DaniHalfin : Did you get the notification you asked for, to see my PR?

**Comment by illfated** [comment]
Looks like I had to do first part of the operation on my Windows 10 computer, then delete the .PNG file in my forked repository to effectively create a file rename here on Github.

Not sure if this is what I have to do in a follow-up PR to rename the remaining files with uppercase file name extensions, or if I can manage to do both if I am careful enough when changing the file names.

**Comment by mypil** [comment]
@DaniHalfin - can you please assist to check, approve and merge the content for this PR? 

Thank you.

**Comment by DaniHalfin** [comment]
Merging and adding @jaimeo FYI.

**Comment by DaniHalfin** [comment]
@illfated hold on the other renames. Now that we know it works, we're going to take it up with GH to see what they suggest.

**Comment by DaniHalfin** [comment]
and thanks for checking this out!!

**Pull request merged**
