### PR TITLE
Update windows-10-enterprise-faq-itpro.md

### PR DESCRIPTION
**Pull request by lindspea**
https://github.com/MicrosoftDocs/windows-itpro-docs/issues/962
New link for Windows Onboarding kit

### CODE REVIEW

**Comment by mypil** [comment]
@brianlic-msft @Justinha - can you please assist to check, approve and merge the content for this PR based on issue #962?

Thank you.

**Comment by lindspea** [comment]
@Justinha Done, thanks Justin.

**Comment by mypil** [comment]
@Justinha - can you please assist to check, approve and merge the content for this PR based on issue #962?

Thank you.

**Comment by Justinha** [comment]
@lindspea Thanks Lindsay!

**Comment by lindspea** [comment]
@mypil this can be closed thank you.

**Pull request merged**
