### PR TITLE
DenyLocalLogOn description updated as incorrect

### PR DESCRIPTION
**Pull request by silvermarkg**
## Description
Updated DenyLocalLogOn description as it was incorrectly referring to DenyLogOnAsService

## Why
DenyLocalLogOn description is incorrect which could lead users to misinterpret the setting.

## Changes
Updated DenyLocalLogOn description

### CODE REVIEW

**Comment by aczechowski** [comment]
Thanks @silvermarkg for the edit, although unfortunately we won't be able to accept it. Most of the CSP documentation is now automated from the DDF and ADMX source files. So even if we took this change now, it would reset in a few weeks when the process runs. For more information, see [Contributing to the CSP reference articles](https://learn.microsoft.com/windows/client-management/mdm/contribute-csp-reference).

I'm going to keep this open though until next week for @vinaypamnani-msft to review, because it's tingling the back of my brain. Like maybe there's a known issue with this policy or something. 🤔

**Comment by silvermarkg** [comment]
No problem and thanks for the link. At least it's been raised for awareness 😊

**Comment by vinaypamnani-msft** [comment]
Closing this PR. I'd already filed a bug for this internally, once it's resolved, the docs will automagically pick up the changes.

**Comment by aidbish** [comment]
This is still an issue with incorrect description, i have also submitted a pull request

**Pull request closed without merging**
