### PR TITLE
Update windows-update-resources.md

### PR DESCRIPTION
**Pull request by soyfrien**
This doesn't work in PowerShell, which wasn't clear enough for me.

```
Windows PowerShell
Copyright (C) Microsoft Corporation. All rights reserved.

Install the latest PowerShell for new features and improvements! https://aka.ms/PSWindows

PS C:\Users\Louis> net stop wuauserv
The Windows Update service is not started.

More help is available by typing NET HELPMSG 3521.

PS C:\Users\Louis> rd /s /q %systemroot%\SoftwareDistribution
Remove-Item : A positional parameter cannot be found that accepts argument '/q'.
At line:1 char:1
+ rd /s /q %systemroot%\SoftwareDistribution
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidArgument: (:) [Remove-Item], ParameterBindingException
    + FullyQualifiedErrorId : PositionalParameterNotFound,Microsoft.PowerShell.Commands.RemoveItemCommand

PS C:\Users\Louis> net start wuauserv^C
PS C:\Users\Louis> cmd
Microsoft Windows [Version 10.0.21376.1]
(c) Microsoft Corporation. All rights reserved.

C:\Users\Louis>net stop wuauserv
The Windows Update service is not started.

More help is available by typing NET HELPMSG 3521.


C:\Users\Louis>rd /s /q %systemroot%\SoftwareDistribution

C:\Users\Louis>net start wuauserv
The Windows Update service is starting.
The Windows Update service was started successfully.
```

### CODE REVIEW

**Review by JohanFreelancer9 — APPROVED** [review]

**Comment by soyfrien** [comment]
Many thanks, @JohanFreelancer9.

**Comment by soyfrien** [comment]
Sorry I thought the merge was complete. Apologies.

**Review by illfated — APPROVED** [review]

**Comment by illfated** [comment]
#sign-off

**Comment by jaimeo** [comment]
"Command prompt" is the correct term for cmd.exe, which is where you are supposed to run those commands.

**Pull request closed without merging**
