### PR TITLE
removed the video configuration file, added new link

### PR DESCRIPTION
**Pull request by RAJU2529**
its my own issue ,  i added below link

*https://www.youtube.com/embed/KYVptkpsOqs*

### CODE REVIEW

**Comment by illfated** [comment]
Please see my comments in issue #5880 . This is not about the page content, it is about an incorrect link (different from the web page) in the PDF page 7 of "Windows Autopilot" (133 pages).

**Comment by e0i** [comment]
@illfated The PDF is generated from the page content. The fix, therefore, seems legitimate. Thank you for your careful feedback, as always. Much appreciated.

@RAJU2529 Rolling the PR into the review. Thank you for your ongoing contributions.

**Comment by e0i** [comment]
@JohanFreelancer9 Minor style checks needed for this PR. Thanks.

**Comment by e0i** [comment]
Closes #5880

**Comment by illfated** [comment]
Well done, good job. I was too stressed today to notice the full sequence of interaction on that page. Thank you for the feedback. @RAJU2529 : Thank you for all of your contributions,

**Pull request merged**
