### PR TITLE
Update hololens-calibration.md

### PR DESCRIPTION
**Pull request by kevincol**

### CODE REVIEW

**Comment by illfated** [comment]
Ref. #5114 (different wording in the PR, but still empty description)

**Comment by e0i** [comment]
@kevincol Would you be able to follow up with revision suggestions provided by the document author, *Teresa-Motiv*? We would like to proceed with this PR. Thanks.

**Comment by illfated** [comment]
Please also consider which one of the Pull Requests (#5113 , #5114 ) to keep, because they will be in conflict with each other, targeting the same file in the same branch.

**Comment by Dansimp** [comment]
Duplicate of #5114. Closing this PR

**Pull request closed without merging**
