### PR TITLE
Corrected grammar and misleading information

### PR DESCRIPTION
**Pull request by poortom1004**
Domain Members changed to domain Controllers, as this group only exists for domain controllers.

### CODE REVIEW

**Comment by poortom1004** [comment]
Created PR to resolve https://github.com/MicrosoftDocs/windows-itpro-docs/issues/8431

**Comment by e0i** [comment]
@JohanFreelancer9 Copy editing is needed for this PR. Thanks.

**Review by JohanFreelancer9 — APPROVED** [review]

**Comment by poortom1004** [comment]
I am new to this and not sure what is meant by copy editing is needed.

**Comment by JohanFreelancer9** [comment]
@poortom1004 - it just means that every change to an article has to be checked by a copy editor for errors. In this instance, I have already done the copy editing and did not find any errors.

**Comment by illfated** [comment]
Practical information: if you add a single line, saying "Closes #8431" to the bottom of your main PR comment, your issue ticket will automatically be closed when this PR gets merged. Example text:

Closes #8431

**Review by illfated — APPROVED** [review]

**Pull request merged**
