### PR TITLE
Just now i  edited and added new link

### PR DESCRIPTION
**Pull request by RAJU2529**
i found another link which contains title "Overview of Windows as a service"
so  replaced old  broken link with new link 
**https://docs.microsoft.com/en-us/windows/deployment/update/waas-overview**

So allow my PR  and  approve it soon.
Thanking you

### CODE REVIEW

**Comment by illfated** [comment]
Please do not change that link. It is a relative link for the Github pages
(not to be confused with the docs.microsoft.com pages).

**Comment by RAJU2529** [comment]
@illfated.ok sir  . I noted Down it now. Next time before changing, I will send information sir

**Comment by illfated** [comment]
Fair enough. May I ask for this PR to be closed as well? (unless there is something else on this page in need of changing)

**Comment by RAJU2529** [comment]
@illfated .broken link must be changed. I mentioned new link earlier in PR . please add link in this document and then close this PR.
Thanking you

**Comment by illfated** [comment]
Aha. I see. I presume you are referring to #4146 ( **Link 404**).
The problem is that the broken link you are referring to
can only be fixed by Microsoft employees with write access
to the docs.microsoft.com official public page.

We ordinary users do not even need to suggest changes to the Github page,
because the error happened when the public page link was translated via script
from MarkDown (here on Github) to HTML (on https://docs.microsoft.com/).

**Comment by RAJU2529** [comment]
@illfated .I thought github site administrator can change this type PR. I am not from Microsoft. that means I don't have write access. 
What type of permission I can get from github

**Comment by illfated** [comment]
My point is:
- Github page is OK, link is NOT broken: https://github.com/MicrosoftDocs/windows-itpro-docs/blob/master/windows/whats-new/ltsc/index.md
- Microsoft Docs page link is broken: https://docs.microsoft.com/en-us/windows/whats-new/ltsc/
  (For detailed information about Windows 10 servicing, see [Overview of Windows as a service](https://docs.microsoft.com/en-us/windows/deployment/update/waas-overview.md).)

We non-Microsoft users should not post any PR for this problem, because in this case, we don't want to change the Github page.

I recommend closing this Pull Request, because the follow-up from Microsoft Docs authors or MS engineers needs to be an internal task, following the natural chain of command, based on the issue #4146 ( **Link 404** ). This means that the issue ticket #4146 can be closed when the page https://docs.microsoft.com/en-us/windows/whats-new/ltsc/ has been corrected by a Microsoft employed web admin.

**Comment by jvsam** [comment]
Hi @RAJU2529 the link attribute has been updated on docs.microsoft.com. As explained by @illfated , the github document does not have any problem, so no change is necessary. I have also closed #4146 . Thank you so much.

**Comment by illfated** [comment]
Issue solved by internal update publicized 06/25/2019 (4 days ago as of the time of this comment). Thank you for keeping us updated on this issue.

@RAJU2529 : Feel free to close this pull request as time permits.

**Comment by illfated** [comment]
(Follow-up to my previous comment.)
The link on the docs.microsoft.com page has now been corrected,
but at the cost of breaking the link on Github. Not sure what to do now.

**Comment by RAJU2529** [comment]
i am closing this issue

**Pull request closed without merging**
