### PR TITLE
WDAC/policy design decisions: typo correction

### LINKED ISSUE #6346: Typo
"Your organization has a well-defined process for application management and deployed." is not a complete sentence.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1c360225-c6aa-04e2-6856-500e9bc11320
* Version Independent ID: 4b27602c-27e0-3154-757d-20f483d7e10f
* Content: [Understand Windows Defender Application Control policy design decisions  (Windows 10) - Windows security](https://docs.microsoft.com/en-us/windows/security/threat-protection/windows-defender-application-control/understand-windows-defender-application-control-policy-design-decisions#feedback)
* Content Source: [windows/security/threat-protection/windows-defender-application-control/understand-windows-defender-application-control-policy-design-decisions.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/public/windows/security/threat-protection/windows-defender-application-control/understand-windows-defender-application-control-policy-design-decisions.md)
* Product: **w10**
* Technology: **windows**
* GitHub Login: @jsuther1974
* Microsoft Alias: **dansimp**

### PR DESCRIPTION
**Pull request by illfated**
**Description:**

As reported in issue ticket #6346 (**Typo**), one of the sentences in the bullet point list 
ends with a malformed word or phrase: "... application management and deployed."

Thanks to @TokenRing (Zach) for finding and reporting this grammatical typo.

**Proposed change:**
- Replace the word "deployed" with *deployment* to match the grammar.

**Ticket closure or reference:**

Closes #6346

### CODE REVIEW

**Comment by illfated** [comment]
Simple 1 word correction. Mostly only needs approval by the author or project manager, although a copy review for the rest of the document is fine too.

@JohanFreelancer9 : If you would be so kind, please do a copy review on this document. Any changes you recommend, even for the entire document, is OK with me.

**Comment by illfated** [comment]
#sign-off

**Comment by illfated** [comment]
Currently: "Your organization has a well-defined process for application management and deployment."
Your idea: "Your organization has a well-defined process and customized policies for application management and deployment method."

Well, I will consider it, but before making that change, I would very much like to hear what the author thinks is the more correct phrasing in that line.

**Comment by TokenRing** [comment]
Hi folks... "deployment method" does not fit in the context of the
sentence. You could make method into methods and it would work better.

But I believe the best phrasing was the one proposed first. Just change
"deploy" into "deployment" and leave it at that.

As a non-Microsoft employee, I'm impressed with your animated and quick
discussion about a single sentence. Kudos to you all.

**Comment by RAJU2529** [comment]
@illfated . I will be watching for this PR. Thanks for considering

**Comment by illfated** [comment]
@TokenRing ; Thanks for the nice words, but I would like to offer the fact that I am not a Microsoft employee. I just like to contribute when I can, based on my 5 years of experience with GitHub as a platform. JohanFreelancer9 may be on the MS payroll, although I have not actually asked about those details before. Last, but not least, Varadharajan K is more of an enthusiastic student of Microsoft software technology in addition to being a teacher and an avid forum member elsewhere. I hope you find that enlightening enough, considering your positive reaction to our response in general.

**Comment by mypil** [comment]
@Dansimp - PR has been copy edited and is ready for final review. This is based on issue #6346.

Thank you.

cc: @kenwith

**Pull request merged**
