### PR TITLE
Informations about Device Encryption and corrected names

### PR DESCRIPTION
**Pull request by Van-Fouran**
Due to https://github.com/MicrosoftDocs/windows-itpro-docs/issues/3504 and https://social.technet.microsoft.com/Forums/en-US/536b1613-22e6-4190-9b9a-d159b536146d/bitlocker-device-encryption-vs-device-encryption?forum=win10itprosecurity the naming of the two encryption features offered by Microsoft seems unclear. In this proposal, I have taken the recommendation from the Technet Forum into account and called the two features "BitLocker" or "Device Encryption".
Furthermore, there seems to be confusion about the system requirements, as well as the functionality of the device encryption.

### CODE REVIEW

**Comment by illfated** [comment]
@lindspea : May we have your views on these changes, as well as possibly the author & manager of this document, before any time is spent reviewing the spelling, grammar, syntax & wording?

**Comment by e0i** [comment]
@Dansimp Any updates with the evaluation of this PR? Thanks.

**Comment by Van-Fouran** [comment]
Can I support you somehow?

**Comment by illfated** [comment]
Frankly speaking, there is not much to be done before we hear from the current document author or manager, subsequently what kind of feedback they get from their teams.

**Comment by e0i** [comment]
@Van-Fouran We'll keep pinging the doc authors until we hear back from them and contact them directly when necessary. Thank you for following up.

**Comment by e0i** [comment]
Still under escalation.

**Comment by Van-Fouran** [comment]
@e0i Thank you for the feedback. Like said before: If there's anything I can do to help, please let me know.

**Comment by Van-Fouran** [comment]
Is this case still under investigation?

**Comment by e0i** [comment]
@Van-Fouran Yes, Pending input from product team. Would you be able to resolve merge conflicts in the meantime? Thank you for your contributions.

**Comment by e0i** [comment]
@Van-Fouran We have been informed that the PR "needs a lot more investigation and analysis" and the authors haven't had the time to follow up. Further, _updated info_ is pending to move forward with the review.

Thank you for your patience with the process.

**Comment by e0i** [comment]
Closes #4916

**Comment by illfated** [comment]
Rich Text Diff view, updated:
https://github.com/MicrosoftDocs/windows-itpro-docs/pull/4913/files?short_path=328cca9#diff-328cca90bc9fbadfb2c183c84199c6e9

**Comment by Van-Fouran** [comment]
Is this case still under investigation?

**Comment by illfated** [comment]
@e0i : Would you mind checking who among the team members could comment on the status "needs a lot more investigation and analysis" ?

**Comment by Van-Fouran** [comment]
The feature which is called "BitLocker device encryption" on this page: https://www.microsoft.com/en-us/windows/compare-windows-10-home-vs-pro
seems to be called "BitLocker drive encryption" on this page: https://docs.microsoft.com/en-us/windows/security/information-protection/bitlocker/bitlocker-use-bitlocker-drive-encryption-tools-to-manage-bitlocker

Probably it would make sense to review the whole BitLocker section.

**Comment by illfated** [comment]
Fair point. I hope we can get some more feedback regarding your suggestions, just so we may know a bit more about how long time it may take to make the decisions.

**Comment by Van-Fouran** [comment]
Would it help if I would check the section and expand my PR?

**Comment by illfated** [comment]
Good question, I am not quite sure. The normal assumption is that smaller PRs get merged faster, but if the affected extra material depends on the existing content in this PR being merged at the same time, it could be more useful to expand this PR. The doc author should be able to give more precise advice. Otherwise, it is mostly up to you and the use of common sense.

**Comment by Van-Fouran** [comment]
I close this Pull request, since I am currently working on a new PR containing bug fixing for the whole BitLocker section.

**Comment by Van-Fouran** [comment]
A new pull request regarding this topic is available: https://github.com/MicrosoftDocs/windows-itpro-docs/pull/6244
I would appreciate feedback.

**Comment by saan5** [comment]
Note: Support for the Diagnostic Data Viewer is available for Microsoft Teams on devices running Android. Support for Teams on devices running Windows, macOS, or iOS is being worked on.

**Comment by saan5** [comment]
# # # #

**Pull request closed without merging**
