### PR TITLE
Fixed typo (Microoft)

### PR DESCRIPTION
**Pull request by hubalazs**

### CODE REVIEW

**Comment by e0i** [comment]
@dulcemontemayor The PR that addresses a minor typo is available for review. Thanks.

**Comment by e0i** [comment]
@DulceMontemayor Following up for updates.

**Comment by DaniHalfin** [comment]
The default branch for this repository has changed. Commenting to remember to merge this to the new default, if this PR gets merged.

**Comment by e0i** [comment]
@hubalazs 

The default branch for this repository has changed from `master` to `public`. Please edit your pull request to change the merge target to `public` via the `Edit` button at the top right corner. Thanks.

**Comment by illfated** [comment]
Maybe Daniel Simpson could follow up this PR instead, if the author is occupied with something else?

**Comment by e0i** [comment]
@martyav Would you be able to review and merge this PR that introduces a minor typo? Thanks.

**Comment by illfated** [comment]
😉 (Forgive me for being nit-picky, but "introduces a minor typo" looks somewhat backwards to me. I am fairly sure you meant any of the following instead: fixes / rectifies / corrects / resolves a typo ) 😄

**Comment by e0i** [comment]
> wink (Forgive me for being nit-picky, but "introduces a minor typo" looks somewhat backwards to me. I am fairly sure you meant any of the following instead: fixes / rectifies / corrects / resolves a typo ) smile

Thank you for helping me resolve this minor "semantic typo." :)

**Comment by e0i** [comment]
@martyav @Dansimp Would you be able to review and merge this PR that fixes a minor typo? Thanks.

**Comment by illfated** [comment]
As previously mentioned, the Rich Text Diff view (https://github.com/MicrosoftDocs/windows-itpro-docs/pull/4884/files?short_path=d8687b6#diff-d8687b60ccc7a48c4cd3a2dfce8b9645) highlights the change better than the regular code view.

**Pull request merged**
