### PR TITLE
added windows update URLs

### PR DESCRIPTION
**Pull request by joinimran**
As requested by the user, I have added windows update URLs in the doc. Reset of the required information is available in the document. 

Problem: https://github.com/MicrosoftDocs/windows-itpro-docs/issues/5154

### CODE REVIEW

**Comment by e0i** [comment]
@Dansimp The PR that has been approved by the document owner can be merged. Thanks.

**Comment by illfated** [comment]
Very good update. Well done. 👍

**Comment by jaimeo** [comment]
@joinimran could you e-mail me directly? I have a question about this update I need your help with.

**Comment by joinimran** [comment]
Sorry I am not able to find your email address. Feel free to drop me email at joinimran@gmail.com

**Comment by illfated** [comment]
@joinimran 
- https://social.technet.microsoft.com/Profile/jaime%20ondrusek%20-%20msft

**Pull request merged**
