### PR TITLE
Updated the link

### PR DESCRIPTION
**Pull request by joinimran**
The old link was not working. Looks like its only available in English, because when I try to open it  as https://www.microsoft.com/CloudandHosting/licensing_sca.aspx it says page not available.

Problem: https://github.com/MicrosoftDocs/windows-itpro-docs/issues/9222

### CODE REVIEW

**Comment by joinimran** [comment]
@JohanFreelancer9 - kindly do the copy editor review for this PR. Thanks.

**Review by illfated — APPROVED** [review]
I concur. The linked page does not appear to be language agnostic, possibly due to different Licensing rules in other countries than the United States.

**Review by JohanFreelancer9 — APPROVED** [review]

**Comment by greg-lindsay** [comment]
Hi - this page always seems to get "corrected" when we include the en-us in the URL. It didn't have it originally, but it keeps getting changed. I change it back, then it gets changed again.  So, we should just use an aka link instead I think to fix this issue.  Let's do that.

**Comment by greg-lindsay** [comment]
Do you need me to create the aka link or can someone else do it?

**Comment by joinimran** [comment]
@greg-lindsay - Please go ahead and create aka link as I don't have permissions to create aka links.

Thanks
Imran.

**Comment by nam31** [comment]
@greg-lindsay please do the copy editor review for this PR.

**Review by JohanFreelancer9 — APPROVED** [review]

**Review by illfated — APPROVED** [review]

**Comment by greg-lindsay** [comment]
The tool has been down for me for quite a while. I'll see if it is available again.

**Review by greg-lindsay — APPROVED** [review]

**Comment by greg-lindsay** [comment]
the aka link already existed as aka.ms/qmth

**Pull request merged**
