### PR TITLE
Update copy-a-gpo-to-create-a-new-gpo.md

### PR DESCRIPTION
**Pull request by msbemba**
Added a snip of how to paste in the GPO object

Fixes #https://github.com/MicrosoftDocs/windows-itpro-docs/issues/10677

### CODE REVIEW

**Comment by msbemba** [comment]
@JohanFreelancer9 Please copy review

**Review by JohanFreelancer9 — APPROVED** [review]

**Comment by yogkumgit** [comment]
@Dansimp Please merge this PR. Thanks

**Comment by vinaypamnani-msft** [comment]
@msbemba @yogkumgit Where is the actual image? I don't see the image file, just the link to it.

**Comment by msbemba** [comment]
Looks like the png file did not get linked to this PR> I have opened another one #https://github.com/MicrosoftDocs/windows-itpro-docs/pull/11046

Could you please check if this one works?

**Pull request closed without merging**
