### PR TITLE
Added Windows Server 2016 in the list

### PR DESCRIPTION
**Pull request by joinimran**
This article is also applicable on Windows Server 2019 and it has been added in the doc.

Problem: https://github.com/MicrosoftDocs/windows-itpro-docs/issues/4345

### CODE REVIEW

**Comment by jvsam** [comment]
Hi @nenonix and @JohanFreelancer9 for copy review please. Thanks.

**Comment by jvsam** [comment]
Hi @mdsakibMSFT this pull request has been copy edited and is ready for your final review and approval. Please let us know if there are outstanding issues to be resolved prior to merge. Thank you very much.

CC: Apologies for CCing you here @Justinha, I am not sure if the author information is accurate. Can you help us? Thank you.

**Comment by Justinha** [comment]
@mdsakibMSFT sorry I might be mistaken here. I actually think this topic applies only to Windows 10 and Windows Server 2019, unless it was backported to Windows Server 2016. If you can confirm or correct me I appreciate it.

**Comment by jvsam** [comment]
Thank you for the assistance @Justinha, much appreciated.

@mdsakibMSFT hoping to hear from you so we can close the main issue. Thank you.

**Pull request merged**
