### PR TITLE
Update update-compliance-configuration-manual.md

### PR DESCRIPTION
**Pull request by lindspea**
https://github.com/MicrosoftDocs/windows-itpro-docs/issues/6901
Added note.

### CODE REVIEW

**Comment by e0i** [comment]
@JohanFreelancer9 Copy editing is needed for this PR. Thanks.

**Comment by jaimeo** [comment]
@cinglis-msft are you OK with this edit?

**Review by JohanFreelancer9 — APPROVED** [review]

**Comment by nam31** [comment]
Hi @jaimeo PR has been copyedited and is ready for final review, could you please check and merge? Thanks!

**Comment by jaimeo** [comment]
@nam31 I want verification from @cinglis-msft that this edit is accurate first.

**Comment by jaimeo** [comment]
@cinglis-msft approves.

**Pull request merged**
