### PR TITLE
Update volume-activation-windows-10.md

### PR DESCRIPTION
**Pull request by baardhermansen**
Updated wording.
Updated links. 
A bit of reformatting.

### CODE REVIEW

**Comment by illfated** [comment]
Rich Text Diff view, for easier overview of the changes:
https://github.com/MicrosoftDocs/windows-itpro-docs/pull/5082/files?short_path=f05069d#diff-f05069d26735f8a569c41af2abfa69e4

@baardhermansen : Why replace the `em` style dash (old line number 46) with a regular dash (new line number 48)?
From a reader's point of view, I don't see the improvement, it looks more like an unnecessary simplification.

At first glance, the rest of the content looks fine, but I will still recommend a copy review.

**Comment by baardhermansen** [comment]
@illfated The replacement of the dash is because the previous version look like a hyphen, thus making reading slightly more cumbersome.

**Comment by illfated** [comment]
Oh. Very well, fair enough. I looked up "hyphen or em dash" just now and it appears that _hyphen_ is the term I meant instead of "dash" as in regular usage of a hyphen. I presume my preference comes from seeing the em dash being used in formal writing, whereas the hyphen is used in modern writing more like an alternative type of spacing.

**Comment by e0i** [comment]
@greg-lindsay The PR provides minor Markdown formatting fixes. Please review and merge as the time permits. Thanks.

**Comment by baardhermansen** [comment]
I'm not really a fan of the hyphen any way, would actually have preferred using commas, but YMMV.

**Comment by illfated** [comment]
Fair enough. As a matter of fact, the same part of the sentence does in fact work completely without hyphens, commas or em dash if that looks more readable:

> Volume activation and the need for activation itself is not new, and this guide does not review all of its concepts and history.

The importance of separation or differentiation of the inserted clause is usually the author's privilege, depending on the intended focus and overall meaning.

**Comment by e0i** [comment]
@greg-lindsay Following up for updates. Thanks.

**Pull request merged**
