### PR TITLE
added missing link

### PR DESCRIPTION
**Pull request by VLG17**
https://github.com/MicrosoftDocs/windows-itpro-docs/issues/2885

### CODE REVIEW

**Comment by mypil** [comment]
@DaniHalfin - Can you please assist to check, approve and merge the content for this PR based on issue #2885?

Thank you.

**Comment by mypil** [comment]
@DaniHalfin - We would like to follow up. Can you please assist to check, approve and merge the content for this PR based on issue #2885?

Thank you.

**Comment by mypil** [comment]
@AndreaBarr - would you be able to merge the content of this PR based on issue #2885? This is just adding a link in the article. 

Thank you.

**Comment by illfated** [comment]
... and if Andrea Barr is unavailable, maybe @jdeckerms could help out, seeing that she is one of the contributors to this page.

**Comment by DaniHalfin** [comment]
Thanks :)

**Pull request merged**
