### PR TITLE
changedf user 2 to user1 and viceversa

### PR DESCRIPTION
**Pull request by RAJU2529**
as per user report #10862, so i changed  user2 to user 1 and viceversa

## Why

- Closes #[Issue Number]

### CODE REVIEW

**Review by JohanFreelancer9 — APPROVED** [review]

**Comment by yogkumgit** [comment]
@frankroj Please review and signoff this PR. Thanks

**Comment by yogkumgit** [comment]
@frankroj Please review and signoff this PR. Thanks

**Comment by frankroj** [comment]
The change is most likely not correct. The correct syntax most likely is:

LoadState.exe  [\\server\share\migration\mystore](file://server/share/migration/mystore) /mu:contoso\user1:fabrikam\user1 /i:MigDocs.xml /i:MigApp.xml

However, I am confirming with experts. I think the main problem is the stated scenario - it talks about migrating two users but then only restores one user. I may just change the scenario so that both users are restored.

**Comment by frankroj** [comment]
Fixed by https://github.com/MicrosoftDocs/windows-docs-pr/pull/7597

**Pull request closed without merging**
