### PR TITLE
Corrected HVCI and virtualizacion comment

### PR DESCRIPTION
**Pull request by j0rt3g4**
Validated and corrected HVCI #2704

### CODE REVIEW

**Comment by illfated** [comment]
Sorry for troubling you with cosmetic details, but would you mind correcting the PR title like this?

Corrected HVCI **and virtualization** comment

(as I said, this is cosmetic, but better to read for English speakers)

**Comment by j0rt3g4** [comment]
I don't mind :) it’s done 😊
Get Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by Justinha** [comment]
@j0rt3g4 thanks for this correction!

**Comment by j0rt3g4** [comment]
No problem @justinha thank you for pointing it out :)

**Pull request merged**
