### PR TITLE
Update windows-analytics-get-started.md

### PR DESCRIPTION
**Pull request by zdvorak**
Added a comment about SSL Inspection

### CODE REVIEW

**Comment by lizap** [comment]
@jaimeo - Jaime, can you take a look? Thanks!

**Comment by jaimeo** [comment]
Hey Zach, can you fix three small things:

- delete extra "enabled"
- change "may" to "might" (it's a Loc thing)
- change "Microsoft's" to just "Microsoft"

With those changes it's good to go.

**Comment by jaimeo** [comment]
oops, forgot to tag: @zdvorak , see above.

**Comment by zdvorak** [comment]
Changes have been made.

**Comment by jaimeo** [comment]
Oh crud, Zach, I'm so sorry I didn't see this. Either the system didn't notify me of your update or Clutter ate it. This looks fine; please merge.

**Pull request merged**
