### PR TITLE
fix: MD006/ul-start-left

### PR DESCRIPTION
**Pull request by nschonni**
Consider starting bulleted lists at the beginning of the line

### CODE REVIEW

**Comment by illfated** [comment]
Maybe I have misunderstood the rule MD006/ul-start-left, but looking at the beginning of your changes, it looks like the intention is to remove white space before any bullet list points. Further down, at https://github.com/MicrosoftDocs/windows-itpro-docs/pull/4630/files#diff-6db9d1a344f92fbadf8af29c51da8b32, it looks like you have added extra space in front of the bullet list points. Doesn't that go against the rule you refer to? Or have I misunderstood the format?

**Comment by nschonni** [comment]
It does flag lists that aren't left aligned, but this has the side-effect of highlighting list items that aren't indented enough under things like ordered list to render correctly

**Comment by illfated** [comment]
Very well. I trust your changes are well founded and that you have verified the results. The rich text diff does not show any changes, so I presume all is well here.

**Comment by nschonni** [comment]
Most of them should show no diffs (when leading space was removed), but it will for the case where the ordered list was re-indented like in that one file you linked to

**Comment by e0i** [comment]
@AndreaBarr The PR that introduces Markdown formatting fixes is available for review. Thanks.

**Comment by e0i** [comment]
@AndreaBarr Following up for updates.

**Comment by AndreaBarr** [comment]
@nschonni please resolve the conflicts for merging.

**Comment by nschonni** [comment]
@AndreaBarr rebased and resolve the conflicts

**Pull request merged**
