### PR TITLE
Updated SetupDiag info.

### PR DESCRIPTION
**Pull request by AdamGrossTX**
https://docs.microsoft.com/en-us/windows/deployment/upgrade/setupdiag#release-notes
6/19/2019 - SetupDiag v1.5.0.0 is released with 60 rules, as a standalone tool available from the Download Center.

### CODE REVIEW

**Comment by AdamGrossTX** [comment]
Just realized that this is the What's new in 1903 article. SetupDiag 1.5.0.0 was just released in June, so this edit may not actually be necessary.

**Comment by e0i** [comment]
@greg-lindsay The PR that introduces a minor version update is available for review. Thanks.

**Comment by e0i** [comment]
@greg-lindsay Following up for updates. Thanks.

**Comment by e0i** [comment]
@AdamGrossTX We have been informed that the deployment docset is being updated and reviews should follow the update. Thank you for your contributions.

cc @greg-lindsay

**Comment by greg-lindsay** [comment]
This is out of date. 1.6 is the current version.

**Comment by illfated** [comment]
https://docs.microsoft.com/nb-no/windows/deployment/upgrade/setupdiag
Current version of SetupDiag: 1.6.0.42

Oh. Right. We need a new PR for this content.

**Pull request closed without merging**
