### PR TITLE
added info about PCR banks in use

### PR DESCRIPTION
**Pull request by VLG17**
https://github.com/MicrosoftDocs/windows-itpro-docs/issues/3012

### CODE REVIEW

**Comment by mypil** [comment]
@nenonix @JohanFreelancer9 - kindly do the copy editor review for this PR. Thanks.

**Comment by mypil** [comment]
@andreabichsel @Justinha - Can you please assist to check, approve and merge the content for this PR based on issue #3012?

Thank you.

**Comment by mypil** [comment]
@VLG17 - please apply the necessary changes as suggested by Justinha. Thanks.

**Comment by Justinha** [comment]
We typically advise against using the Registry unless necessary. Our engineering team wants to consider this before publishing. I'll reply back to the issue.

**Comment by VLG17** [comment]
i've created a new PR with all the info. I have not added initialy the part with the algorith because the issue stated that there is no way of knowing how to check what TPM PCR Bank is being used (not what algorithm it uses).

**Comment by Justinha** [comment]
@VLG17 Thanks for the update. We'll get engineering input.

**Pull request closed without merging**
