### PR TITLE
Corrected command value

### PR DESCRIPTION
**Pull request by AndreasStenhall**
Corrected command value, must be 17 and not "Enabled:Allow Supplemental Policies". Option 17 do activate "Enabled:Allow Supplemental Policies" but the syntax of the command is not correct.

### CODE REVIEW

**Comment by e0i** [comment]
@mdsakibMSFT The PR that corrects a code sample within the document is available for review. Thanks.

**Comment by e0i** [comment]
@mdsakibMSFT Following up for updates.

**Comment by e0i** [comment]
@mdsakibMSFT Following up for updates.

**Comment by AndreasStenhall** [comment]
Not sure what I'm expected to do, should I Close the pull request?

**Comment by illfated** [comment]
@AndreasStenhall : No, please just be patient. We need feedback from the document author (@mdsakibMSFT ) to verify and validate your change, so it can be merged by any MS Docs team manager.

**Comment by AndreasStenhall** [comment]
Roger that, I'll just relax :)

**Comment by e0i** [comment]
@mdsakibMSFT Following up for updates.

cc @Dansimp

**Comment by brbrahm** [comment]
Hi there. This should be changed to Set-RuleOption -FilePath <string> -Option 17

**Comment by illfated** [comment]
@AndreasStenhall : Please note the feedback from Microsoft PM **brbrahm** and adjust your PR solution accordingly.

**Comment by AndreasStenhall** [comment]
Updated my commit to include the -Option switch.

**Comment by brbrahm** [comment]
Thanks for checking in this correction, Andreas!

**Comment by brbrahm** [comment]
Update looks good. Can someone merge this?

**Comment by illfated** [comment]
@e0i : I presume you will keep in touch with the author & manager to request the merge.

**Comment by e0i** [comment]
@Dansimp @mdsakibMSFT Please merge this PR that has been approved by **brbrahm**, Microsoft PM on OS Security. Thanks.

**Comment by AndreasStenhall** [comment]
> ~@Dansimp @mdsakibMSFT Please merge this PR that has been approved by **brbrahm**, Microsoft PM on OS Security. Thanks.~
> 
> @AndreasStenhall Please change the target of the PR branch from `master` to `public`. This can be done by clicking `Edit` at the top-right corner of the PR and clicking the branch link. Thanks.

Clicking Edit at top right corner only let me change the headline of the PR. I see no way of changing branch.

**Comment by illfated** [comment]
Took me a few seconds to draw the right conclusion, but it is because you don't have the [`public`](https://github.com/MicrosoftDocs/windows-itpro-docs/tree/public) branch as part of your own repository (https://github.com/AndreasStenhall/windows-itpro-docs).

In order for you to acquire your own copy of the [`MicrosoftDocs:public`](https://github.com/MicrosoftDocs/windows-itpro-docs/tree/public) branch, you could use an external tool like Git Extensions, but maybe it can be done via web tools too. I haven't tried other web methods than removing the whole existing repository and forking it again with all the current branches, besides using Git Extensions and re-synchronizing it to my local computer, then pushing the changes to my personal repository on Github.

**Pull request merged**
