### PR TITLE
remove win 10 mobile from article

### PR DESCRIPTION
**Pull request by MaratMussabekov**
https://github.com/MicrosoftDocs/windows-itpro-docs/issues/9418
Windows 10 mobile is not supported and is not applicable for any service channel

### CODE REVIEW

**Comment by MaratMussabekov** [comment]
Dear @JohanFreelancer9,
kindly do the copy editor review for this PR.

Dear @nam31, for your information

Thank you

**Review by illfated — COMMENTED** [review]
The removal looks clean to me.

**Comment by illfated** [comment]
(note to myself: This article document can do with some codestyle improvements.)

**Comment by illfated** [comment]
Rich Diff view, for easier layout review:
- https://github.com/MicrosoftDocs/windows-itpro-docs/pull/9454/files?short_path=6e24e9d

**Review by JohanFreelancer9 — APPROVED** [review]

**Comment by nam31** [comment]
@jaimeo, PR has been copyedited and is ready for final review, could you please check and merge? Thanks!

**Pull request merged**
