### PR TITLE
Link to dg-readiness-tool.md instead of old version

### LINKED ISSUE #5690: There is a v3.7.x of the 'DG & DC Readiness tool'
'Windows Defender Device Guard and Windows Defender Credential Guard hardware readiness tool' v3.7 is found here:

https://docs.microsoft.com/en-us/windows/security/identity-protection/credential-guard/dg_readiness_tool

Edit: There is now a v3.7.1 at: https://docs.microsoft.com/en-us/windows/security/identity-protection/credential-guard/dg-readiness-tool (note "_" --> "-")

At the top of https://docs.microsoft.com/en-us/windows/security/identity-protection/credential-guard/credential-guard-manage there is still a link to v3.6 as a "convenient" but old download. 

> Windows Defender Credential Guard can be enabled either by using Group Policy, the registry, or the Hypervisor-Protected Code Integrity and Windows Defender Credential Guard >>>hardware readiness tool<<<. 

Microsoft should update that download.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 41c2cb44-269d-3334-019a-726eb5432f1c
* Version Independent ID: 251024cc-b818-18c6-a112-4ac0276cb4b1
* Content: [Manage Windows Defender Credential Guard (Windows 10) - Microsoft 365 Security](https://docs.microsoft.com/en-us/windows/security/identity-protection/credential-guard/credential-guard-manage#disable-windows-defender-credential-guard)
* Content Source: [windows/security/identity-protection/credential-guard/credential-guard-manage.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/public/windows/security/identity-protection/credential-guard/credential-guard-manage.md)
* Product: **w10**
* Technology: **windows**
* GitHub Login: @DulceMontemayor
* Microsoft Alias: **dansimp**

### PR DESCRIPTION
**Pull request by HenkPoley**
Removes link to https://www.microsoft.com/download/details.aspx?id=53337

Adds link to https://github.com/MicrosoftDocs/windows-itpro-docs/blob/public/windows/security/identity-protection/credential-guard/dg-readiness-tool.md

This should close #5690

### CODE REVIEW

**Comment by beerisgood** [comment]
I don't think this is a good solution.
Microsoft just need to update the old tool version.

**Comment by HenkPoley** [comment]
Well, they won't. and they haven't.

**Comment by illfated** [comment]
@beerisgood : I think both of you have got fair points in your arguments. The fact that the ideal solution would be to convert the script to a downloadable package the same way the old version is available in a single package file, would be the best solution for all, I think. Then again, I also get the impression that it would take more time than the target audience for the DG Readiness Tool is willing to wait for someone with the authority to make the necessary changes to make sure that the updated version will be converted to a single downloadable package. Therefore, I find it just as useful to make sure that those who are looking for the most up-to-date version should not need to go out of their way to search for the new version or continue to use the old version.

**Comment by e0i** [comment]
@HenkPoley Thank you for this contribution.

@Kateyanne This PR can be merged as it fixes a broken link at the surface level with a hash link inside the same article.

Thank you.

**Pull request merged**
