### PR TITLE
Correction in Note Section

### PR DESCRIPTION
**Pull request by joinimran**
This is not available in 20H2 but these are available in Windows Insider Preview build 21313.

Problem: https://github.com/MicrosoftDocs/windows-itpro-docs/issues/9147

### CODE REVIEW

**Comment by joinimran** [comment]
@JohanFreelancer9 - kindly do the copy editor review for this PR. Thanks.

**Review by illfated — APPROVED** [review]
Looks good & correct to me, based on the discussion in https://github.com/MicrosoftDocs/windows-itpro-docs/issues/9147 .

**Comment by nam31** [comment]
@DaniHalfin PR has been copyedited and is ready for final review, could you please check and merge? Thanks!

**Comment by denisebmsft** [comment]
Dani Halfin has moved to a different team. Assigned to Sinead for her review.

**Comment by illfated** [comment]
Thanks for the info update, useful to know.

**Review by JohanFreelancer9 — APPROVED** [review]

**Comment by siosulli** [comment]
@illfated @nam31
these changes were announced as part of this preview build: 
https://blogs.windows.com/windows-insider/2020/03/05/announcing-windows-10-insider-preview-build-19577/
 
So that is why that preview build is referenced in this article.  

Based on this, I think this PR should be closed without merging.

Thanks
Sinead

**Comment by illfated** [comment]
OK, I see. The change in this PR does not apply to the target page. Fair point.

**Comment by siosulli** [comment]
Closing this PR based on the comments above. thanks!

**Comment by joinimran** [comment]
@siosulli - I have already gone through the blog post where it says that it was released in build 19577 but in actual, it's still not available in V1909, and 20H2. Based on this finding I have created the PR to reflect the correct information.

**Comment by illfated** [comment]
OK, so even if the announcement https://blogs.windows.com/windows-insider/2020/03/05/announcing-windows-10-insider-preview-build-19577/ claims that the settings are supposed to be available from build 19577, but it did not make it out until the Insider Preview build 21313.

@siosulli : Based on that counterpoint, I suggest that we reopen this PR and check if there is any other documentation available to counter the information in this PR before closing it instead of merging it.

**Pull request closed without merging**
