### PR TITLE
Update bitlocker-how-to-enable-network-unlock.md

### PR DESCRIPTION
**Pull request by Lexy2**
- Corrected certificate store name from FVENKP to FVE_NKP
- Added the requirement to reboot the clients after applying the policy
- Added the requirement for the clients to have a TPM protector
- Removed duplicate steps of adding a TPM protector (require TPM+PIN vs allow TPM+PIN)
- Fixed linking within the document

### CODE REVIEW

**Comment by illfated** [comment]
Maybe this is a bit redundant, but I will take the chance of linking this PR back to the issue by link: https://github.com/MicrosoftDocs/windows-itpro-docs/issues/2714

(My preferred way of closing issues on Github (given that it is going to solve the issue) is to link the issue by adding "`Closes #2714` " to the commit (on a separate line of the commit text) before pushing the commit back to my `origin` before I create the PR.)

**Comment by lizap** [comment]
@Justinha - can you take a look at the proposed changes to this Bitlocker article? Thanks!

**Comment by Justinha** [comment]
@Lexy2 Thanks for the corrections!

**Comment by illfated** [comment]
BTW, issue ticket #2714 can be closed now.

**Comment by Lexy2** [comment]
Thanks, guys.
@illfated , duly noted, thank you.

**Pull request merged**
