### PR TITLE
Update upgrade-mbam2.5-sp1.md

### PR DESCRIPTION
**Pull request by TobyTu**

### CODE REVIEW

**Comment by TobyTu** [comment]
Hi team, i make a update for this article, could you have a look and help merge, as i cannot preview the article, pls help confirm the video link can work. additionally, can you help update the TOC to reflect this article?  mdop/mbam-v25/upgrade-mbam2.5-sp1.md

**Comment by illfated** [comment]
Rich Text Diff view:
https://github.com/MicrosoftDocs/windows-itpro-docs/pull/4802/files?short_path=a0467ea#diff-a0467eaf6dabe4a677a03585c9696dfb

**Comment by TobyTu** [comment]
#hold-off

**Comment by TobyTu** [comment]
@illfated pls hold on to merge this pull request until i get the correct link from the requester.

**Comment by illfated** [comment]
😄 Thank you for thinking so highly of me, but I am neither employed nor a Microsoft Docs team member, I do not have access to change anything outside my own comments and my own pull requests. Your comment will be read later on by the MS Docs team members, so it is still OK. 👍

**Comment by e0i** [comment]
@Dansimp Would you be able to review this new article created by an internal MS contributor as the time permits? Thanks.

**Comment by TobyTu** [comment]
@e0i @Dansimp We have fixed the video problem, and i have also create a pull request https://github.com/MicrosoftDocs/windows-itpro-docs/pull/4833 to update the toc to reflect this file, pls have a look and help merge these two pull requests. Thx!

**Comment by TobyTu** [comment]
@Dansimp  would you able to take a look at this and help merge these two pull requests?

**Pull request merged**
