### PR TITLE
added windows 11

### PR DESCRIPTION
**Pull request by RAJU2529**
after reading this article, i confirmed windows 11 is supported

### CODE REVIEW

**Review by JohanFreelancer9 — APPROVED** [review]

**Comment by RAJU2529** [comment]
@JohanFreelancer9  Thanks for your verification for previous created PR
 on 27th December 2022, i created around 30 PR  under windows-it pro category, so verify and accept it.

**Comment by JohanFreelancer9** [comment]
> @JohanFreelancer9 Thanks for your verification for previous created PR on 27th December 2022, i created around 30 PR under windows-it pro category, so verify and accept it.

@RAJU2529, it is my pleasure and will do these as well. Please have a look at the previous batch - there were three that needed some changes. Could you please commit those changes? Many thanks.

**Comment by RAJU2529** [comment]
@JohanFreelancer9 could you please resend changes of previous batch, because I have deleted all the  notifications

**Comment by aczechowski** [comment]
@RAJU2529, first of all, **thank you** for your contributions to our content! 🎉 You've been busy in December, and I wanted to share some feedback on the 130+ PRs you recently submitted. 😄 You don't need to make any changes to these PRs now, this feedback is just for future use.

CC @tiburd @yogkumgit 

### Changes planned for "applies to" in Windows IT Pro docs

- FYI our team plans on revising how we do "applies to" in the Windows IT Pro for client content. We're still working on the plan, but want to make sure that it's implemented consistently across all of this content.
- If you're planning to contribute more of these types of edits, please wait until we switch over to the new format.
- I'm going through all of these PRs and will accept as many as I can now. I want to encourage edits and accept them as much as possible! Even if a specific change may not continue to be published in the near future because we change the format, your commit/contribution credit will persist!

### Use content authoring tools locally for major edits

As a frequent contributor and/or when making more significant changes, I recommend using the local process with Git and VSCode: [Install content authoring tools](https://learn.microsoft.com/contribute/get-started-setup-tools). There are some instances where the GitHub web-based "pencil edit" is quicker and faster (I use it myself often for smaller edits), but in this specific instance I think it might have been easier overall to make the edits in a single commit or in multiple commits in the same branch. It would then be a single pull request, which makes it much easier for folks like Johan and me to review a single PR with 130 files instead of 130 PRs each with a single file. 😄 

### Making multiple commits into the same branch/PR 

It *is* possible to use the GitHub browser-based experience to edit multiple files (make multiple commits) into the same branch, and thus the same PR. Here's how to do that:

1. As you would normally, edit the first file and create a pull request.

    In this example, the first file I edited is `windows/client-management/administrative-tools-in-windows-10.md` in PR https://github.com/MicrosoftDocs/windows-itpro-docs/pull/11254.

2. From the pull request, select your branch at the top:

    image

    This action opens your branch in your fork of the repo, for example from this graphic: `https://github.com/A-A-Ron42/windows-itpro-docs/tree/patch-1` - Note it's under user `A-A-Ron42` (my secondary account 😉 ) and *not* `MicrosoftDocs` 

3. Browse through the GitHub source for the next file you want to edit.

    1. For example, I'm next editing `windows/client-management/quick-assist.md`
    2. So I browse to https://github.com/A-A-Ron42/windows-itpro-docs/blob/patch-1/windows/client-management/quick-assist.md

    image

5. From this next file in my branch of my fork, select the pencil icon to edit the file.

6. In the GitHub editor, I'll see that I'm editing the file in `patch-1` (the same branch as the first commit in the original PR)

    image

7. I make the edit, and then at the bottom when I commit the changes, use the default option to **Commit directly to the `patch-1` branch**

    image

    This action commits this edit to the second file into the *same branch* (for example, `patch-1`), and GitHub automatically adds that commit to the existing pull request for that branch. 😮 

    If you look at the example PR (https://github.com/MicrosoftDocs/windows-itpro-docs/pull/11254), you'll see [two commits](https://github.com/MicrosoftDocs/windows-itpro-docs/pull/11254/commits) and [two files changed](https://github.com/MicrosoftDocs/windows-itpro-docs/pull/11254/files).

Repeat this process, and you can add multiple files/commits to a single pull request, all using the GitHub web editor!

Again, thanks for your contributions, and no change needed right now, but please review and consider this feedback for future contributions. Let me know if you have any questions! As I mentioned, I definitely want to help support contributors as much as possible.

--- 
Aaron Czechowski
Content Experience Manager
Windows client for IT Pros (aka.ms/wincomdocs)

**Review by aczechowski — APPROVED** [review]

**Comment by aczechowski** [comment]
Thanks @RAJU2529 for the comment - I just did a private PR to address those five articles. FYI, the first policy was renamed: **Interactive logon: Require Windows Hello for Business or smart card**. The other four policies are for SMBv1, so I removed them and added a note to the primary policy articles.

**Pull request merged**
