### PR TITLE
Update some names, sample commands and links

### PR DESCRIPTION
**Pull request by SergioCalderonR**
I have changed Windows Defender Device Guard to Device Guard in the local GPO, updated the sample command for New-CIPolicy and some broken links to the old TechNet to the new Docs.

### CODE REVIEW

**Comment by SergioCalderonR** [comment]
Done. I have removed the en-us and updated some other links.

**Comment by Justinha** [comment]
@SergioCalderonR Thanks for these corrections!

**Comment by Justinha** [comment]
I see that change in the "Files changed" tab here.

**Comment by SergioCalderonR** [comment]
Yes, I see them too, but cannot see the changes on the actual [public doc](https://docs.microsoft.com/en-us/windows/security/threat-protection/device-guard/steps-to-deploy-windows-defender-application-control). Do we have to wait for a merge?

**Comment by Justinha** [comment]
Yes, I should have added we publish twice daily ~ 10:30 and 3:30 PST. I see the changes are live now.

**Comment by SergioCalderonR** [comment]
@Justinha, sorry for bother you, but I still cannot see the GPO and cmdlets changes I sent. =)

**Comment by Justinha** [comment]
@SergioCalderonR Thanks for pointing it out. I don't see you listed as contributor yet either so something is not right and I'm following up.

**Pull request merged**
