### PR TITLE
Surface Hub: note for creating accounts using EAC

### LINKED ISSUE #3295: Ambiguous Section - "Create a device account using the Exchange Admin Center"
The "Create a device account using the Exchange Admin Center" section of this document implies that the Office 365 Exchange Online Admin Center can be used to add the account, even though the screenshot is of the Exchange 2103-or-higher EAC on-premises.

### PR DESCRIPTION
**Pull request by illfated**
**Description:**

According to user feedback, using the Exchange Admin Center to create Surface Hub device user accounts requires on-premises Active Directory to synchronize from, for that method to work.

**Change proposed:**

Add a note saying
> **This method will only work if you are syncing from an on-premises Active Directory.**

directly below the header title of the second section.

***
Closes #3295

### CODE REVIEW

**Comment by mypil** [comment]
@DaniHalfin @lizap @jaimeo @Justinha @mjcaparas @greg-lindsay - Can anyone of you please assist to check, approve and merge the content of this PR based on issue #3295?

Thank you.

**Comment by nenonix** [comment]
@illfated A question about the MD for Tips, Notes and Warnings: does it make a difference  if there is a space after the **>**. In other words: >does this render > differently to this?

**Comment by illfated** [comment]
> @illfated A question about the MD for Tips, Notes and Warnings: does it make a difference if there is a space after the **>**. In other words: >does this render > differently to this?

Good question. I have not seen any difference on the docs.microsoft.com pages whether the space is there or not, but I assume it can be worth adding the space, just to be on the safe side.

**Comment by mypil** [comment]
@DaniHalfin @lizap @jaimeo @Justinha @mjcaparas @greg-lindsay - We would like to follow up on this. Can anyone of you please assist to check, approve and merge the content of this PR based on issue #3295?

Thank you.

**Pull request merged**
