### PR TITLE
Updated required windows version

### PR DESCRIPTION
**Pull request by joinimran**
Network protection works on Windows Pro and Enterprise. I have upgraded this information. Problem Link: https://github.com/MicrosoftDocs/windows-itpro-docs/issues/2776

### CODE REVIEW

**Comment by mypil** [comment]
@TokyoScarab - kindly do the copy editor review for this PR. Thanks.

**Comment by TokyoScarab** [comment]
Looks good

**Comment by mypil** [comment]
@andreabichsel - can you please assist to check, approve and merge the content for this PR based on issue #2776?

Thank you.

**Comment by mypil** [comment]
@andreabichsel - I would like to follow up on this. Can you please assist to check, approve and merge the content for this PR based on issue #2776?

Thank you.

**Comment by mypil** [comment]
@andreabichsel - I would like to follow up on this. Can you please assist to check, approve and merge the content for this PR based on issue #2776?

Thank you.

**Comment by mypil** [comment]
@DaniHalfin - would you be able to merge the content for this PR based on issue #2776? Thank you.

**Comment by mypil** [comment]
@andreabichsel - I would like to follow up on this. Can you please assist to check, approve and merge the content for this PR based on issue #2776?
Thank you.
cc: @kenwith

**Comment by mypil** [comment]
@jdeckerms - would you be able to help check and merge the content of this PR? Thanks.

**Comment by mypil** [comment]
@kenwith - would you be able to merge the content for this PR based on issue #2776?

Thanks.

**Comment by kenwith** [comment]
This looks correct but I need to find someone that can sign off on this one to confirm.

**Comment by Justinha** [comment]
I'm checking on this.

**Comment by Justinha** [comment]
@joinimran sorry for delay! Thanks for the correction!

**Pull request merged**
