### PR TITLE
Update surface-hub-2s-techspecs.md

### PR DESCRIPTION
**Pull request by cjhusky**
Updating RAM and SSD details

### CODE REVIEW

**Comment by illfated** [comment]
Do you have any references, links or quotes for this information update?
(I don't know the topic details, it just looks like a resource reference would be useful here.)

**Comment by cjhusky** [comment]
I run the Hub SW engineering team...thought THIS was the reference site.

Thanks,
Chris
________________________________

**Comment by jvsam** [comment]
Content: https://docs.microsoft.com/en-us/surface-hub/surface-hub-2s-techspecs
Content Source: https://github.com/MicrosoftDocs/windows-itpro-docs/blob/master/devices/surface-hub/surface-hub-2s-techspecs.md

@illfated FYI

**Comment by illfated** [comment]
Sorry, I did not realize that the PR author is one of the Microsoft internals.
At first glance, the user page looks just like any new public github user.

**Comment by e0i** [comment]
@robmazz

The PR provides additional details for RAM and SSD to Surface Hub 2S tech specs page provided by an internal MS contributor is available for review. Thanks.

**Comment by e0i** [comment]
@robmazz Following up for updates.

**Comment by illfated** [comment]
@cjhusky : May I suggest adding a short biography, location information and organization membership to your Github profile? Doing so would help us other users recognize as a Microsoft internal as well as trusting your information to be factual.

**Comment by e0i** [comment]
@robmazz Following up for updates.

cc @Dansimp

**Comment by e0i** [comment]
@cjhusky Please change the PR merge target from `master` to `public`. Thanks.

**Comment by e0i** [comment]
@cjhusky Feel free to re-open this PR upon changing its target from `master` to `public`. Thanks.

**Pull request closed without merging**
