### PR TITLE
fix typos dg_readiness_tool.md

### PR DESCRIPTION
**Pull request by schneiderl**

### CODE REVIEW

**Comment by e0i** [comment]
@Dansimp The PR that has been approved by the document author can be merged. Thanks.

**Comment by e0i** [comment]
@Dansimp The PR that has been approved by the document author can be merged. Thanks.

**Comment by e0i** [comment]
Please feel free to re-open this PR with resolved merge conflicts to continue with the review. Thank you.

**Comment by illfated** [comment]
I will incorporate these typo corrections in my PR **[WDDG & WDCG HW readiness tool: typo & Arch Locale](https://github.com/MicrosoftDocs/windows-itpro-docs/pull/6575) #6575**
(Oddly enough, I have not noticed that typo before or received feedback in my PR about it.)

**Pull request closed without merging**
