### PR TITLE
added  october 2020 admx templates link

### PR DESCRIPTION
**Pull request by RAJU2529**
this is my own PR , i read this article, i found October 2020 admx templates link not added , so i added a new link to this article

### CODE REVIEW

**Comment by e0i** [comment]
@JohanFreelancer9 Copy editing is needed for this PR. Thanks.

**Review by JohanFreelancer9 — APPROVED** [review]

**Review by illfated — APPROVED** [review]

**Comment by e0i** [comment]
@RAJU2529 Can you kindly resolve the merge conflicts in order to proceed with the review? Thank you.

**Comment by illfated** [comment]
Looks like the main part of this PR is already added (using **20H2** as ADMX version number instead of **2009**).

Never mind. I will create a PR to @RAJU2529's branch patch-112 to update it. It may look more like a whitespace cleanup after, but improvement is improvement. 😉

**Comment by RAJU2529** [comment]
@illfated . ok carry on.

**Comment by RAJU2529** [comment]
@e0i . I will try after 4.30PM today using pc

**Comment by illfated** [comment]
Thank you for merging my PR. I hoped it would be enough, but it seems I added too much whitespace clean-up to even out the difference between your branch and the MicrosoftDocs/windows-itpro-docs public branch. Unless you manage to even out the difference via editing, there is the option to start a new PR based on the existing content in the public branch. Good luck with the editing. 👍🏻

**Comment by e0i** [comment]
Please re-open to resolve the merge conflicts. Thanks.

**Comment by illfated** [comment]
Yes, it is better to start a new PR to have the new changes unhindered by old changes.

**Pull request closed without merging**
