### PR TITLE
Added list of countries where AP is supported

### PR DESCRIPTION
**Pull request by brentkendall**
Added last question/answer to General section to clarify a common question:  does AP work in all regions?

### CODE REVIEW

**Comment by e0i** [comment]
@Justinha @DaniHalfin Could you review and merge this PR opened by a MS contributor? Thank you.

**Comment by e0i** [comment]
@brentkendall Would you be able to follow up with the requested changes for PR's approval? Thank you.

**Comment by Dansimp** [comment]
@greg-lindsay can you please review the changes here?

**Comment by greg-lindsay** [comment]
I'm adding this manually since there is a conflict in the file

**Pull request closed without merging**
