### PR TITLE
added reference to 1909

### PR DESCRIPTION
**Pull request by MaratMussabekov**
#5899

### CODE REVIEW

**Comment by MaratMussabekov** [comment]
@JohanFreelancer9

**Comment by illfated** [comment]
By the way, is this PR related to issue ticket #5930 (**1909 missing**)? That ticket in itself is more or less related to ticket #5899 .

**Comment by medgarmedgar** [comment]
Note: there was never a 1909 Enterprise (or 1909 non-Enterprise) endpoints article published.  It was a decision made based on the nature of the 1909 release (primarily bug fixes).

**Comment by medgarmedgar** [comment]
Couple of notes:
1. Since we didn't explicitly collect the "raw traffic" endpoints for 1909 I can't say that there is a 100% match between 1903 and 1909.

2. There is also a 1903 "non-enterprise" article with a similar situation of there being no definitive 1909 "raw traffic" results.

Overall, since the 1909 release was mostly bug fixes, but it did include some features as well, the 1903 results will generally map well if not near 100% to 1909.  

Conclusion: 1903 endpoints are a great guideline for what to expect from 1909, but may not be 100% accurate.

Finally, the next release of Windows 10 will have a separate article for both Enterprise and non-Enterprise endpoints.

**Comment by Dansimp** [comment]
rejecting PR per medgarmedgar's comments

**Pull request closed without merging**
