### PR TITLE
Update wufb-compliancedeadlines.md: pencil edits

### PR DESCRIPTION
**Pull request by illfated**
**Description:**

Based on the newly merged PR #6165, it seems useful to make a couple of minor edits to improve readability slightly and to avoid unintended capitalization other than brand names and start of a sentence.

**Changes proposed:**

- Remove "For" where the lines already contain sentence starting caps and apply consistency to copying section headings to the link text.
- Whitespace adjustments:
    - "Trim Trailing Space" (remove blanks at end-of-line)
    - Remove 10 redundant blank lines
    - Add MD indent marker compatibility spacing in the Note blob
    - Add MD indent marker compatibility spacing to "Applies to:"

Use either the Rich diff view or the Hide whitespace changes feature.

**Ticket closure or reference:**

Ref. PR #6165

### CODE REVIEW

**Comment by illfated** [comment]
(Ref. my old broken & closed PR: #6169 )

**Comment by illfated** [comment]
#sign-off

**Comment by jaimeo** [comment]
Well I'm trying to leave the review for this (it's fine--go for it), but I can't get the review buttons to appear for some reason.

**Comment by illfated** [comment]
Thank you for your feedback. I think I remember seeing that happen to me once as well. Could be a temporary browser issue, but I am not 100% certain.

**Comment by illfated** [comment]
Could we possibly have a new look at this content, in case our browsers are more updated or compliant now?

**Comment by illfated** [comment]
#sign-off

**Comment by illfated** [comment]
#sign-off

**Comment by illfated** [comment]
@e0i : Any chance you could find someone else to perform the final review? Jaime Ondrusek seems to have difficulties adding his review to this PR.

**Comment by jaimeo** [comment]
Sorry about that! I wasn't aware this was still hanging around.

**Comment by illfated** [comment]
Fair enough. Thank you for the merge. I did not want to nag about it (at least not directly), knowing that you and your teammates are busy enough as it is. Keep up the good work. Stay safe and well. 😉

**Pull request merged**
