### PR TITLE
Updating Intune screenshots

### PR DESCRIPTION
**Pull request by MaxSteinMS**
Uploaded new VPN policy settings that are available today within the Microsoft Endpoint Manager admin center.
(Current screenshots were from the Intune Silverlight admin console).

Could we upload and update the following?

vpn-connection-intune:
vpn-connection-intune

vpn-custom-xml-intune:
vpn-custom-xml-intune

### CODE REVIEW

**Comment by MaxSteinMS** [comment]
Just a quick note that Issue: https://github.com/MicrosoftDocs/windows-itpro-docs/issues/8637 was closed as a duplicate of this pull request.

**Comment by illfated** [comment]
Good choice. Even though #8637 is an **issue ticket** (and this page being a Pull Request), the ticket is commonly kept open only as long as the ticket was created by a completely different user. In cases where both the ticket and the directly related PR is created by the same person, closing the ticket is recommended.

**Comment by illfated** [comment]
Note about the images: if your intention is to add images to this PR content, the image(s) need to be added in the related ./images/ directory in your PR branch. Feel free to ask, if you don't know the necessary details of that procedure.

**Comment by MaxSteinMS** [comment]
Hi @illfated, thanks for the feedback. New images uploaded to the related image directory and ready to go.
If there's anything is missing, please let me know! 😄

**Comment by illfated** [comment]
Well done, good job. Thank goodness for the complete updated view showing the included images as part of the page when viewed from your PR branch in your repository:
- https://github.com/MaxSteinMS/windows-itpro-docs/blob/patch-3/windows/security/identity-protection/vpn/vpn-connection-type.md

(otherwise, I would have worried a lot why the PR rich diff preview will not show the new images, but that may or may not have something to do with the order the files were added)

**Review by illfated — APPROVED** [review]
Looks good to me. I think we can have a final review and merge now.

**Review by illfated — COMMENTED** [review]
**Normal source view:** https://github.com/MicrosoftDocs/windows-itpro-docs/pull/8638/files
**Rich diff, image 1:** https://github.com/MicrosoftDocs/windows-itpro-docs/pull/8638/files?short_path=3127e1c#diff-3127e1c1e8dec6e86dc5965a7db0e342d3d6f6a2c491f928a89a224425e20e30 (shows image before & after)
**Rich diff, image 2:** https://github.com/MicrosoftDocs/windows-itpro-docs/pull/8638/files?short_path=a2b9594#diff-a2b959478831ddb6ce02345143406b36fb037066e3e0bc8c6324b190372c1b6e

**Pull request merged**
