### PR TITLE
updated min os version requirements and warning about eas policies

### PR DESCRIPTION
**Pull request by tanviramsft**

### CODE REVIEW

**Comment by e0i** [comment]
@dulcemontemayor Would you be able to review this PR contributed by the community? Thanks.

**Comment by tanviramsft** [comment]
@e0i I'm a verified Microsoft employee who owns the feature for this doc page.

**Comment by e0i** [comment]
@DulceMontemayor Would you be able to merge this PR created by a MS contributor who owns the feature in this page? Thanks.

**Comment by e0i** [comment]
@DulceMontemayor Any updates?

**Comment by greg-lindsay** [comment]
I've added this manually

**Pull request closed without merging**
