### PR TITLE
Fix: Corrected template name in CA

### PR DESCRIPTION
**Pull request by SteveBurkettNZ**
As per SquirrelAssassin's comment, the name of the template is incorrect in this section, it's correct in the Creating an Enrollment Agent certificate for Group Managed Service Accounts section above it.

### CODE REVIEW

**Comment by illfated** [comment]
Ref. issue ticket #3792
- https://github.com/MicrosoftDocs/windows-itpro-docs/blob/master/windows/security/identity-protection/hello-for-business/hello-hybrid-cert-whfb-settings-pki.md
- https://docs.microsoft.com/en-us/windows/security/identity-protection/hello-for-business/hello-hybrid-cert-whfb-settings-pki

**Comment by e0i** [comment]
@mapalko Please review this community contributed PR that addresses issue #3792 as the time permits. Thanks.

**Comment by illfated** [comment]
Rich text diff: https://github.com/MicrosoftDocs/windows-itpro-docs/pull/4588/files?short_path=226bfeb#diff-226bfeb1bd9d43422f555e11649463c0
(makes the small change more obvious than the standard diff view)

**Comment by e0i** [comment]
@mapalko Following up for updates. Thanks.

**Comment by e0i** [comment]
@AndreaBarr The PR that has been approved by the document author can be merged. Thanks.

**Comment by e0i** [comment]
@AndreaBarr The PR is ready to be merged. Thanks.

**Pull request merged**
