### PR TITLE
Updated guidance for deploying multi-format signed policies with the …

### PR DESCRIPTION
**Pull request by jgeurten**
…EFI instructions

I am a member of the WDAC application control feature team at Microsoft.

### CODE REVIEW

**Comment by jgeurten** [comment]
Please add @jsuther1974, @kimklein/v-kikl as a required reviewers to the PR.

**Review by illfated — APPROVED** [review]
Rich Diff view:
- https://github.com/MicrosoftDocs/windows-itpro-docs/pull/9495/files?short_path=ad38e9b

Looks good to me.

**Review by JohanFreelancer9 — APPROVED** [review]

**Review by jsuther1974 — CHANGES_REQUESTED** [review]
The deployment instructions are redundant with other topics that explicitly describe these steps. We should remove all of the deployment steps here and instead direct the reader to the Deployment Guide topic.

**Comment by jgeurten** [comment]
Abandoning the PR in favor of #9543 which incorporates these fixes in addition to some others.

**Pull request closed without merging**
