### PR TITLE
changed 1121 and 1122 to block and audit modes

### PR DESCRIPTION
**Pull request by Malind19**
Confirmed with following article. https://www.ghacks.net/2017/10/23/configure-attack-surface-reduction-in-windows-10/

### CODE REVIEW

**Comment by illfated** [comment]
Ref. issue ticket #3228

**Comment by mypil** [comment]
@andreabichsel - Can you please assist to check, approve and merge the content for this PR based on issue #3228?

Thank you.

**Comment by mypil** [comment]
@andreabichsel - I would like to follow up on this. Can you please assist to check, approve and merge the content for this PR based on issue #3228?

Thank you.

**Comment by mypil** [comment]
@AndreaBarr - would you be able to merge the content of this PR? Thank you.

**Pull request merged**
