### PR TITLE
Changes to note

### PR DESCRIPTION
**Pull request by JasonJiachengZhao**
Made changes to "Take note" section to correct some information.

Removed redundant Footnote section.

### CODE REVIEW

**Comment by jdeckerms** [comment]
@JasonJiachengZhao Why did you remove the footnotes?

**Comment by JasonJiachengZhao** [comment]
I hope this email finds you.

I attached the thread for your reference. Basically, we removed the footnote because we thought they were the result of a bad copy-paste. The schema is introduced in 1809, and we are confused why something related to 1607, 1703, 1709 and 1803 would be there.

We changed “must” to “should”, because Pranav, who implemented this, said the inclusion is recommended, but not required. In other words, the policy will not fail if you don’t include local admin. Hence the changes.

We probably have a misunderstanding of what the footnote is about. Would appreciate it if you could explain.

Thanks,
Jason

**Comment by jdeckerms** [comment]
@JasonJiachengZhao The root CSP doc and the Policy CSP doc both contain tables that indicate which versions and editions a group of settings applies to. Each table contains superscript indicators, and the footnotes are the key to the superscript. I put them back in the topic (but immediately following the table since that's where they belong).

Your pull request can't be merged until you sign the contributor license agreement, thanks!

**Comment by JasonJiachengZhao** [comment]
@jdeckerms Thanks for the explanation. We didn't know that the superscript exists. I signed the contributor license agreement. Would wait for it get get merged then!

Thanks,
Jason

**Pull request merged**
