### PR TITLE
chore: Renormalize line endings

### PR DESCRIPTION
**Pull request by nschonni**
Ran `git add --renormalize .`

### CODE REVIEW

**Comment by e0i** [comment]
@DulceMontemayor @AndreaBarr The PR that introduces whitespace fixes by normalizing line endings is available for review. Thanks.

**Comment by AndreaBarr** [comment]
@DulceMontemayor please review for merging

**Comment by e0i** [comment]
> @DulceMontemayor could you please review this for merging?

Following up.

**Comment by e0i** [comment]
@AndreaBarr The PR that has been approved by document author is ready to be merged. Thanks.

**Pull request merged**
