### PR TITLE
Update MVI Program Criteria Test Labs

### PR DESCRIPTION
**Pull request by adamoboe**
This change adds a list of approved test labs to use to qualify for MVI membership

### CODE REVIEW

**Comment by adamoboe** [comment]
Please confirm I have added this info correctly. I am the MVI Program owner for Microsoft. adamsh@microsoft.com

**Comment by illfated** [comment]
@e0i : Will you be assigning yourself to follow up on this PR, or will someone else be assigned?
From the doc:
```
author: levinec
manager: dansimp
```

**Comment by e0i** [comment]
@adamoboe Please follow up with the revision suggestions provided by the document author, *levinec*. We would like to proceed with this PR. Thanks.

**Comment by illfated** [comment]
@adamoboe : if you would like to have line breaks (CR/LF or NewLine) in your MarkDown table text, you need to use HTML breaks ( `</br>` ) at the end of the lines in need of a definite line break. This is specific to MarkDown tables, because ordinary Line Feed / NewLine characters will be ignored inside MarkDown table text.

**Comment by e0i** [comment]
@adamoboe Any updates with the content revision suggestions provided by document author, **levinec**? We would like to proceed with this PR. Thanks.

**Comment by e0i** [comment]
Closing as revisions suggested by the document author haven't been implemented. Feel free to re-open this PR for revisions to continue with the review process.

Thanks.

**Comment by levinec** [comment]
I made some revisions on my own, see the updated doc: https://docs.microsoft.com/windows/security/threat-protection/intelligence/virus-initiative-criteria

**Pull request closed without merging**
