### PR TITLE
WU Error Codes: Block codes from translation

### PR DESCRIPTION
**Pull request by illfated**
**Description:**

This is a "best effort" attempt at keeping code names from being translated by automatic translation/machine translation.

The main change here is to add a MarkDown back tick (code tag) before and after each code name reference in the tables, to block translation.

The side effect of seeing a massive text change appears because of the text being shifted at least 2 spaces sideways for the entire Message column, some times more due to code names also appearing in the Description text. I have also taken the liberty to add spacing to clean up the table layout, to improve readability for future edits. This also affects the appearance of massive change.

Browsing the PR content in Rich Text Diff view will be most useful.

A couple of minor typos are also corrected (cancelled -> canceled) (according to Webster).

**issue ticket closure or reference:**

This content should in theory close issue ticket #4933, but it remains to be seen if blocking the code names from being translated will be as effective as we are hoping for. Hence, I will only reference issue ticket #4933 and not apply automatic git closure.

Ref. **Перевод констант** #4933

### CODE REVIEW

**Comment by illfated** [comment]
I just noticed that Github might have trouble rendering the Rich Text Diff view, so that option could be troublesome. My apologies for trusting that feature to always be available.
> **Oh My**
> Sorry, we’re unable to render a diff of this document.

**Comment by illfated** [comment]
Oh well. If you want to see the Rich Text view, there is always the full file view, showing the Github page version with my changes applied:
- PR commit: https://github.com/MicrosoftDocs/windows-itpro-docs/blob/f64c3f5/windows/deployment/update/windows-update-error-reference.md
- my repo: https://github.com/illfated/windows-itpro-docs/blob/keep_code_as_code/windows/deployment/update/windows-update-error-reference.md

**Comment by jvsam** [comment]
Thanks for creating this PR @illfated. I hope you're feeling better now! :-)

**Comment by jvsam** [comment]
Hi @greg-lindsay, if you have time, can you please check this PR and approve if you see no issues? @illfated described what this PR will resolve, hopefully it's acceptable for you. Thank you.

**Comment by jvsam** [comment]
Hi @greg-lindsay, just following up. If you have time, can you please review this PR? Your help is appreciated. Thank you.

**Comment by jvsam** [comment]
Hi again @greg-lindsay, hope all is well. Kindly review the proposed changes via this PR and merge if there are no issues. Thank you.

CC: @Dansimp

**Comment by illfated** [comment]
Looks like there is still time for me to clean up a couple of cosmetic details in a couple of error code columns.

**Comment by illfated** [comment]
Github is still unable to render a Rich Text Diff view of the file, so the PR file will have to make do:
https://github.com/MicrosoftDocs/windows-itpro-docs/blob/dee59b5/windows/deployment/update/windows-update-error-reference.md
Basically, the major change is to have back ticks added around the keywords in column 2.
Some of the cosmetic improvements are mostly only useful for future editing.

**Comment by jvsam** [comment]
Thank you @illfated for the explanation. That makes it easier for everyone to easily understand what this PR is all about.

**Comment by jvsam** [comment]
Hi again @greg-lindsay, please check this PR if time permits. Let us know if there are issues with it. Thank you.

**Comment by jvsam** [comment]
Hello again @greg-lindsay kindly check if you have time. Thank you.

**Comment by illfated** [comment]
I appreciate that it may be a bit daunting to review this PR content and to see what has actually been changed.
Use this whitespace setting to make it easier to spot the changes at least for the first half of the page:

image

**Comment by jvsam** [comment]
Hi @greg-lindsay, do you have any update on this? If there are any issues with this PR, we would appreciate if you can provide feedback so we can make the necessary changes. Thank you.

**Comment by illfated** [comment]
Please notify me if there is anything at all I can do to make this pull request and its content more agreeable.

**Comment by jvsam** [comment]
@illfated there seems to be merge conflicts. Can you please check and resolve?

**Comment by illfated** [comment]
Thank you for pointing out the change.
Looks like I should have checked what the actual change was before attempting to merge the `public` branch into my PR branch, which caused a duplicate file to be created with the added file name extension `.orig` instead of keeping only the merged version of the file. Oh well, never mind. It should be back to the original state now, with the metadata change incorporated:
```diff
- audience:
+ audience: itpro
```

**Comment by jvsam** [comment]
Thanks for the quick update, @illfated 

@greg-lindsay, the merge conflicts have been resolved. Can you please look at this again and merge if there are no issues? Thank you.

@officedocsbot assign @greg-lindsay

**Comment by jvsam** [comment]
@officedocsbot assign @greg-lindsay

**Comment by illfated** [comment]
Thank you for the merge, much appreciated. 👍 😃

**Pull request merged**
