### PR TITLE
update licensing requirements

### PR DESCRIPTION
**Pull request by MaratMussabekov**
https://github.com/MicrosoftDocs/windows-itpro-docs/issues/8911

### CODE REVIEW

**Comment by MaratMussabekov** [comment]
Dear @JohanFreelancer9,
kindly do the copy editor review for this PR.

Dear @e0i, for your information

Thank you

**Review by illfated — APPROVED** [review]
Looks good to me, fairly straightforward adjustments.

**Review by JohanFreelancer9 — APPROVED** [review]

**Comment by alexaguilar89** [comment]
help to check

**Comment by illfated** [comment]
#sign-off

**Comment by adirdidi** [comment]
Thank you for your comment, I will address it as part of a different change I'm making to the page.

**Comment by adirdidi** [comment]
Addressed, you should see the change during noon PST tomorrow.

**Comment by illfated** [comment]
@adirdidi : Would you mind adding a minimum of information to your GitHub user profile page? That would make it slightly easier for others to be aware of your role in the team.

**Pull request closed without merging**
