### PR TITLE
the first link under "related topics"

### PR DESCRIPTION
**Pull request by LaurenMoynihan**
the first link under "related topics" has a broken link. I proposed what might be the right one but not sure. Can you please update? For some reason this issue is blocking my ability to redirect my docs in the redirection file for windows-docs-pr.  Thanks!
Lauren

### CODE REVIEW

**Comment by illfated** [comment]
@LaurenMoynihan 
The default branch for this repository has changed from master to public. Please edit your pull request to change the merge target to public via the Edit button at the top right corner. Thanks.

**Comment by LaurenMoynihan** [comment]
ok done. thx!
Lauren

________________________________

**Comment by illfated** [comment]
Very well, fair enough. It appears that in making the change, your [`patch-2`](https://github.com/LaurenMoynihan/windows-itpro-docs/tree/patch-2) branch has got a backlog compared to the ["head" of the public branch](https://github.com/MicrosoftDocs/windows-itpro-docs), adding 2 more files to your original 1 file change. I will make a local copy of your fork & branch, update it and push a PR to your repository to update it and (hopefully) remove that discrepancy.

**Comment by illfated** [comment]
There you go. Hope you will be able to choose between following up on my PR or use your own software (git) tools to update your branch [`LaurenMoynihan:patch-2`](https://github.com/LaurenMoynihan/windows-itpro-docs/tree/patch-2) .

**Comment by LaurenMoynihan** [comment]
hey Trond,

What is it that I need to do? Sorry, this is getting a little advanced for me.

thanks,
Lauren

________________________________

**Comment by illfated** [comment]
OK, right. I thought that it might be more advanced than you expected. I have been debating this situation in my own head for a little while, trying to find out which route will be easier and more practical for your use. One of the challenges I faced is the fact that you have got some older work stored in a couple of unrelated branches in your current repository.

If keeping the old branches is not much of a concern to you, you could choose to delete your existing repository and fork the https://github.com/MicrosoftDocs/windows-itpro-docs repository to your own repository (making it a new https://github.com/LaurenMoynihan/windows-itpro-docs repository with the `public` branch the new default. This route will not keep the old branches, unfortunately, so it is only recommended if you don't specifically need the old branches anymore.

On the other hand, I can suggest a different route, if you want to keep the current branches as well as updating the current PR branch to make it work as intended. This depends very much on you trusting me to help you rebase/merge new content into your existing repository, by adding me as a collaborator in your windows-itpro-docs repository. I don't know if this feels intrusive to you or if you are OK with this. If there are someone you know well, maybe a colleague at work, who can help you do the same changes, make that user a collaborator in your windows-itpro-docs repository to enable that user to update your master branch, PR branch ( [`LaurenMoynihan:patch-2`](https://github.com/LaurenMoynihan/windows-itpro-docs/tree/patch-2) ) as well as adding the [`MicrosoftDocs:public`](https://github.com/MicrosoftDocs/windows-itpro-docs) branch to your current repository.

I know. This can definitely look overwhelming to anyone who are not yet familiar with how branches, repositories and git commands work. I still hope you will be able to share your thoughts on what you would prefer to keep or let go as you move forward with your decisions.

**Comment by illfated** [comment]
Simple suggestion: if you just want to get this PR updated without any other changes,
you can merge my PR into your repository by going to this page:
https://github.com/LaurenMoynihan/windows-itpro-docs/pull/1
then scroll down to the bottom of the page and press the green [Merge] button,
to have your PR updated without the 2 unrelated files.

**Comment by illfated** [comment]
Sorry for creating trouble in the first place. As a Microsoft employee, you should probably use the `master` branch as your target, in contrast to users not employed by Microsoft (like me).

See if your PR goes back to normal (only 1 file included) if you switch back to the master branch.

**Comment by e0i** [comment]
@mjcaparas Following up for updates regarding review.

**Pull request merged**
