### PR TITLE
CI 103173

### PR DESCRIPTION
**Pull request by Deland-Han**
Modify this article according to [CI 103173](https://dev.azure.com/ContentIdea/ContentIdea/_queries/edit/103173/?triage=true). Remove this out-date information.

### CODE REVIEW

**Comment by Deland-Han** [comment]
sign-off

**Comment by e0i** [comment]
@manikadhiman This PR that removes an outdated policy description is ready for review. Thanks.

**Comment by e0i** [comment]
@Deland-Han Any updates with suggested changes? Thanks.

**Comment by Deland-Han** [comment]
Hi @ManikaDhiman and @e0i,

Sorry I did not see your comments. I have modified the other two article as you suggested. Please review.

**Pull request merged**
