### PR TITLE
Updated article

### PR DESCRIPTION
**Pull request by VLG17**
https://github.com/MicrosoftDocs/windows-itpro-docs/issues/2741

### CODE REVIEW

**Comment by mypil** [comment]
@jdeckerms - Can you please assist to check, approve and merge the content for this PR based on issue #2741?

Thank you.

**Comment by VLG17** [comment]
@jdeckerms i wanted to mention that not only this article is out of date, but the entire article tree refferencing VAMT:

image

**Comment by mypil** [comment]
@jdeckerms - I would like to follow up on this. Can you please assist to check, approve and merge the content for this PR based on issue #2741?

Thank you.

**Comment by mypil** [comment]
@jdeckerms - I would like to follow up on this. Can you please assist to check, approve and merge the content for this PR based on issue #2741?

Thank you.

**Pull request merged**
