### PR TITLE
Updating typo for face FAR

### PR DESCRIPTION
**Pull request by mapalko**
Updating the False Accept rate for facial recognition to add a percentage to the measure.

### CODE REVIEW

**Comment by illfated** [comment]
Ref. issue ticket #3239

**Comment by illfated** [comment]
Github does not allow for comments to be made outside of the lines containing changes in the source, so I will comment here instead.

Maybe also add % after `0.001` in the previous section, `False Accept Rate (FAR): <0.001 – 0.002%` ?

(Ref. https://github.com/MicrosoftDocs/windows-itpro-docs/issues/3239#issuecomment-482420429)

**Comment by mypil** [comment]
@DaniHalfin - can you please assist to check, approve and merge the content for this PR based on issue #3239?

Thank you.

**Comment by mypil** [comment]
@DaniHalfin - I would like to follow up on this. Can you please assist to check, approve and merge the content for this PR based on issue #3239?

Thank you.

**Comment by mypil** [comment]
@AndreaBarr - would you be able to merge the content of this PR? Thanks.

**Comment by AndreaBarr** [comment]
@MikeStephens-MS Can you please review this and approve it for merging?

**Comment by mapalko** [comment]
@AndreaBarr , Mike Stephens no longer works on WHFB. Dani and I are the current owners.

**Comment by mypil** [comment]
@DaniHalfin @mapalko - I would like to follow up on this. Can you please assist to check, approve and merge the content for this PR based on issue #3239?

Thank you.

**Comment by mapalko** [comment]
I approve of this change, but I don't think I have write access to merge it.

**Comment by mypil** [comment]
@AndreaBarr - would you be able to merge the content of this PR? This has been approved for merging by @mapalko. Thank you.

**Pull request merged**
