### PR TITLE
URL addition of OWA

### PR DESCRIPTION
**Pull request by joinimran**
Added URL for OWA attachment protection using WIP

Problem: https://github.com/MicrosoftDocs/windows-itpro-docs/issues/3747

### CODE REVIEW

**Comment by e0i** [comment]
@dulcemontemayor The PR introduces a URL for OWA attachment protection using WIP and resolves issue #3747. Please review as the time permits.

**Comment by illfated** [comment]
@joinimran : May I ask your opinion on the bullet points before the URLs in this table?

When I browse/read/look at the Rich Text Diff view,
https://github.com/MicrosoftDocs/windows-itpro-docs/pull/4840/files?short_path=877ff33#diff-877ff334a03b9dc9815e0c8053e86c8c ,
it looks to me like the bullet points (`<li>`) are not very useful visually, compared to the rows without bullet points.
What do you think?

**Comment by e0i** [comment]
> @joinimran : May I ask your opinion on the bullet points before the URLs in this table?
> 
> When I browse/read/look at the Rich Text Diff view,
> https://github.com/MicrosoftDocs/windows-itpro-docs/pull/4840/files?short_path=877ff33#diff-877ff334a03b9dc9815e0c8053e86c8c ,
> it looks to me like the bullet points (`<li>`) are not very useful visually, compared to the rows without bullet points.
> What do you think?

cc @joinimran

**Comment by e0i** [comment]
@DulceMontemayor Following up for updates.

**Comment by joinimran** [comment]
Agree with @e0i , I am going to remove all the bullets and make URLs plain in the table.

**Pull request merged**
