### PR TITLE
change from insiders-fast to prod repositories

### LINKED ISSUE #8943: We need to add clarification to the channel/version for the MDE repo.
[Enter feedback here]

Dear Sir or Madam,

/*
For example, if you are running CentOS 7 and wish to deploy MDATP for Linux from the insiders-fast channel:

Bash

Copy
sudo yum-config-manager --add-repo=https://packages.microsoft.com/config/centos/7/insiders-fast.repo
*/

After this portion, we should have the following note:
For production environments, use the Production channel:
sudo yum-config-manager --add-repo=https://packages.microsoft.com/config/centos/7/prod.repo

Note:  For any version of RHEL/CENTOS/Oracle 7.0 thru 7.10, please use 7 repo.

Thanking you in advance,
Yong Rhee [yongrhee@microsoft.com]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e2197cba-30ac-1749-e25a-6f39c9ee9d20
* Version Independent ID: bcd14f13-ab59-8e69-5c83-42fee6e51f87
* Content: [Deploy Microsoft Defender ATP for Linux manually - Windows security](https://docs.microsoft.com/en-us/windows/security/threat-protection/microsoft-defender-atp/linux-install-manually)
* Content Source: [windows/security/threat-protection/microsoft-defender-atp/linux-install-manually.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/public/windows/security/threat-protection/microsoft-defender-atp/linux-install-manually.md)
* Product: **w10**
* GitHub Login: @Dansimp
* Microsoft Alias: **dansimp**

### PR DESCRIPTION
**Pull request by konstruktoid**
change from insiders-fast to prod repositories, and do some basic linting

Closes #8943 

Signed-off-by: Thomas Sjögren <konstruktoid@users.noreply.github.com>

### CODE REVIEW

**Comment by konstruktoid** [comment]
Rich diff: https://github.com/MicrosoftDocs/windows-itpro-docs/pull/8960/files?diff=unified&w=1&short_path=8f15c25#diff-8f15c25ac9cfb463694328e86bf49f1a47108fbcaf6d7c1cff1d59be3e14ce5d

**Review by illfated — APPROVED** [review]
Looks quite good to me, coherent with the PR description.

Also, for those who prefer to review in source view, but want to focus on the effective changes, this is the **Hide whitespace changes** feature:
- https://github.com/MicrosoftDocs/windows-itpro-docs/pull/8960/files?diff=unified&w=1

**Comment by konstruktoid** [comment]
Added updated instructions regarding `curl` and the deprecation of `apt-key` (ref: https://github.com/MicrosoftDocs/windowsserverdocs/issues/5193)

**Comment by e0i** [comment]
@JohanFreelancer9 Copy editing is needed for this PR. Thanks.

**Review by JohanFreelancer9 — APPROVED** [review]

**Review by illfated — APPROVED** [review]

**Comment by illfated** [comment]
#sign-off

**Comment by illfated** [comment]
(ref. #9019)

**Comment by nam31** [comment]
@Dansimp PR has been copyedited and is ready for final review, could you please check and merge? Thanks!

**Review by illfated — APPROVED** [review]

**Comment by illfated** [comment]
**This branch has conflicts that must be resolved**
Only those with write access to this repository can merge pull requests.

**Conflicting files**

windows/security/threat-protection/microsoft-defender-atp/linux-install-manually.md

**Comment by konstruktoid** [comment]
Is there any point updating this since the new page is located at https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/security/defender-endpoint/linux-install-manually.md?

**Comment by e0i** [comment]
@konstruktoid You may reintroduce the change in the new file as the source path has been changed as you had mentioned. Thanks.
‘

**Pull request closed without merging**
