### PR TITLE
Added PowerShell script specific documentation

### PR DESCRIPTION
**Pull request by BrianSteingraber**
Added specific descriptions for the Split-PolicyRules.ps1, Merge-PolicyRules.ps1 and Baseline-ADImport.ps1 PowerShell scripts.

These descriptions are taken straight from the Policy Analyzer documentation (by Aaron Margosis)

### CODE REVIEW

**Comment by illfated** [comment]
(Ref. #6784 )

**Comment by DulceMontemayor** [comment]
@e0i please resolve branch conflicts first, thanks.

**Comment by e0i** [comment]
@BrianSteingraber 

Would you be able to resolve merge conflicts to proceed with the review? Thank you.

**Comment by BrianSteingraber** [comment]
@e0i, I'll try to!

**Comment by illfated** [comment]
Looks good, thank you for the quick and effective follow-up! 👍

**Comment by illfated** [comment]
Well... sorry to say, but it appears you removed the list I added in my PR #7072 (commit https://github.com/MicrosoftDocs/windows-itpro-docs/commit/ea82895b12781141645ac507cd19ebaf4c94bcfd).

I think you need to add it back and also add the full content of your original text.

**Comment by illfated** [comment]
Maybe I am confusing myself too much here. I thought my PR #6800 was the cause behind this file conflict, but I somehow mixed up your other PR with this one.

**Pull request closed without merging**
