### PR TITLE
Update event-4663.md

### PR DESCRIPTION
**Pull request by msbemba**
Checked and updated 0x4 to 0x6 (access mask) for     AppendData (or AddSubdirectory or CreatePipeInstance)

Reference per testing:-

Subject:
  Security ID: LB\administrator
  Account Name: administrator
  Account Domain: LB
  Logon ID: 0x3DE02

Object:
  Object Server: Security
  Object Type: File
  Object Name: C:\asdf\New Text Document.txt
  Handle ID: 0x178
  Resource Attributes: S:AI
 

Process Information:
  Process ID: 0x113c
  Process Name: C:\Windows\System32\notepad.exe

Access Request Information:
  Accesses: WriteData (or AddFile)
    AppendData (or AddSubdirectory or CreatePipeInstance)
    Access Mask: 0x6

Fixes#https://github.com/MicrosoftDocs/windows-itpro-docs/issues/10650

### CODE REVIEW

**Comment by msbemba** [comment]
@JohanFreelancer9 Please copy review

**Review by JohanFreelancer9 — APPROVED** [review]

**Comment by yogkumgit** [comment]
@Dansimp Please merge this PR. Thanks

**Comment by aczechowski** [comment]
hold off for now - see discussion in #10650

**Comment by vinaypamnani-msft** [comment]
Access Mask values are bitwise flags, so a value 0x6 means 0x2 (WriteData) and 0x4 (AppendData) are set. I'll close the related PR and this issue.

**Pull request closed without merging**
