### PR TITLE
Deploy WDAC/Intune: update intro description

### PR DESCRIPTION
**Pull request by illfated**
**Description:**
As discussed in issue ticket #4482 (Custom WDAC policy in Intune), it would be useful to add a detail on implementing a custom WDAC policy in Intune. Without this detail, the implication is that you can ONLY
use the Endpoint Protection template to configure WDAC in Intune.

Thank you to @Air-Git for following up on this topic and the content.

**Proposed change:**

- add details missed in the previous PR #5659 (Content Update)

**issue ticket closure or reference:**
Ref. #4482 (already closed)

**Additional notes:**
Feel free to suggest modifications or improvements as you deem necessary.

### CODE REVIEW

**Comment by illfated** [comment]
@jvsam : I presume you will be following this PR to comment when needed.
@Air-Git : You are welcome to comment regarding any modification request.
@JohanFreelancer9 & @nenonix : You are welcome to perform a copy review.

**Comment by illfated** [comment]
@Ait-Git : I may have missed out on adding the part about custom OMA-URI setting in the last sentence on this page. Please confirm.

**Comment by illfated** [comment]
#sign-off

**Comment by jvsam** [comment]
Thanks @illfated. 

@Dansimp for your review and approval. Please merge if you see no issues with the suggested changes. Thank you. 

@officedocsbot assign @Dansimp

**Comment by illfated** [comment]
Thanks to all of you for the follow-up & merge.

**Pull request merged**
