### PR TITLE
Key Trust now support RDP

### PR DESCRIPTION
**Pull request by tayasuta**
Please take a look at the docs below. Now WHfb Key Trust model supports RDP.
https://docs.microsoft.com/en-us/windows/security/identity-protection/hello-for-business/hello-deployment-rdp-certs

### CODE REVIEW

**Comment by illfated** [comment]
( ref. PR #9394 & #9396 )

**Review by illfated — APPROVED** [review]

**Comment by mapalko** [comment]
This issue isn't accurate. The instructions in the linked doc are basically for how to issue a cert for a key trust credential so it can be used as a supplied credential for RDP. Supplying only the key is still not supported.

**Review by JohanFreelancer9 — APPROVED** [review]
Copy is fine but please see @mapalko's comment.

**Comment by e0i** [comment]
Closing based on the comments above.

**Pull request closed without merging**
