### PR TITLE
Added more detail about removing Delegated Admin Permissions

### PR DESCRIPTION
**Pull request by brentkendall**
Added more detail about removing Delegated Admin Permissions

### CODE REVIEW

**Comment by illfated** [comment]
Cosmetic detail, but I notice a couple of double spaces between sentences (after full stop), but it is not consistent. Is this intended or just overlooked?

**Comment by brentkendall** [comment]
That was intentional (that’s how I was taught), but if it’s inconsistent with the rest of the document, you can change it to one space.

Thanks,

Brent

**Comment by illfated** [comment]
Not a big deal. I presume the extra white space will be ignored, at least for certain in the `registration-auth.md` file and maybe in the resulting HTML doc page too. I was mostly curious if it was intentional.

**Comment by greg-lindsay** [comment]
Merging

**Pull request merged**
