### PR TITLE
Add files via upload

### PR DESCRIPTION
**Pull request by Reeced40**
https://github.com/MicrosoftDocs/windows-itpro-docs/issues/3385
Fixed screenshot and added note in PR https://github.com/MicrosoftDocs/windows-itpro-docs/pull/3694

### CODE REVIEW

**Comment by mypil** [comment]
@get-itips - can you please assist to review the screenshot image and let us know if something needs to be changed? Thanks.

**Comment by get-itips** [comment]
The image is ok now, 
As the UI has changed, the instructions should reflect that too, for example, when it says:

_Click the Virus & threat protection tile (or the shield icon on the left menu bar) and then click Virus & threat protection settings:_

it should read

_Click the Virus & threat protection tile (or the shield icon on the left menu bar) **and then click Manage Settings under** Virus & threat protection settings:_

**Comment by mypil** [comment]
@Justinha @jaimeo @DaniHalfin - Can you please assist to check, approve and merge the content of this PR based on issue #3385? 
Please take note the the screenshot image is on PR #3694 which also need to be merged.

Thank you.

**Comment by mypil** [comment]
@Justinha - I can see that you merged PR #3694. Can you also check whether this PR needs to be merged? This contains the screenshot image. Please advise what needs to be done to this PR. Thank you.

**Pull request merged**
