### PR TITLE
Credential Guard: Enterprise & Education SKU

### PR DESCRIPTION
**Pull request by illfated**
Just to make it clear that Credential Guard is not supported on Windows 10 Pro or Windows 10 Home edition

Ref. closed issue ticket #4025

Thanks to @JonZeolla for raising the question by opening the ticket.
Thanks to @tecxx for taking the time to create and follow up CRM:0773000358 (MSRC).

Look out for my next PR to follow up other documents from the same ticket.

### CODE REVIEW

**Review by illfated — COMMENTED** [review]
Nothing fancy, just a 1 line update (clear text).

**Comment by illfated** [comment]
#sign-off

**Comment by illfated** [comment]
(ref. #8436)

**Review by RAJU2529 — COMMENTED** [review]
Windows 10 <=1903 Enterprise and Education SKUs
Windows 10 >=1909 Enterprise and Education SKUs

If both have appeared means it gives much contradiction, meaning gives in between 1903 and 1909
windows 10  versions from enterprise , education editions are  not compatible

**Comment by illfated** [comment]
Not sure if I get your exact meaning, but are you saying that the suggested change implies that versions between 1903 and 1909 are not compatible?

If yes, then I guess there should only be one line saying `Windows 10 Enterprise and Education SKUs`

Is that your recommendation, to merge the 2 lines and remove the version information?

**Comment by tecxx** [comment]
currently it looks like this:

image

based on current research, best "fix" would be to just have one line for windows 10

* Windows 10 Enterprise and Education SKUs
* Windows Server 2016
* Windows Server 2019




also, there are more pages having an inconsistency:
"Windows Defender Credential Guard: Requirements" - https://docs.microsoft.com/en-us/windows/security/identity-protection/credential-guard/credential-guard-requirements
"How Windows Defender Credential Guard works" - https://docs.microsoft.com/en-us/windows/security/identity-protection/credential-guard/credential-guard-how-it-works
"Windows Defender Credential Guard protection limits" - https://docs.microsoft.com/en-us/windows/security/identity-protection/credential-guard/credential-guard-protection-limits
"Considerations when using Windows Defender Credential Guard" - https://docs.microsoft.com/en-us/windows/security/identity-protection/credential-guard/credential-guard-considerations
"Windows Defender Credential Guard: Known issues" - https://docs.microsoft.com/en-us/windows/security/identity-protection/credential-guard/credential-guard-known-issues

they all list Windows 10 (without SKUs) and Server 2016 (Server 2019 is missing):
image

either update all these pages with the current information, or as an alternative approach specify the requirements explicitely in "**Windows Defender Credential Guard: Requirements**" by adding a statement here:
image

add -> Windows 10 Enterprise or Education SKU


thanks for updating the docs, highly appreciated.

**Comment by illfated** [comment]
Thank you for confirming. Will fix.

**Review by illfated — COMMENTED** [review]
#sign-off

**Comment by illfated** [comment]
I could have made additional changes to the document, but felt that the key improvement was more important.

**Comment by e0i** [comment]
@JohanFreelancer9 Copy editing is needed for this PR. Thanks.

**Review by DulceMontemayor — APPROVED** [review]

**Pull request merged**
