### PR TITLE
update link to new version of the tool

### PR DESCRIPTION
**Pull request by VLG17**
https://github.com/MicrosoftDocs/windows-itpro-docs/issues/5972#issuecomment-581356661

### CODE REVIEW

**Comment by denisebmsft** [comment]
Hello @VLG17. Thank you for submitting this pull request. There is one little thing that must be fixed, though. GitHub doesn't support underscores in a file name. "dg_readiness_tool.md" must be renamed. "dg-readiness-tool.md" would work. I'll try to take a look at this later today, or route to someone on my team. But we can't merge this just yet.

**Comment by illfated** [comment]
Hmm, that is mildly surprising to me, at least when looking at the GitHub file name: https://github.com/MicrosoftDocs/windows-itpro-docs/blob/public/windows/security/identity-protection/credential-guard/dg_readiness_tool.md

Then again, I guess the docs.microsoft.com pages don't support that filename structure, as you said.

**Comment by mypil** [comment]
@JohanFreelancer9 - kindly do the copy editor review for this PR. Thanks.

**Comment by VLG17** [comment]
> Hello @VLG17. Thank you for submitting this pull request. There is one little thing that must be fixed, though. GitHub doesn't support underscores in a file name. "dg_readiness_tool.md" must be renamed. "dg-readiness-tool.md" would work. We can't merge this just yet.

@denisebmsft I copied that file name from the article itself, so i don't understand why it's a problem, because it was already in the article and the reference was working fine. Should we then change all the .md references in the article containing underscores?

**Comment by illfated** [comment]
If so, you would need to change the GitHub repository file name as well and trusting that the file name change replicates to docs.microsoft.com, which would be less likely to be accepted (unless asked to do so by one of the MS Docs tech writers). Maybe the project manager (D. Simpson) could comment and recommend the best way to deal with that question.

**Comment by VLG17** [comment]
> > Hello @VLG17. Thank you for submitting this pull request. There is one little thing that must be fixed, though. GitHub doesn't support underscores in a file name. "dg_readiness_tool.md" must be renamed. "dg-readiness-tool.md" would work. We can't merge this just yet.
> 
> @denisebmsft I copied that file name from the article itself, so i don't understand why it's a problem, because it was already in the article and the reference was working fine. Should we then change all the .md references in the article containing underscores?

@denisebmsft could you please help us with this?

**Comment by mypil** [comment]
@Dansimp @denisebmsft @DulceMontemayor - Would you be able to help review and address how we can get this PR merged? This is based on this https://github.com/MicrosoftDocs/windows-itpro-docs/issues/5972#issuecomment-588969536.

Thank you.

cc: @kenwith

**Comment by denisebmsft** [comment]
Hello! I am working on this today. I realize that the filename was copied; however, it still won't work in GitHub. It might work in preview, but it will not work on the live site. I have cloned the working branch here and will rename the file that has the underscores, and then fix any broken links that causes. Then we will be able to merge this pull request. Stay tuned!

**Pull request closed without merging**
