### PR TITLE
Match heading levels and field formats with other telemetry docs

### PR DESCRIPTION
**Pull request by iadgovuser1**
Bump telemetry category headings to level 3 to match other telemetry documentation (all the Basic telemetry documentation) that uses level 3 for category. Remove the : character from field names to match other telemetry documentation (all the Basic telemetry documentation) that doesn't use a : character.

### CODE REVIEW

**Comment by shortpatti** [comment]
@iadgovuser1, please sign the Contributor License Agreement so that these changes can be published.

**Comment by shortpatti** [comment]
@iadgovuser1, please sign the [Contributor License Agreement](https://cla.opensource.microsoft.com/MicrosoftDocs/windows-itpro-docs?pullRequest=1001).

**Comment by DaniHalfin** [comment]
@iadgovuser1 thanks for taking your time to work on this.
I'd have to reject the current PR, for multiple reasons : 
1. The heading levels in this doc aren't consistent with the other docs intentionally, due to having slightly different depth levels. We'd like to make the content more consumable, and so we'd rather have something in the righthand side navigation bar, than have it empty for the sake of consistency.
2. I'd have to make a change on the backend to make sure that formatting changes stay consistent, and so there's no point in making 2 changes.

In the future, if there's a sweeping formatting issue, I'd ask you to raise it as an issue, so that we can deal with it on the backend.

Thanks!

**Comment by iadgovuser1** [comment]
@DaniHalfin

Thanks for the follow up. What's driving this PR is code I've written for parsing all telemetry documentation so it is easier to compare telemetry changes between releases of Windows. I can work around the different heading levels in my code.

**Pull request closed without merging**
