### PR TITLE
Update microsoft-defender-advanced-threat-protection.md

### PR DESCRIPTION
**Pull request by ErikMoreau**
replaced link to ATP trial (ended up on Windows 10 devices for business page with no link to ATP Trial

### CODE REVIEW

**Comment by illfated** [comment]
Out of curiosity, would it be useful in any way to skip the `/en-us/` part of the link? I mean, I tested removing it and got mostly the same link in return (https://www.microsoft.com/en-us/microsoft-365/windows/microsoft-defender-atp?rtc=1). I am guessing there are no translated pages for Microsoft ATP trial yet, but would it be practical at a later date, when the page gets translated?

**Comment by e0i** [comment]
@mjcaparas The PR fixes a link to ATP trial is available for review. Thanks.

**Comment by e0i** [comment]
@mjcaparas Following up for updates.

**Comment by Dansimp** [comment]
We did a global search & replace to fix this URL as it shows up often in our docs. All instances should be fixed now, this PR is no longer necessary.

**Comment by illfated** [comment]
The docs.microsoft.com pages are updated with the correct link. I find it interesting to see that the `public` branch is updated, but not synced to the `master` branch yet. Could be a useful observation with regards to which branch to open future PRs to.

**Pull request closed without merging**
