### PR TITLE
Changed the word Certificate for Key #2259

### PR DESCRIPTION
**Pull request by ojrb**
Following the recommendation on issue #2259 I have changed the word **Certificate** for **Key**

### CODE REVIEW

**Comment by ojrb** [comment]
Solution for the issue #2259 in PR #3174

**Comment by mypil** [comment]
@DaniHalfin - can you please assist to check, approve and merge the content for this PR based on issue #2259?

Thank you.

**Comment by jdeckerms** [comment]
Issue #2259 is saying that the text "requires Windows Server 2016 domain controllers" is incorrect, not the word "certificate".

**Comment by mypil** [comment]
@jdeckerms - this is also related to issue #2379.

**Comment by mypil** [comment]
@jdeckerms @DaniHalfin - can you please assist to check, approve and merge the content for this PR based on issue #2379 and #2259?

Thank you.

**Comment by mypil** [comment]
@AndreaBarr - would you be able to merge the content of this PR? Thank you.

**Pull request merged**
