### PR TITLE
Remove TSF1/2 Deprecate

### PR DESCRIPTION
**Pull request by embender**
PM for Text Input team here - The Text Input team is not poised to release the TSF3 IMEs publicly at this time so we would like to remove this update as it's not accurate and can lead to confusion amongst our external customers.

thanks! reach out to @embender if you have more questions

### CODE REVIEW

**Comment by embender** [comment]
Hi,

It appears this what I edited out of the MSDN article is still live on the site at the moment; when will MSDN reflect this info correctly?

Thanks!
-emily

**Comment by illfated** [comment]
@embender : Usually anything from 1-2 days up to one week, depending on how well the migration process from GitHub to docs.microsoft.com works.

**Comment by embender** [comment]
Thank you!



________________________________

**Comment by illfated** [comment]
Updated today, question resolved:
- https://docs.microsoft.com/en-us/windows/deployment/planning/windows-10-deprecated-features

**Pull request merged**
