### PR TITLE
Clarify firewall requirements

### PR DESCRIPTION
**Pull request by andreiztm**

### CODE REVIEW

**Comment by illfated** [comment]
Out of curiosity (I am not a firewall expert, only a regular user), is this an "either - or" situation, or could it be "and - or" instead?

**Review by JohanFreelancer9 — APPROVED** [review]

**Review by illfated — APPROVED** [review]

**Comment by andreiztm** [comment]
Technically speaking both are required, so it would be and.

**Comment by andreiztm** [comment]
Made the change, please check. Thank you.

**Review by illfated — APPROVED** [review]
The inclusive "and" logic looks better to me. Thank you.

**Comment by illfated** [comment]
#sign-off

**Review by JohanFreelancer9 — APPROVED** [review]

**Comment by illfated** [comment]
@e0i : For your information, the PR has been copy reviewed and updated, it is ready for final review & merge by the document author (jaimeo) or manager (LauraWi).

**Comment by andreiztm** [comment]
Thank you!

**Pull request merged**
