### PR TITLE
Removed links pointing to a personal blog

### PR DESCRIPTION
**Pull request by joinimran**
I think this reference should be removed as the content is pointing to a non-official document. It's a personal blog and we can not refer any information from any personal blog in MS documentation.  All of the links pointing to a personal blog should be removed. Link to **Configuring a proxy for your Surface Hub** , **Configuring a proxy for your Surface Hub** and **Surface Hub and the Skype for Business Trusted Domain List** .

Problem: https://github.com/MicrosoftDocs/windows-itpro-docs/issues/5847

### CODE REVIEW

**Comment by joinimran** [comment]
@nenonix @JohanFreelancer9 - kindly do the copy editor review for this PR. Thanks.

**Comment by illfated** [comment]
#sign-off

**Comment by joinimran** [comment]
Ready to go live. Conflict resolved.

**Comment by illfated** [comment]
Rich diff: https://github.com/MicrosoftDocs/windows-itpro-docs/pull/5863/files?short_path=bb97a55#diff-bb97a556bfce590c1452f5c1a5637858

**Comment by illfated** [comment]
@joinimran : There is a third occurrence of the same link in line 96 of this page, but it is 1 line away from being available for us others to post suggestions for it to be removed, like you have removed the other 2. I will paste the related text here so you can see which part of the document I am talking about:

https://github.com/MicrosoftDocs/windows-itpro-docs/pull/5863/files#diff-bb97a556bfce590c1452f5c1a5637858R96

Field |Success |Failure |Comment |Reference
|------|------|------|------|------|
Internet Connectivity |Device does have Internet connectivity |Device does not have Internet connectivity |Verifies internet connectivity, including proxy connection |
HTTP Version |1.1 |1.0 |If HTTP 1.0 found, it will cause issue with WU and Store |
Direct Internet Connectivity |Device has a Proxy configured Device has no Proxy configured |N/A |Informational. Is your device behind a proxy? |
Proxy Address | | |If configured, returns proxy address. |
**Proxy Authentication** |**Proxy does not require Authentication** |**Proxy requires Proxy Auth** |**Result may be a false positive if a user already has an open session in Edge and has authenticated through the proxy.** |[Configuring a proxy for your Surface Hub](https://blogs.technet.microsoft.com/y0av/2017/12/03/7/)
Proxy Auth Types | | |If proxy authentication is used, return the Authentication methods advertised by the proxy.  |

**Comment by joinimran** [comment]
@illfated Thanks for pointing this out. It's removed. 

@mypil Ready to go live.

**Comment by e0i** [comment]
@Dansimp The PR has been approved by the document author and is ready for merge.

May you have a good day. Thanks.

**Pull request merged**
