### PR TITLE
re: #3829, Wrong value for registering devices

### PR DESCRIPTION
**Pull request by martyav**
#3829 Wrong value for registering devices in Intune

>Its current 500 devices

Our docs and screenshots agree that the current max is 500; for example, the link in the table - https://docs.microsoft.com/en-us/intune/enrollment-autopilot - was last updated ~6 months after this article and it contains a screenshot listing a max of 500 rows, with one row for each device:

image

### CODE REVIEW

**Comment by e0i** [comment]
@greg-lindsay Would you be able to review and merge this PR created by a MS contributor? Thanks.

**Comment by e0i** [comment]
@greg-lindsay Any updates?

**Comment by e0i** [comment]
@lizap Would you be able to merge this PR created by a MS contributor? Thanks.

**Comment by greg-lindsay** [comment]
This was corrected in another edit.

**Pull request closed without merging**
