### PR TITLE
Update autopilot-faq.md

### PR DESCRIPTION
**Pull request by sowjanya365**
Fixed the broken URL.

### CODE REVIEW

**Comment by sowjanya365** [comment]
Fixed the broken URL.

**Comment by mypil** [comment]
@greg-lindsay - can you please assist to check, approve and merge the content for this PR based on issue #2243?

Thank you.

**Comment by mypil** [comment]
@greg-lindsay - I would like to follow up on this.  Kindly assist to check, approve and merge the content for this PR based on issue #2243?

Thank you.

**Comment by illfated** [comment]
Looks good to me. Broken link repaired with 2 hyphens. Simple as that.

**Comment by mypil** [comment]
@kenwith - would you be able to merge the content for this PR? This is just a Level 1 (broken link) issue. Thank you.

**Pull request merged**
