### PR TITLE
Update waas-delivery-optimization.md

### PR DESCRIPTION
**Pull request by cmknox**
Added support for Edge browser installations and updates.

### CODE REVIEW

**Comment by illfated** [comment]
I don't know the specifics, but would an update like this warrant an update to the metadata date field as well?

**Comment by cmknox** [comment]
thanks for asking, no need to update the metadata field for this change.

**Review by illfated — APPROVED** [review]
Looks good to me.

**Comment by illfated** [comment]
#sign-off

**Pull request merged**
