### PR TITLE
Documenting AppCompat events in EDP

### PR DESCRIPTION
**Pull request by javiercarrillo**

### CODE REVIEW

**Comment by lizap** [comment]
@DaniHalfin and @brianlic-msft - can one of you please take a look at these proposed additions to the diagnostic data content? This adds additional events. Thanks!

**Comment by mypil** [comment]
@DaniHalfin and @brianlic-msft - We would like to follow up on this. Can you please assist to check, approve and merge the content for this PR? 

Thank you.

**Comment by DaniHalfin** [comment]
@mypil - we took the discussion on this offline. Going to hold on this PR for now.

**Comment by DaniHalfin** [comment]
Merged internally.

**Pull request closed without merging**
