### PR TITLE
MSD-ATP/Deployment: improve grammar & readability

### LINKED ISSUE #5949: Typos in the Adoption section
There are a lot of typos in the adoption section of this page. I didn't read the other sections, but I think it could use some proofreading. Here is an example: 

In many cases**_,_**organizations will have existing endpoint security products in place...…. But in some cases an organization might also already **_implanted_** an EDR solution.

### PR DESCRIPTION
**Pull request by illfated**
**Description:**

As pointed out in issue ticket #5949 (Typos in the Adoption section), this document needs some proofreading for grammar & semantics.

Thanks to @chhatley for opening the issue ticket.

**Changes proposed:**
- add some commas for grammar & readability
- rearrange a couple of sentences for readability
- add the missing newline at the end of the document

**issue ticket closure or reference:**

Closes #5949

**Additional notes:**

This PR is currently a draft PR to allow more time for additional improvement suggestions to this page.

### CODE REVIEW

**Comment by illfated** [comment]
@chhatley : Feel free to add suggestions for additional improvements in this document.

**Comment by illfated** [comment]
Thanks for marking this PR as ready. Looks like there is no more feedback to gain, even after nearly a fortnight.

**Comment by illfated** [comment]
#sign-off

**Comment by e0i** [comment]
The PR that has been approved by the document author can be merged. Thanks.

**Pull request merged**
