### PR TITLE
issue #2744

### PR DESCRIPTION
**Pull request by MaratMussabekov**
added info about "Safe Samples", sources:
1. [February 2015 anti-malware platform update for Endpoint Protection clients](https://support.microsoft.com/help/3036437/february-2015-anti-malware-platform-update-for-endpoint-protection-cli)
2. [Send file samples when further analysis is required.](https://getadmx.com/?Category=SystemCenterEndpointProtection&Policy=Microsoft.Policies.Antimalware::maps_submitsamplesconsent)
also, about "what data is sent, where it’s stored etc", it is more likely to be out of scope of this article, the link to the article that contains this info is already persist in the source 
"See [Use Microsoft cloud-delivered protection](https://docs.microsoft.com/en-us/windows/security/threat-protection/windows-defender-antivirus/utilize-microsoft-cloud-protection-windows-defender-antivirus) for an overview of Windows Defender Antivirus cloud-delivered protection."

### CODE REVIEW

**Comment by illfated** [comment]
Just a little tip about Pull Requests here on Github: This page does not read the issue number the way a commit is read, so it would be more useful to write something like e.g.
**Windows Defender Antivirus: add note with description for "Send safe samples automatically"**

(You are of course free to write what you think is best, this is just a suggestion.)

**Comment by TokyoScarab** [comment]
Looks good

**Comment by mypil** [comment]
@andreabichsel - can you please assist to check, approve and merge the content for this PR based on issue #2744?

Thank you.

**Comment by mypil** [comment]
@andreabichsel - I would like to follow up on this. Can you please assist to check, approve and merge the content for this PR based on issue #2744?

Thank you.

**Comment by mypil** [comment]
@kenwith - can you possibly help to merge the content of this PR? Thank you.

**Comment by kenwith** [comment]
Yes, and I am starting a project to get the author sorted in metadata so we know who is the author that owns each article in future. Thanks.

**Comment by kenwith** [comment]
Confirmed from references above. Merged.

**Pull request merged**
