### PR TITLE
Isolate Machine Screenshot update - Add Teams

### PR DESCRIPTION
**Pull request by computeronix**
For the respond-alerts.md page, under Isolate a Machine, updated screenshot to show Teams support - https://docs.microsoft.com/en-us/windows/security/threat-protection/microsoft-defender-atp/respond-machine-alerts#isolate-machines-from-the-network

### CODE REVIEW

**Comment by computeronix** [comment]
Added one more change to the page documentation with the screenshot to mention Teams as well in the list of apps that provide Selective Isolation

**Comment by illfated** [comment]
Still looks good to me. @e0i : May we have some follow-up by the document author or manager? Also note that the PR author is a MS Docs team member.

**Comment by e0i** [comment]
Hello, @computeronix We would like to proceed by merging this PR when the document is revised as suggested by document author **mjcaparas**. Thanks.

**Comment by e0i** [comment]
Hello, @computeronix Any updates with review suggestions provided by **mjcaparas** ? Thank you.

**Comment by e0i** [comment]
@computeronix Closing as there has been no follow-up with the document author's revision suggestion. Please re-open the PR to proceed with the review. Thank you for your patience with the process and your contributions.

**Pull request closed without merging**
