### PR TITLE
Updated Instruction and screenshots.

### PR DESCRIPTION
**Pull request by joinimran**
As requested by the user, I have updated the instruction and added a screenshot.

Problem: https://github.com/MicrosoftDocs/windows-itpro-docs/issues/8216

### CODE REVIEW

**Comment by joinimran** [comment]
@JohanFreelancer9 - kindly do the copy editor review for this PR. Thanks.

**Review by JohanFreelancer9 — APPROVED** [review]

**Comment by illfated** [comment]
@joinimran : Will you be able to resolve the file conflict for https://github.com/joinimran/windows-itpro-docs/blob/master/windows/security/threat-protection/device-control/control-usb-devices-using-intune.md via the GUI editor here in your PR, or maybe update your source file, if you know what the external changes are?

**Review by illfated — APPROVED** [review]

**Comment by joinimran** [comment]
No more conflicts, ready to go live.

**Comment by illfated** [comment]
#sign-off

**Pull request merged**
