### PR TITLE
WHfB/Error mitigation: convert table to MarkDown

### LINKED ISSUE #5455: Error Code 0x801C044D listed twice it Error Mitigation Sections
The Error Code 0x801C044D is listed twice in the mitigation section, not adjacent, and with different explanations.  while I get that there might be multiple causes I think you should group them together to make that more obvious.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6b4f9133-887f-17a6-95fc-3712de8a3fa1
* Version Independent ID: 09d34ce8-1590-8202-3e70-e6299dadbb65
* Content: [Windows Hello errors during PIN creation (Windows 10)](https://docs.microsoft.com/en-us/windows/security/identity-protection/hello-for-business/hello-errors-during-pin-creation#feedback)
* Content Source: [windows/security/identity-protection/hello-for-business/hello-errors-during-pin-creation.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/public/windows/security/identity-protection/hello-for-business/hello-errors-during-pin-creation.md)
* Product: **w10**
* Technology: **windows**
* GitHub Login: @mapalko
* Microsoft Alias: **mapalko**

### PR DESCRIPTION
**Pull request by illfated**
**Description:**

Based on community feedback in issue ticket #5455, the Error Code 0x801C044D is listed twice in the mitigation section, not adjacent, and with different explanations. The suggestion is to group them together
to make it more obvious that there are 2 separate causes & mitigations.

Thanks to J.R. Jenkins (@jrjenk) for reporting this issue.

In order to simplify editing and information management in the table, I propose to change the table formatting from simple HTML to MarkDown.
I also suggest sorting the lines based on the Error code Hex values.

**Changes proposed:**
- convert the Error mitigations table to MarkDown
- rearrange the row lines and sort by Hex value (1 exception)
- place the 2 errors with the same Hex value adjacent to each other
- add some missing punctuation
- adjust spacing and remove some redundant whitespace

**issue ticket closure or reference:**

Closes #5455

### CODE REVIEW

**Comment by illfated** [comment]
As usual, @JohanFreelancer9 and @nenonix are invited to do a copy review on this content.

@mapalko : You are welcome to review the content when time permits, seeing that you are listed as author of this page.

@mypil : I presume you want to follow up on this.

**Comment by illfated** [comment]
#sign-off

**Comment by mypil** [comment]
@nenonix @JohanFreelancer9 - kindly do the copy editor review for this PR. Thanks.

**Comment by illfated** [comment]
Regular source code view: https://github.com/MicrosoftDocs/windows-itpro-docs/pull/5501/files
non-whitespace changes: https://github.com/MicrosoftDocs/windows-itpro-docs/pull/5501/files?utf8=%E2%9C%93&diff=unified&w=1
Rich Text Diff (GUI) view: https://github.com/MicrosoftDocs/windows-itpro-docs/pull/5501/files?short_path=748573b#diff-748573bf46cfc3dfc4c3414c93e69d60

**Comment by mypil** [comment]
@mapalko @Dansimp - PR has been copy edited and is ready for final review. This is based on issue #5455

Thank you.

cc: @kenwith

**Pull request merged**
