### PR TITLE
chore: Cleanup OS files

### PR DESCRIPTION
**Pull request by nschonni**

### CODE REVIEW

**Comment by e0i** [comment]
See: #4098

**Comment by e0i** [comment]
@DaniHalfin Any thoughts on this PR?

**Comment by illfated** [comment]
This is a reasonable thing to do for contributors using Git / Git Extension / Git GUI applications to contribute while also browsing their local cloned repository folder on Apple MacOS (`.DS_Store`) or Microsoft Windows  (`Thumbs.db`). This should make it easier to avoid OS files being added in Pull Requests (or even added in commits via MS Docs team members using Git from their local computer OS).

**Comment by e0i** [comment]
@DaniHalfin @lizap @mjcaparas Any thoughs on this PR that introduces changes to Git dotfile? Thanks.

**Comment by e0i** [comment]
@Dansimp Following up for updates.

**Comment by DaniHalfin** [comment]
The default branch for this repository has changed. Commenting to remember to merge this to the new default, if this PR gets merged.

**Comment by nschonni** [comment]
@DaniHalfin I used the Edit to change the target branch to "public"

**Comment by DaniHalfin** [comment]
Thanks, @nschonni !

**Comment by nschonni** [comment]
No problem, you probably have the ability to do this to the other PRs if you want.
PS: I prefer the old name though, because git alias scripts assume that as the name. Also, other docs repos that have changed it usually use "live".

**Comment by illfated** [comment]
Thanks for the comments, useful to know. BTW, isn't Live branch already in use in the private branches?

**Pull request merged**
