### PR TITLE
Update windows-10-enterprise-e3-overview.md

### PR DESCRIPTION
**Pull request by nenonix**
Edited line 18: added "and activated" to enhance clarity and removed "also known as" to keep sentence concise. (Also removed /en-us/ locale code from links on  lines 252 and 253)  Resolves https://github.com/MicrosoftDocs/windows-itpro-docs/issues/2723

### CODE REVIEW

**Comment by illfated** [comment]
Thank you. I was contemplating opening this PR myself, but I see you have already done so and also improved more of the text than I was aware of. Good job. 👍

**Comment by nenonix** [comment]
@illfated   Thanks for the tip (the process of closing issues is a bit more complicated for our team:smiley:)  but if that is the GitHub convention I will try it

**Comment by illfated** [comment]
Very good. BTW, just an hour ago I found another keyword which is used by Github to close issues: `Resolves #<issue_number>` - same way as `Closes #<issue_number>`.

**Comment by illfated** [comment]
Please note: When I said "I usually add `Closes #<issue number>` at the end of my commit text", I meant that it is part of the text written in git (or Git Extensions) when finalizing the commit before pushing. This is the same place as you put your commit text line `As per #2723` -- just to indicate where it is at.

**Comment by nenonix** [comment]
@illfated Thanks.  I read more about  [closing issues with keywords](https://help.github.com/en/articles/closing-issues-using-keywords)  - although it wont have any effect I will not experiment further, "As per" is just how I reference issues.  What convention would you suggest?

**Comment by illfated** [comment]
The most common one is to add `Closes #1234` as the ending line (or one of the ending lines) in the first commit text added to the commit before pushing the commit to the origin repository and creating the PR. Subsequent commits to the same PR do not need to have any more text than what is needed to explain changes in the commit (see my PR #2817 as an example with extra commit added to the same PR).

When I put the same text in the Github page comment as in the PR, it was mostly because I did not see any need to expand on the existing text to explain the issue, due to my preceding dialog with Justinha. So the occurrence of Closes ... in that page is mostly only useful to link the PR page back to the originating issue (it does not close the issue ticket by itself, that is what (`Closes #2813`) the first commit text does. (And the commit text is where the keyword "Resolves #..." is an option.)

**Comment by nenonix** [comment]
@illfated I read more about [closing issues with keywords](https://help.github.com/en/articles/closing-issues-using-keywords)  it probably wont have any effect but I now see how it works. Thank you.

**Pull request merged**
