### PR TITLE
Update mandatory-user-profile.md

### PR DESCRIPTION
**Pull request by baardhermansen**
Updated outdated URLs.
Some markdown corrections with numbered lists, they were out of order.
Took a teeny bit of liberty renaming headings.

### CODE REVIEW

**Comment by illfated** [comment]
Looks pretty good to me. I was quite pleased to see that the internal link change worked properly. I recommend using "Hide whitespace changes" (https://github.com/MicrosoftDocs/windows-itpro-docs/pull/6085/files?utf8=✓&diff=unified&w=1) to see the changes in the correct order, otherwise the changes may appear too scattered to compare the way you are used to. @JohanFreelancer9 , would you like to perform a copy review?

**Comment by JohanFreelancer9** [comment]
Looks good.

**Comment by illfated** [comment]
#sign-off

**Comment by e0i** [comment]
cc @Dansimp

**Pull request merged**
