### PR TITLE
windows server 2016 or later change

### PR DESCRIPTION
**Pull request by Malind19**
Changed the all domain controllers to sipport windows server

### CODE REVIEW

**Comment by mypil** [comment]
@nenonix @JohanFreelancer9 - kindly do the copy editor review for this PR. Thanks.

**Comment by JohanFreelancer9** [comment]
Copy edited - no changes.

**Comment by illfated** [comment]
Ref. #3082

**Comment by mypil** [comment]
@DaniHalfin - can you please assist to check, approve and merge the content for this PR based on issue #3082?

Thank you.

**Comment by mypil** [comment]
@DaniHalfin - I would like to follow up on this. Can you please assist to check, approve and merge the content for this PR based on issue #3082?

Thank you.

**Comment by mypil** [comment]
@DaniHalfin - I would like to follow up on this. Can you please assist to check, approve and merge the content for this PR based on issue #3082?

Thank you.

**Pull request merged**
