### PR TITLE
minor fix

### PR DESCRIPTION
**Pull request by MaratMussabekov**
https://github.com/MicrosoftDocs/windows-itpro-docs/issues/9408

### CODE REVIEW

**Comment by MaratMussabekov** [comment]
Dear @JohanFreelancer9,
kindly do the copy editor review for this PR.

Dear @nam31, for your information

Thank you

**Review by illfated — APPROVED** [review]
Looks like a good improvement to me.

Targeted public page:
- https://docs.microsoft.com/en-us/windows/client-management/mdm/policy-configuration-service-provider

**Review by JohanFreelancer9 — APPROVED** [review]

**Comment by nam31** [comment]
@Kateyanne, PR has been copyedited and is ready for final review, could you please check and merge? Thanks!

**Comment by nam31** [comment]
@Dansimp, PR has been copyedited and is ready for final review, could you please check and merge? Thanks!

**Pull request merged**
