### PR TITLE
Link update

### PR DESCRIPTION
**Pull request by joinimran**
As suggested I have updated the correct link.

Problem: https://github.com/MicrosoftDocs/windows-itpro-docs/issues/7896

### CODE REVIEW

**Review by illfated — APPROVED** [review]

**Comment by illfated** [comment]
BTW, I notice that there are a handful PowerShell commands on the same page, but the MarkDown code block syntax highlighting says only "text".

@joinimran : Do you mind if I make a PR to your repository, adding those changes, just to get that detail out of the way?

**Comment by joinimran** [comment]
@illfated - Your input is always welcome.

**Comment by illfated** [comment]
Thanks. Looking forward to the merge of my PR https://github.com/joinimran/windows-itpro-docs/pull/3 to your [`patch-114`](https://github.com/joinimran/windows-itpro-docs/tree/patch-114) branch.

**Comment by illfated** [comment]
Oh well. I can always open my own PR to the public branch to have those changes applied later.

**Pull request merged**
