### PR TITLE
Making a change to Cryptomining policy on the 30th of Aug

### PR DESCRIPTION
**Pull request by ItIsJustMee**
Would not like to make changes until the 30th of August.
Can you hold off until then please, or should I resubmit then?

### CODE REVIEW

**Review by JohanFreelancer9 — APPROVED** [review]
Copy review.

**Comment by ItIsJustMee** [comment]
Please hold off until the 3rd of September 2021. Updates got delayed.

**Comment by e0i** [comment]
@ItIsJustMee Can we move forward with this PR since it is over 3rd of Sept.? Thanks.

**Comment by ItIsJustMee** [comment]
@e0i Yes we can, can you please move forward with it?

**Comment by ItIsJustMee** [comment]
Please publish this.

**Comment by ItIsJustMee** [comment]
@e0i , @JohanFreelancer9 , @denisebmsft can you please publish this now?

**Comment by ItIsJustMee** [comment]
Can we publish this today?

**Comment by ItIsJustMee** [comment]
> @ItIsJustMee Can we move forward with this PR since it is over 3rd of Sept.? Thanks.

Yes please.

**Pull request merged**
