### PR TITLE
MDOP May 2019 Servicing Release: new Hotfix Link

### LINKED ISSUE #4574: Hotfix link is outdated
The link "Desktop Optimization Pack" goes to the July 2018 servicing release.
MABM version chart here - https://blogs.technet.microsoft.com/dubaisec/2016/05/23/mbam-version-chart/ - states there is a May 2019 release now - https://support.microsoft.com/en-gb/help/4505175/may-2019-servicing-release-for-microsoft-desktop-optimization-pack

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 67626969-2854-3925-fc2d-9d8a09183796
* Version Independent ID: f442462e-6e55-406d-9a77-4e98e6dc036f
* Content: [Applying hotfixes on MBAM 2.5 SP1](https://docs.microsoft.com/en-us/microsoft-desktop-optimization-pack/mbam-v25/apply-hotfix-for-mbam-25-sp1)
* Content Source: [mdop/mbam-v25/apply-hotfix-for-mbam-25-sp1.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/master/mdop/mbam-v25/apply-hotfix-for-mbam-25-sp1.md)
* Product: **w10**
* Technology: **mdop**
* GitHub Login: @shortpatti
* Microsoft Alias: **pashort**

### PR DESCRIPTION
**Pull request by illfated**
**Description:**

- Microsoft Desktop Optimization Pack May 2019 Servicing Release.
- Replaces the outdated MDOP link to July 2018 Servicing Release.

<br>

**Notes:**

Thanks to @CaptainUnlikely for the Technet blogs information update.

<br>

**Github issue ticket reference or closure:**

Closes #4574

### CODE REVIEW

**Comment by e0i** [comment]
cc @jvsam

**Comment by illfated** [comment]
@lizap: Are you available for review and merge of this relevant update?

**Comment by jvsam** [comment]
HI @shortpatti and @Dansimp, this PR is ready for your review, please merge if there are no issues. It contains the [correct Desktop Optimization Pack link](https://github.com/MicrosoftDocs/windows-itpro-docs/pull/4592/files). Thank you.

**Comment by jvsam** [comment]
Thank you @Dansimp!

**Pull request merged**
