### PR TITLE
Add DISM command- Task 4610206

### PR DESCRIPTION
**Pull request by Alluthewriter**
As per the suggestion from PR (#8680) , I am creating this new branch to solve the issue of getting the DISM command under the MD Note blob. Hope this solves the issue (Take a look at the screenshot below). 
solved

### CODE REVIEW

**Review by illfated — APPROVED** [review]
Sure, let's go with this view. I want to edit the file later on anyway, to fix some formatting issues far from this PR content section. I approve of this current addition.

**Review by illfated — COMMENTED** [review]
- [X] **Normal source view:** https://github.com/MicrosoftDocs/windows-itpro-docs/pull/8700/files
- [X] **Rich diff view:** https://github.com/MicrosoftDocs/windows-itpro-docs/pull/8700/files?diff=unified&w=1&short_path=d86914a#diff-d86914a1852d8b6dce5c0e010552158c271495f73b42c5b47ff81a4574e8cb4d

**Comment by illfated** [comment]
#sign-off

**Comment by illfated** [comment]
@denisebmsft : Any further steps you want to include, before final review?

**Review by denisebmsft — APPROVED** [review]
Thank you @Alluthewriter and @illfated. Can you make the same changes to the McAfee guide and the general non-Microsoft guide as well? The two articles are this one: https://docs.microsoft.com/en-us/windows/security/threat-protection/microsoft-defender-atp/mcafee-to-microsoft-defender-setup 
and this one: https://docs.microsoft.com/en-us/windows/security/threat-protection/microsoft-defender-atp/switch-to-microsoft-defender-setup

**Comment by Alluthewriter** [comment]
> Thank you @Alluthewriter and @illfated. Can you make the same changes to the McAfee guide and the general non-Microsoft guide as well? The two articles are this one: https://docs.microsoft.com/en-us/windows/security/threat-protection/microsoft-defender-atp/mcafee-to-microsoft-defender-setup
> and this one: https://docs.microsoft.com/en-us/windows/security/threat-protection/microsoft-defender-atp/switch-to-microsoft-defender-setup

@denisebmsft made similar changes to the above two articles. Here's the PR:  #8727

**Pull request merged**
