### PR TITLE
Update hello-hybrid-cert-whfb-settings-pki.md

### PR DESCRIPTION
**Pull request by davguent**
Command line should contain spaces as delimiter not commas.

### CODE REVIEW

**Comment by illfated** [comment]
Please note that the current content with comma delimiters instead of spaces is based on issue ticket **Certutil command wrong #5089** (which in turn was based both on user experience and TechNet pages like https://social.technet.microsoft.com/Forums/windowsserver/en-US/847c13d5-a32e-4799-bb83-2f8ead98a069/certutil-quottoo-many-argumentsquot?forum=winserversecurity)

See also the follow-up PR **WHfB/certutil: Add command args comma separators #5119** resulting in commit https://github.com/MicrosoftDocs/windows-itpro-docs/commit/da0d757b733fa9b077bed5832779abbf7784c7a5

If you have got any documentation and/or test results to show that the comma delimiters are incorrect, I would appreciate seeing some of them, just to know which documentation to refer to if and when someone else suggests that commas are the correct delimiters again.

**Comment by davguent** [comment]
+Brian who just set this up end to end and was the requestor for documentation change.

@Brian<mailto:brian.mulford@microsoft.com> Can you comment below?

Dave Guenthner

**Comment by davguent** [comment]
Thanks for including me in the loop Dave. I successfully validated this command in 2 different labs ( windows 2016 and Windows 2019), and used the comma separated command to fix a live customer environment last week.

The original Pull Request references a Social TechNet thread related to a different function of Certutil -importPFX - not Certutil -dstemplate.   certutil -importpfx is NOT relevant for this documentation.


The goal of the certutil command in the article is to add the Hello Logon Key flag to the msPKI-Private-Key-Flag of the WHFBAuthentication template

Verification Steps:


  1.  Verify Current msPKI-Private-Key-Flags on WHFBAuthentication certificate template
     *   Run certutil -dsTemplate WHFBAuthentication msPKI-Private-Key-Flag
     *   Output does not display Hello Logon Key
[A screenshot of a computer screen  Description automatically generated]



  1.  Validate Comma separated command does not change msPKI-Private-Key-Flag
     *   Run command from current docs article : certutil -dsTemplate WHFBAuthentication,msPKI-Private-Key-Flag,+CTPRIVATEKEY_FLAG_HELLO_LOGON_KEY
     *   Output appears to show command ran successfully
[A screen shot of a computer  Description automatically generated]



     *   Verify Private Key Flag has not changed certutil -dsTemplate WHFBAuthentication msPKI-Private-Key-Flag (
[A close up of a screen  Description automatically generated]



  1.  Validate Comma separated command updates change msPKI-Private-Key-Flag
     *   Run command with spaces: certutil -dsTemplate WHFBAuthentication msPKI-Private-Key-Flag +CTPRIVATEKEY_FLAG_HELLO_LOGON_KEY
     *   Output ( Shows Old Value and New Value - highlighted Windows Hello Flag that is required for WHfB)
[A screenshot of a cell phone  Description automatically generated]


  1.  Verify Current msPKI-Private-Key-Flags on WHFBAuthentication certificate template
     *   Run certutil -dsTemplate WHFBAuthentication msPKI-Private-Key-Flag
     *   Output correctly shows Hello Logon Key Flag
[A screen shot of a computer  Description automatically generated]


From: Dave Guenthner (PROPLUS-RANGER) <davguent@microsoft.com>
Sent: Monday, December 2, 2019 8:15 AM
To: MicrosoftDocs/windows-itpro-docs <reply@reply.github.com>; MicrosoftDocs/windows-itpro-docs <windows-itpro-docs@noreply.github.com>; Brian Mulford <brian.mulford@microsoft.com>
Cc: Author <author@noreply.github.com>
Subject: RE: [MicrosoftDocs/windows-itpro-docs] Update hello-hybrid-cert-whfb-settings-pki.md (#5544)

+Brian who just set this up end to end and was the requestor for documentation change.

@Brian<mailto:brian.mulford@microsoft.com> Can you comment below?

Dave Guenthner

**Comment by illfated** [comment]
OK, very well. I see you have researched this issue thoroughly, so I defer to your results and conclude that we will move forward with this Pull Request to have the command corrected accordingly.

**Comment by illfated** [comment]
(ref. #5532 (**certutil typo?**))

**Pull request merged**
