### PR TITLE
Potential Fix for What's new in Windows 10 link

### PR DESCRIPTION
**Pull request by computeronix**
The link for What's new in Windows 10 did not remove the md on the production side

adding a ./ as a potential fix but if you know of a different fix feel free to adjust too

### CODE REVIEW

**Comment by greg-lindsay** [comment]
The problem is not a ./ it is that someone added .md to the link. The link should just go to the filename without the extension.

**Comment by eross-msft** [comment]
@computeronix 
If you would like to make the suggested change in this pull request, I can merge it into the content.

**Comment by greg-lindsay** [comment]
I'm taking care of the baby. I'll not be able to make changes until this afternoon.

**Comment by eross-msft** [comment]
My request was for computeronix to make the change so that he can get credit for the update on the topic. There is nothing more required for you to do, Greg. Just enjoy baby-time :)

**Comment by computeronix** [comment]
This has been corrected as suggested  removed the . in the ./
Then removed .md

Thank you!

**Pull request merged**
