### PR TITLE
Data Management Service Endpoints: link correction

### LINKED ISSUE #4936: Doc bug in "Configure Windows diagnostic data in your organization" article
The article may have the wrong URL listed in the "ENDPOINTS" section:
https://docs.microsoft.com/en-us/windows/privacy/configure-windows-diagnostic-data-in-your-organization#endpoints

image

"Settings - win.data.microsoft.com" is mentioned 3 times in this section.
I believe it should be:
"Settings - settings-win.data.microsoft.com"

### PR DESCRIPTION
**Pull request by illfated**
**Description:**

As reported in issue ticket #4936, the link `win.data.microsoft.com` does not work as a an endpoint for diagnostic data services.
In contrast to this, the endpoint `settings-win.data.microsoft.com` works as intended.

Thanks to @amirsc3 for finding and reporting the incorrect links.

**Proposed changes:**
- add table outer limit markers
- correct 3 links by adding the missing prefix "settings-"
- replace hyphens with colon to separate descriptions and data
- add extra line breaks in the tables to separate different data
- add 1 missing MarkDown space in a Note further down

**issue ticket closure or reference:**

Resolves #4936

### CODE REVIEW

**Comment by illfated** [comment]
Rich Text Diff view, for easier overview of the changes:
https://github.com/MicrosoftDocs/windows-itpro-docs/pull/4991/files?short_path=4eb9c08#diff-4eb9c08057abcbe93b43f82a373c1825

**Comment by jvsam** [comment]
Hello @Dansimp and @DaniHalfin, if you have time, can you please review this PR? If you agree with the proposed changes, kindly approve and merge. Thank you.

**Comment by jvsam** [comment]
Hello again @Dansimp and @DaniHalfin, just following up regarding the status of this pull request. Please approve and merge if you find no issues with the proposed changes. Thank you so much.

**Comment by DaniHalfin** [comment]
@medgarmedgar - could you confirm this?
If Mike signs-off, we're good to go.

**Comment by jvsam** [comment]
Hello @medgarmedgar if time permits, kindly verify if the proposed changes are correct so @DaniHalfin  can approve this PR. Thank you so much for your assistance.

**Comment by medgarmedgar** [comment]
@Dani Halfin<mailto:Dani.Halfin@microsoft.com> I don’t own that article.

I’m having problems signing into GitHub, so I’m sending this email.

-Mike

**Comment by jvsam** [comment]
Thank you for the  update @medgarmedgar, much appreciated.

@DaniHalfin kindly advise on how to proceed. The author data is showing @Dansimp. 

*Meta data reference:* https://github.com/MicrosoftDocs/windows-itpro-docs/blob/master/windows/privacy/configure-windows-diagnostic-data-in-your-organization.md

**Comment by illfated** [comment]
Just in case there is any difference, here is the link to the same document in the public branch:
https://github.com/MicrosoftDocs/windows-itpro-docs/blob/public/windows/privacy/configure-windows-diagnostic-data-in-your-organization.md

(not sure if there is any difference, but the [`public`](https://github.com/MicrosoftDocs/windows-itpro-docs/tree/public) branch gets updated sooner than the [`master`](https://github.com/MicrosoftDocs/windows-itpro-docs/tree/master) branch these days (since the change about 2 months ago).

**Comment by jvsam** [comment]
Hi again @Dansimp and @DaniHalfin, kindly advise on the status of this PR. Thank you.

**Comment by DaniHalfin** [comment]
Still waiting on final confirmation. Should have an update next week.

**Comment by illfated** [comment]
Thank you for your reply. I was worried that this content might not be agreeable and that this PR should be closed.

**Comment by jvsam** [comment]
Hi @DaniHalfin, also assigning this to you. FYI. Thanks.

@officedocsbot assign @DaniHalfin

**Comment by jvsam** [comment]
Hi @DaniHalfin, just a friendly follow-up. Do you have any update on this issue? Thank you.

**Comment by illfated** [comment]
I would also like to point out, as discussed in issue https://github.com/MicrosoftDocs/windows-itpro-docs/issues/4936 , that the validity of this PR change can be verified by any end user familiar with looking up host names/URLs on the internet and verifying their existence.

**Comment by jvsam** [comment]
Hi @DaniHalfin, do you have any update for us? Thanks and regards.

**Comment by illfated** [comment]
Looking forward to feedback regarding this content and if it will be considered useful before next year (2020).

**Comment by DaniHalfin** [comment]
Thanks, @illfated - sorry it took so long to merge.

**Comment by illfated** [comment]
Fair enough. I am glad you found time to verify & merge it now, at least. Thank you. 👍

**Pull request merged**
