### PR TITLE
Microsoft Defender for Endpoint: Linux GA support

### LINKED ISSUE #8818: Potential Out of Date information
On the docs page it states that Linux is not supported but planned.

Based on - https://techcommunity.microsoft.com/t5/microsoft-defender-for-endpoint/microsoft-defender-atp-for-linux-is-now-generally-available/ba-p/1482344

It would seem that it is now GA supported on Linux, if this is correct can this be updated to reflect?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e907ba50-a076-6fe7-d3ea-87fdbce5ed1b
* Version Independent ID: dbb7073e-e7d3-83f4-22ea-698134062cb2
* Content: [Supported operating systems and platforms for threat and vulnerability management - Windows security](https://docs.microsoft.com/en-us/windows/security/threat-protection/microsoft-defender-atp/tvm-supported-os)
* Content Source: [windows/security/threat-protection/microsoft-defender-atp/tvm-supported-os.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/public/windows/security/threat-protection/microsoft-defender-atp/tvm-supported-os.md)
* Product: **w10**
* GitHub Login: @levinec
* Microsoft Alias: **ellevin**

### PR DESCRIPTION
**Pull request by illfated**
**Description:**

Reported in issue ticket #8818 (**Potential Out of Date information**):

> On the docs page it states that Linux is not supported but planned.
>
> Based on - https://techcommunity.microsoft.com/t5/microsoft-defender-for-endpoint/microsoft-defender-atp-for-linux-is-now-generally-available/ba-p/1482344
>
> It would seem that it is now GA supported on Linux, if this is correct can this be updated to reflect?

Thanks to @paflaher for reporting this support document issue.

This is correct. Linux Server is supported (not yet on Desktop, but that is planned).

On the off chance that the following is correct, that Linux is supported the same way as Mac OS (both are UNIX-based OS), I propose to duplicate the MacOS support information.

Please review and inform me of any required changes, particularly when it comes to actually supported areas in the **Security assessment support** column.

**Changes proposed:**

- replace "Not supported (planned)" for Linux with the same information as in the MacOS row above
- add the list of supported Linux distributions (distros)
- add description "(only the following listed distros)"

**Whitespace changes:**

- add editorial blank line between metadata and page title
- add missing MarkDown indent marker compatibility spacing (3x)
- adjust and expand MD table to adhere to common MarkDown guidelines

**Ticket closure or reference:**

Closes #8818

### CODE REVIEW

**Comment by illfated** [comment]
Thanks also to @konstruktoid for preliminary support while preparing to write this PR.

**Review by illfated — COMMENTED** [review]
- [x] **Normal source view:** https://github.com/MicrosoftDocs/windows-itpro-docs/pull/8820/files
- [x] **Hide whitespace changes:** https://github.com/MicrosoftDocs/windows-itpro-docs/pull/8820/files?diff=unified&w=1
- [x] **Rich Diff view:** https://github.com/MicrosoftDocs/windows-itpro-docs/pull/8820/files?diff=unified&w=1&short_path=4764062

**Comment by konstruktoid** [comment]
LGTM.

**Comment by illfated** [comment]
#sign-off

**Comment by levinec** [comment]
The supported systems and platforms for threat and vulnerability management are different from the minimum requirements for Microsoft Defender for Endpoint list (as stated in the note in the documentation). Even though TVM is part of MDE, it currently does not support Linux.

**Comment by illfated** [comment]
I see. So the current table is correct, then. We may as well close the referenced ticket with the same message as above.

**Comment by levinec** [comment]
Done :)

**Comment by illfated** [comment]
Thanks. I noticed.

**Pull request closed without merging**
