### PR TITLE
Fix typo in whats-new-windows-10-version-20H2.md

### PR DESCRIPTION
**Pull request by pianofab**

### CODE REVIEW

**Review by illfated — APPROVED** [review]
Slightly funny typo, looks like an invalid plural form of "police". Good correction. Thank you.

**Comment by STO123456789** [comment]
I had contacted more legal assistance to Pursue legal action I have all docs and sites where you are distributing my content and files even servers and up addresses used I will pursue to the full extent of the law and I’m also seeking punitive damages for Defamation of character as well as support since she wouldn’t allow me to work while I was live with her

**Comment by STO123456789** [comment]
I had contacted more legal assistance to Pursue legal action I have all docs and sites where you are distributing my content and files even servers and up addresses used I will pursue to the full extent of the law and I’m also seeking punitive damages for Defamation of character as well as support since she wouldn’t allow me to work while I was live with her

**Comment by STO123456789** [comment]
I’m also going after her for all the time I spent in jail your community as well. Enjoy your days they’re numbered my attorney Phillip a. Is actively working on it now I also contacted I iccc and fbi for Internet crimes division I will not stand by and allow her nor you to do this any longer

**Comment by STO123456789** [comment]
Removing it won’t help I’ve already documented enough to prove my case

**Pull request merged**
