### PR TITLE
chore: Replace "syntax" with  code fence language

### PR DESCRIPTION
**Pull request by nschonni**

### CODE REVIEW

**Comment by e0i** [comment]
@Justinha @lizap @mjcaparas

Would you be able to review and merge this PR that addresses various Markdown improvements? Thanks.

**Comment by illfated** [comment]
@nschonni : I am pondering if we contributors should start looking for pages in need of "pretty print" XML alignment in some of the XML samples, or whether we just wait for feedback from other users before spending any time looking for XML samples in need of XML alignment. Would you happen to have any thoughts on that?

**Comment by nschonni** [comment]
@illfated no particular opinion. I just find the correct language syntax highlighting can sometimes help point out issues with samples. The pretty-print can be helpful because then the examples don't have much/any horizontal scroll

**Comment by e0i** [comment]
@AndreaBarr The community contributed PR that has gotten approval via _mjcaparas can be merged. Thanks.

**Comment by MamaDoc** [comment]
Thank You

**Pull request merged**
