### PR TITLE
Solution to issue #4076

### PR DESCRIPTION
**Pull request by j0rt3g4**
Fixing the note to integrate the taskbar configuration and how to do it. solution #4076

### CODE REVIEW

**Comment by mypil** [comment]
@nenonix @JohanFreelancer9 - kindly do the copy editor review for this PR. Thanks.

**Comment by mypil** [comment]
@ManikaDhiman - PR has been copy edited and is ready for final review. This is based on issue #4076.

Thank you.

**Comment by ManikaDhiman** [comment]
@j0rt3g4 I don't understand how the fix in this PR is the solution to customer issue #4076. Am I missing something here?

**Comment by j0rt3g4** [comment]
Yes,
The link on the article basically says how they can customize the issue, I just make it more evident with the rephrase of the line where the article is listed. The taskbar customization is done by modifying your "win10 image on the Test Computer" mentioned in the article, so if you modify the taskbar there, it will be saved into your image.

**Comment by ManikaDhiman** [comment]
Could you mention the line# where you rephrased the sentence?

**Comment by illfated** [comment]
To be continued in #4273 (**Taskbar customization**).

**Pull request closed without merging**
