### PR TITLE
added reference to www.microsoft.com

### PR DESCRIPTION
**Pull request by MaratMussabekov**
#5899, replacement of #6331

### CODE REVIEW

**Comment by MaratMussabekov** [comment]
Dear @e0i,
for your information.
Thank you

**Comment by illfated** [comment]
In case you find that the **rich diff** will not render for the source view in "Files changed", you can view the edited file result here instead:
- https://github.com/MicrosoftDocs/windows-itpro-docs/blob/85771d9f4f7acb59449f5e88c3a074410239072a/windows/privacy/manage-windows-1903-endpoints.md

Looks good to me, only the essential required changes are incorporated here: 1 inserted table row, 1 missing sentence ending completed.

**Comment by illfated** [comment]
@DaniHalfin : if you look back at the previous attempt at modifying this page, Mike Edgar commented on the version history for the rejected changes, whereas Daniel Simpson handled the final closure.

Perhaps I have overlooked something, that you are looking for a different topic expert for the current changes?

**Comment by DaniHalfin** [comment]
There has been some turnover on our end, so just need the current owner to approve this.

**Comment by e0i** [comment]
> There has been some turnover on our end, so just need the current owner to approve this.

@DaniHalfin Please let us know of the new owner if they also own the topic group so then I'll update the metadata for articles accordingly. Thank you.

**Comment by e0i** [comment]
@DaniHalfin Can you share who the new owner for this article is? We would like to follow-up with the owner and update metadata accordingly. Thank you, and stay healthy.

**Pull request merged**
