### PR TITLE
HoloLens: move Deploy link to Quick reference

### LINKED ISSUE #5065: Cleanly separate user from IT docs
The upper topics (guides) are primarily user focused, and the bottom ones are more IT and deployment focused.  Perhaps move the "Deploy HoloLens in a commercial environment" to the lower section for a clean divide.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: bb70c2a8-dcb0-2425-8d72-da180d05c2e1
* Version Independent ID: 7504c800-b203-0d18-9049-98005dd9a8b5
* Content: [Microsoft HoloLens (HoloLens)](https://docs.microsoft.com/en-us/HOLOLENS/)
* Content Source: [devices/hololens/index.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/public/devices/hololens/index.md)
* Product: **hololens**
* Technology: **windows**
* GitHub Login: @scooley
* Microsoft Alias: **scooley**

### PR DESCRIPTION
**Pull request by illfated**
**Description:**

As suggested in issue ticket #5065 (Cleanly separate user from IT docs), the link for "Deploy HoloLens in a commercial environment" should be moved from the Guides section to the Quick reference section.

Thanks to Microsoft internal Graham Bury (@grbury) for the suggestion.

**Proposed change:**
- move the Deploy link to the Quick reference section

**issue ticket closure or reference:**

Closes #5065

### CODE REVIEW

**Comment by jvsam** [comment]
Thanks for creating this PR @illfated 

Hi @scooley, kindly review the proposed changes and if there are no issues, please approve and merge. Thank you so much.

**Comment by jvsam** [comment]
Hello again @scooley, if you have time, kindly review this pull request. Thank you.

**Comment by jvsam** [comment]
Hello again @scooley, any update on this PR? If there are issues with it, please let us know. Thanks.

**Comment by jvsam** [comment]
@officedocsbot assign @jvsam

**Comment by scooley** [comment]
Looks good to me!

**Comment by illfated** [comment]
Glad to hear that. Do you have merge access, or do we need assistance from one of the managers?
(in case you don't have access, feel free to use the **[Approve]** and **[Submit review]** feature under **[Review changes]** in the [Files changed](https://github.com/MicrosoftDocs/windows-itpro-docs/pull/5118/files) section)

**Comment by jvsam** [comment]
Thanks @scooley. As suggested by @illfated, can you please approve and merge this PR if you have the access?

**Comment by jvsam** [comment]
@illfated if you have time, can you please resolve the merge conflict?

**Comment by illfated** [comment]
I tried to merge the [`MicrosoftDocs:public`](https://github.com/MicrosoftDocs/windows-itpro-docs/tree/public) branch into my PR branch, but the changes made in commit https://github.com/MicrosoftDocs/windows-itpro-docs/commit/06d13c5ce9dc2620542cccdc8fa31b77fe500d65 are plenty and diverse, making it counter-productive for me to add back a link text which has already been removed (see the `index.md` part of the commit: https://github.com/MicrosoftDocs/windows-itpro-docs/commit/06d13c5ce9dc2620542cccdc8fa31b77fe500d65#diff-47f9f9dcc7890300eee02b26b9c80471).

From what I can tell by the external changes, this PR no longer fits its original purpose, which was to resolve issue ticket #5065 by simplifying the categories of the page https://docs.microsoft.com/en-us/HOLOLENS/ (**Microsoft HoloLens**). I will therefore close this PR and recommend that we ask the ticket author to open a new ticket if the current content needs additional improvements. I would have to close this PR and make a new one anyway, so I prefer to start from a ticket where the suggestion or request for a change is based on the current content instead of the outdated version of the document.

I hope this is OK with you. Feel free to suggest a different approach, if you can discover any obvious improvements in need of implementation.

**Pull request closed without merging**
