### PR TITLE
Update whats-new-windows-10-version-1809.md

### PR DESCRIPTION
**Pull request by RavennMSFT**
Updated the status of web sign in

### CODE REVIEW

**Comment by illfated** [comment]
Maybe my suggestion is too cosmetic for you, but I would like to see the MD Note sections (3+1) updated to include the MD indent marker compatibility spacing (1 space between the indent marker & its following text). Would you be OK with that?

Example:
```diff
- >[!IMPORTANT]
- >This is a private preview feature and therefore not meant or recommended for production purposes.

+ > [!IMPORTANT]
+ > This is a private preview feature and therefore not meant or recommended for production purposes.
```

**Comment by RavennMSFT** [comment]
> Maybe my suggestion is too cosmetic for you, but I would like to see the MD Note sections (3+1) updated to include the MD indent marker compatibility spacing (1 space between the indent marker & its following text). Would you be OK with that?
> 
> Example:
> 
> ```diff
> - >[!IMPORTANT]
> - >This is a private preview feature and therefore not meant or recommended for production purposes.
> 
> + > [!IMPORTANT]
> + > This is a private preview feature and therefore not meant or recommended for production purposes.
> ```

Seems too cosmetic. We need this info out soon

**Comment by illfated** [comment]
OK, fair enough. I concur, the factual change is more important than compatibility spacing.

**Comment by illfated** [comment]
#sign-off

**Pull request merged**
