### PR TITLE
Update basic-permissions.md

### LINKED ISSUE #8864: typo
For more information, see Assign administrator and non-administrator roles to uses with Azure Active Directory.
(near the bottom of the page)

uses should read users

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: cb427fd5-e30d-101e-7905-544f9eb5081e
* Version Independent ID: bf829c27-33f5-b9b5-7923-9dd47dd10657
* Content: [Use basic permissions to access Microsoft Defender Security Center - Windows security](https://docs.microsoft.com/en-us/windows/security/threat-protection/microsoft-defender-atp/basic-permissions)
* Content Source: [windows/security/threat-protection/microsoft-defender-atp/basic-permissions.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/public/windows/security/threat-protection/microsoft-defender-atp/basic-permissions.md)
* Product: **w10**
* GitHub Login: @mjcaparas
* Microsoft Alias: **macapara**

### PR DESCRIPTION
**Pull request by illfated**
**Description:**
From issue ticket #8864 (**typo**):

> For more information, see Assign administrator and non-administrator roles to uses with Azure Active Directory.
> (near the bottom of the page)
>
> uses should read users

Thanks to @andrePKI for pointing out the typo.

This seemingly simple typo correction escalated somewhat into a format improvement and link update to replace outdated MSDN and TechNet links with current MS Docs links. You want to verify if the new links are the proper ones for this source page, or request the links either to be reverted back to the old ones, in case there is specific information in the old documents not present in the new documents, or suggest more correct links to replace the old ones.

**Proposed changes:**
- typo correction, "uses" -> users
- typo correction: remove 2 commas from "see, Add, or remove group memberships"
- Connect-MsolService: replace the old MSDN URL with a new one pointing to its current PowerShell docs page
    - old URL: https://msdn.microsoft.com/library/dn194123.aspx
    - new URL: https://docs.microsoft.com/powershell/module/msonline/connect-msolservice
- "Add, or remove group memberships" link text replaced with "Add or remove group members using Azure Active Directory" (document title)
    - old URL: https://technet.microsoft.com/library/321d532e-407d-4e29-a00a-8afbe23008dd#BKMK_ManageGroups (anchor link jump broken by redirection)
    - new URL: https://docs.microsoft.com/azure/active-directory/fundamentals/active-directory-users-assign-role-azure-portal

The TechNet link change proposal is particularly disputable, since it now points to an Azure AD GUI management page instead of a PowerShell cmdlets page. We may want to find a PowerShell cmdlet document page instead (I am uncertain at this point).

**Whitespace & formatting changes:**
- remove redundant end-of-line blanks (2 occurrences)
- add editorial blank line after MarkDown H2 and H3 headings (4 occurrences)
- MD syntax highlighting phrase "text" corrected to "PowerShell" (MD code blocks containing PS cmdlets)
- reduce double blank spacing in bullet point list to single space (1 occurrence)
- add MD indent marker compatibility spacing (1 occurrence)

**Ticket closure or reference:**
Closes #8864

### CODE REVIEW

**Review by illfated — COMMENTED** [review]
- [X] **Hide whitespace changes:** https://github.com/MicrosoftDocs/windows-itpro-docs/pull/8865/files?diff=unified&w=1 (useful to focus review on the effective changes)

**Comment by illfated** [comment]
#sign-off (for now)

**Comment by e0i** [comment]
cc @JohanFreelancer9

**Review by JohanFreelancer9 — APPROVED** [review]

**Comment by mjcaparas** [comment]
pls resolve conflicts

**Comment by illfated** [comment]
> pls resolve conflicts

Sure, will do.

**Comment by illfated** [comment]
Merged the link update from PR #8804 (**Link update**), commit https://github.com/MicrosoftDocs/windows-itpro-docs/commit/197da8e66ca54ec8e2b07d0352e9fa33c4c63305 .

**Comment by illfated** [comment]
#sign-off

**Pull request merged**
