### PR TITLE
Update deploy-enterprise-licenses.md

### PR DESCRIPTION
**Pull request by ancamartin2000**
We are getting a lot of calls generated in Support because the customers use slmgr /dli or slmgr /dlv to pull the license information when they use E3/E5 activation and get the default Windows 10 Pro key which for them is a problem and think that the client has been downgraded from Ent to Pro. We need this information public until slmgr /dli or /dlv will be able to pull the E3/E5 information so we avoid more calls being generated.

### CODE REVIEW

**Comment by mypil** [comment]
@nenonix @JohanFreelancer9 - kindly do the copy editor review for this PR. Thanks.

**Comment by JohanFreelancer9** [comment]
No edits

**Comment by mypil** [comment]
@greg-lindsay - Can you please assist to check, approve and merge the content for this PR? 

Thank you.

**Comment by mypil** [comment]
@ancamartin2000 - I just tagged the doc owner greg-lindsay to review your PR and get his assistance to merge the content. Thank you.

**Comment by WK-MS** [comment]
@mypil -- Thank you for the quick response!

**Pull request merged**
