### PR TITLE
Update hello-hybrid-key-whfb-settings-pki.md

### PR DESCRIPTION
**Pull request by AlexLafargue**
The note regarding NTAuth certificate store is invalid. It states that you must add the DC certificate in the store. It should have stated to add the issuing CA certificate in the store. +Added a link to certutil command

### CODE REVIEW

**Comment by illfated** [comment]
@AlexLafargue : Just in case your content change gets accepted by the document author, would it be OK to ask you to add a MarkDown compatibility space after the quote markers ( `>` ) ?

**Comment by illfated** [comment]
This PR has been approved by the doc author, but it needs follow-up from the DM/PM for the final merge process.

**Comment by e0i** [comment]
@Dansimp The PR that has been approved by document owner can be merged. Thanks.

**Comment by Dansimp** [comment]
Fixed in https://github.com/MicrosoftDocs/windows-itpro-docs/pull/5389

**Comment by illfated** [comment]
@AlexLafargue : The change suggested in this PR is still not part of the documentation.
If you are certain that this content is correct, you will want to open a new PR containing the exact same changes.

**Pull request closed without merging**
