### PR TITLE
Update docs with the newer MDOP version (May 2019)

### PR DESCRIPTION
**Pull request by andreiztm**

### CODE REVIEW

**Comment by illfated** [comment]
Please note: The URL you are suggesting to add to this page (https://support.microsoft.com/help/4505175/may-2019-servicing-release-for-microsoft-desktop-optimization-pack) seems to contain a broken link to the download page for the MDOP package for 2019. The URL https://www.microsoft.com/downloads/details.aspx?FamilyId=2afccd89-6f66-4396-a5a4-7819d37bbe01 gives me "**404 - File or directory not found.**" all the time, at least during the last hour. Not sure if the link will be revived anytime soon.

Functional link to the download page: https://www.microsoft.com/download/details.aspx?id=58345

**Comment by andreiztm** [comment]
@illfated thank you for noticing that, will put in a separate request to update the KB itself. This PR is good as is.

**Comment by illfated** [comment]
Sounds good to me. Thank you for your informative reply. 👍

**Comment by simonxjx** [comment]
The link in 4505175 is updated. Thanks.

**Comment by andreiztm** [comment]
@simonxjx thank you very much.  :D

**Comment by andreiztm** [comment]
ty

**Pull request merged**
