### PR TITLE
Update update-compliance-feature-update-status.md

### PR DESCRIPTION
**Pull request by mesharma-msft**
1. Changed the term "compatibility hold" to "safeguard hold" since this is the terminology we are going to use going forward as approved by the Comms team.
2. Added the "Queries for Safeguard holds" section. Unable to upload the UC_workspace_safeguard_queries.png file in images folder, so will email the image to Jaime to upload.

### CODE REVIEW

**Comment by e0i** [comment]
@JohanFreelancer9 Copy editing is needed for this PR. Thanks.

**Comment by e0i** [comment]
@mesharma-msft Would you be able to resolve the merge conflicts? We'd like to have this content reviewed for a merge afterward. Thank you.

**Comment by mesharma-msft** [comment]
Resolved conflict. @e0i Can you please review?

**Comment by mesharma-msft** [comment]
@e0i Hey Onur, if all looks good, can we please merge this PR now?

**Pull request merged**
