### PR TITLE
Migrate two topics from Portico

### PR DESCRIPTION
**Pull request by daleche-sh**
This is for testing whether I can submit a PR, markdown files are from Amanda Zhu (Shanghai Wicresoft Co,.Ltd.). Ramu Konidena will talk with the Repos owner for this RP.

### CODE REVIEW

**Comment by illfated** [comment]
There is some information related to this PR, worth noticing for later when you want to create an actual PR to the public branch:

https://github.com/daleche-sh/windows-itpro-docs/tree/red-branch
This branch is 7 commits ahead, 3297 commits behind MicrosoftDocs:public.

https://github.com/daleche-sh/windows-itpro-docs
This branch is even with MicrosoftDocs:public.

**Comment by ramakoni1** [comment]
@MightyPen - can you please check this PR and see if we have the right repo identified for the browser articles (these are not migrated from KB, but nevertheless are good candidates for test runs - these are created with the help of CSS SMEs). Please comment on what else is needed to get these published and added to TOC. These are top call volume generators on CSS side.

**Comment by MightyPen** [comment]
@ramakoni1 @daleche-sh 

1. With `ms.topic: troubleshooting`, these KB articles (quasi-KB?) would need to be in a high-level GitHub directory named `troubleshooting/`.

2. Dale would have to edit the relevant toc.yml file himself, as part of the PR, before the PR could be merged.

3. This PR should also @ notify the writer who is repo-rep for this repository, and @ notify me (which you did).  For this repo, I believe that Daniel Simpson = @Dansimp is the repo-rep (or he may delegate).

4. The metadata name `appliesto` might not be acceptable to use.  Megan Bradley has not yet responded to my email asking her for clarification.  I'll re-ping Megan.

5. Metadata name `audience` also seems suspect.  Please use only metadata names you see as explicitly valid, in the Contributors' Guide (or Localization Guide etc).  And only use what you truly need, and avoid overuse of marginal metadata names that are unnecessary of vague nice-to-haves.

6. `ms.custom` values with embedded blanks might be problematic?  Can values like `CI 111020` instead be `CI-111020`?

7. Please do not allow a blank line to exist between the end of the metadata section (`---`) and the `#` H1 title header.  Some LINT checkers consider the blank line to be an error.

8. In file `browsers/clear-ie-cache-from-command-line.md`, line 106 ` echo 2. ...` is oddly indented by one space.  Unless there is a reason the space is needed, can those spaces be removed. Those unneeded spaces cause an unpleasant visual mis-alignment of the code lines.

9. It is unsettling that this public repo, `windows-itpro-docs`, has no OPS Build.  If there is a repo named `windows-itpro-docs-pr` (with the suffix `-pr`), that would be the proper private repo to use, not this public repo.
   -  I am confused here, because [https://ops.microsoft.com](https://ops.microsoft.com) portal does not even know about this public repo??

10. Contributors' Guide article `contribute\code-in-docs.md` does not list `bat` as being a valid Language Specifier for "Fenced code blocks".  _The CSS writers must check the C.Guide before putting any value for a Lang Spec._  Neither I nor the writer repo-reps can fully check this type of detail for correctness.
   - Consider using the valid Lang Spec `console`.  However, I agree that `bat` should be a colorizer and available to use - it just isn't.
   - The guides are at:  [https://review.docs.microsoft.com/en-us/help/contribute/?branch=master](https://review.docs.microsoft.com/en-us/help/contribute/?branch=master)

Thanks.  MightyPen (= GeneMi) , 2020/Jan/10

**Comment by illfated** [comment]
I presume you are well familiar with Github Flavored Markdown, just mentioning the source file for languages known by GFM, in case it is useful to you.
- https://github.com/github/linguist/blob/master/lib/linguist/languages.yml

**Pull request closed without merging**
