### PR TITLE
HoloLens TOC update

### PR DESCRIPTION
**Pull request by scooley**
Grouping pages into logical units for better readability.

### CODE REVIEW

**Comment by e0i** [comment]
@Justinha @DaniHalfin @mjcaparas Would you kindly be able to review this PR concerning TOC changes? Thank you.

**Comment by DaniHalfin** [comment]
@scooley  is a PM in the category, so I would definitely trust her changes :)

**Comment by scooley** [comment]
Thank you both :D - please let me know if there's a better way to interface with you folks.  I'm going to be doing a ton of work here in to update for HL2 and would love to work closely with doc team.

**Comment by DaniHalfin** [comment]
@scooley - ping me on Teams. We've been talking about Hololens publishing internally for a while, so I have some thoughts :)

**Pull request merged**
