### PR TITLE
Deployment/Update: standardize double quote marks

### LINKED ISSUE #6241: Curly quotes in PowerShell script prevent it from working
The PowerShell script as posted here will note work. Somewhere along the way some of the double quote marks became "curly quotes". To correct this, all open and closing curly quotes (these are two different items) need to be changed to straight quotes. After making that change the script will function.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c7734ca5-0770-5bbd-7da5-dda4c1cf5ae0
* Version Independent ID: cb98ef23-d0c6-e62e-b72b-9b5f5d724e8e
* Content: [Update Windows 10 media with Dynamic Update - Windows Deployment](https://docs.microsoft.com/en-us/windows/deployment/update/media-dynamic-update#feedback)
* Content Source: [windows/deployment/update/media-dynamic-update.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/public/windows/deployment/update/media-dynamic-update.md)
* Product: **w10**
* Technology: **windows**
* GitHub Login: @SteveDiAcetis
* Microsoft Alias: **jaimeo**

### PR DESCRIPTION
**Pull request by illfated**
**Description:**

As reported in issue ticket #6241 (**Curly quotes in PowerShell script prevent it from working**), this page contains curly double quote marks in its PowerShell scripts and cmdlets. These incorrectly inserted characters within code snippets (or maybe they were incorrectly re-coded some time ago) prevent the code snippets from being read correctly by PowerShell. This PR aims to resolve this issue.

Thanks to @hsehestedt for reporting this issue.

**Changes proposed:**
- Replace incorrect curly quote marks with straight ones
- Add "PowerShell" as MarkDown syntax highlight identifiers
- Remove redundant end-of-line blanks throughout the document

**Ticket closure or reference:**

Closes #6241

### CODE REVIEW

**Comment by illfated** [comment]
#sign-off

**Comment by illfated** [comment]
(Ref. PR #6275 for the same file, with only the curly quotes changed.)

**Comment by jaimeo** [comment]
@illfated I'm going to go with #6275 b/c that PR is from the SME for the topic--he specifically did not want the PowerShell identifier for the code block b/c it was rendering strangely (we should probably file a bug on that). That's why we went with the plain generic rendering.

**Comment by illfated** [comment]
OK, fair enough.

**Pull request closed without merging**
