### PR TITLE
Added Information About Gamebar

### PR DESCRIPTION
**Pull request by rahulkumarsingh73690**

### CODE REVIEW

**Comment by e0i** [comment]
@dansimp Would you be able to review this PR that is contributed by the community? Thanks.

**Comment by e0i** [comment]
@Dansimp Any updates with the PR? Thanks.

**Comment by illfated** [comment]
I would like to recommend complete dismissal for this PR, based on the fact that the suggested link is neither a Microsoft page nor a Microsoft affiliate page.

As a matter of fact, the PR author is trying to use this PR for self promotion of one of his personal pages, which will never be accepted by Microsoft.

**Comment by e0i** [comment]
Closing the PR due to valid points raised by the community.

**Comment by e0i** [comment]
@officedocsbot close

**Pull request closed without merging**
