### PR TITLE
Update index.md

### PR DESCRIPTION
**Pull request by mmahler86**
The current documentation isn't clear that hybrid joined devices aren't supported with web sign-in

## Why

- Closes #[Issue Number]

### CODE REVIEW

**Comment by paolomatarazzo** [comment]
The article clearly states in the first paragraph : "Microsoft Entra joined devices"

**Comment by mmahler86** [comment]
Paolo,

Well, it's not clear to customers since the customer worked on this for a while and then opened a support ticket.  I ran this by with SR TA Paul Townsend who agreed the document doesn't clearly state hybrid joined devices aren't supported.  Additionally, public docs don't say anything about the web sign-in provider not being visible for hybrid joined devices.  Thank you for considering the update.

- Mike

Mike Mahler
***@***.******@***.***>
Azure Identity Support Engineer
Customer Services and Support
Office: +1 980 776-7185
Working Hours:
Mon-Fri 09:00-18:00 EST


[8AAC27E6]
Alternate Contacts if I am unavailable
Technical Advisor Shawn Gray +1 (469) 7754718
Backup Engineer Ademola Adedeji ***@***.******@***.***>
Backup Engineer Lindsay Conkle ***@***.******@***.***>
Team Manager | Brad Held +1 (512) 795-5798

UPCOMING OOF: 10/31, 11/10, 11/20 - 11/22, 12/27 - 12/29

**Comment by paolomatarazzo** [comment]
Alright, I'll take a look on Monday and add a prerequisite section then. Thank you for the feedback

**Comment by paolomatarazzo** [comment]
Sorry on mobile now. Are you saying that even the current prerequisites section is not clear?

To use web sign-in, the clients must meet the following prerequisites:

Windows 11, version 22H2 with 5030310, or later
Must be Microsoft Entra joined
Must have Internet connectivity, as the authentication is done over the Internet

**Comment by mmahler86** [comment]
Paolo,

For customers, a hybrid joined device is entra id joined so something that makes it very clear that a hybrid joined device is not supported.  I fully understand that hybrid isn't supported, but I think this could prevent some support cases going forward.  I am starting to see an uptick on web sign in cases for Identity and for this case and customer, something that specifically called out hybrid joined as not being supported would have prevented a support case and a lot of effort on the customers part.  Our internal wiki calls this out, but public docs do not.

- Mike

Mike Mahler
***@***.******@***.***>
Azure Identity Support Engineer
Customer Services and Support
Office: +1 980 776-7185
Working Hours:
Mon-Fri 09:00-18:00 EST


[8AAC27E6]
Alternate Contacts if I am unavailable
Technical Advisor Shawn Gray +1 (469) 7754718
Backup Engineer Ademola Adedeji ***@***.******@***.***>
Backup Engineer Lindsay Conkle ***@***.******@***.***>
Team Manager | Brad Held +1 (512) 795-5798

UPCOMING OOF: 10/31, 11/10, 11/20 - 11/22, 12/27 - 12/29

**Comment by paolomatarazzo** [comment]
Thanks for clarifying, I'll add a note in the prerequisites then to make it clearer.

**Comment by mmahler86** [comment]
Paolo,

Thank you for the change.  I appreciate your assistance in making the change.

- Mike

Mike Mahler
***@***.******@***.***>
Azure Identity Support Engineer
Customer Services and Support
Office: +1 980 776-7185
Working Hours:
Mon-Fri 09:00-18:00 EST


[8AAC27E6]
Alternate Contacts if I am unavailable
Technical Advisor Shawn Gray +1 (469) 7754718
Backup Engineer Ademola Adedeji ***@***.******@***.***>
Backup Engineer Lindsay Conkle ***@***.******@***.***>
Team Manager | Brad Held +1 (512) 795-5798

UPCOMING OOF: 10/31, 11/10, 11/20 - 11/22, 12/27 - 12/29

**Comment by mmahler86** [comment]
Paolo,

Thank you for updating the public docs.  Much appreciated.

[A screenshot of a computer error  Description automatically generated]

Mike Mahler
***@***.******@***.***>
Azure Identity Support Engineer
Customer Services and Support
Office: +1 980 776-7185
Working Hours:
Mon-Fri 09:00-18:00 EST


[8AAC27E6]
Alternate Contacts if I am unavailable
Technical Advisor Shawn Gray +1 (469) 7754718
Backup Engineer Ademola Adedeji ***@***.******@***.***>
Backup Engineer Lindsay Conkle ***@***.******@***.***>
Team Manager | Brad Held +1 (512) 795-5798

UPCOMING OOF: 10/31, 11/10, 11/20 - 11/22, 12/27 - 12/29

**Pull request closed without merging**
