### PR TITLE
Added second row of names in white

### PR DESCRIPTION
**Pull request by get-itips**
to support Dark mode. https://github.com/MicrosoftDocs/windows-itpro-docs/issues/655

### CODE REVIEW

**Comment by mypil** [comment]
@mtniehaus - can you please assist to check, approve and merge the content for this PR based on issue #655?

Thank you.

**Comment by mtniehaus** [comment]
I assume the change was to make the image non-transparent?  Looks fine to me, but I'm not using dark mode.

**Comment by get-itips** [comment]
@mtniehaus Hi Michael, not really, but achieve the same goal, I added the text in a white version that will only show up when enabling dark mode.

**Comment by illfated** [comment]
Thank you for this solution to the issue in #655 . 👍

**Pull request merged**
