### PR TITLE
Correcting typo

### PR DESCRIPTION
**Pull request by andreiztm**

### CODE REVIEW

**Comment by jdeckerms** [comment]
@andreiztm I'm looking at the file and don't see any difference between the original sentence and your version. What is the change you're making?

**Comment by andreiztm** [comment]
@jdeckerms I've added just an enter before the list, because the first URL would jump up and near the : sign and it was not that visible :).

You may choose to apply a rule to permit HTTP RANGE requests for the following URLs:

*.download.windowsupdate.com  
*.dl.delivery.mp.microsoft.com  
*.emdl.ws.microsoft.com

**Comment by jdeckerms** [comment]
@andreiztm aha, thanks! Looked right at it and couldn't see it. :)

**Comment by andreiztm** [comment]
@andreiztm Don't blame ya :) Thank you!

**Comment by andreiztm** [comment]
Fastest merge in the west! :D

**Comment by illfated** [comment]
Even so, faster merges than this can happen: https://github.com/MicrosoftDocs/windows-itpro-docs/pull/2894

**Comment by jdeckerms** [comment]
@andreiztm Your fixes (this one and https://github.com/MicrosoftDocs/windows-itpro-docs/pull/2884/files) got lost in some build issues that we had yesterday but I'm restoring the changes so they should go live today. Thanks!

**Pull request merged**
