### PR TITLE
Update manage-packaged-apps-with-applocker.md

### PR DESCRIPTION
**Pull request by baardhermansen**
Updated Notes markdown.
Updates links to web pages.

### CODE REVIEW

**Comment by e0i** [comment]
@dansimp The PR that introduces a clarifying note to the document is available for review. Thanks.

**Comment by baardhermansen** [comment]
@Dansimp Sorry, but shouldn't the merge have been done into the publich branch, not master?

**Comment by illfated** [comment]
@baardhermansen : Your PR was created with the `master` branch as the target for merging. If you find that the `public` branch is the correct one to target, you need to set the `public` branch  as your main branch in your own repository before creating a new PR, or edit the PR after it has been created, to change the target from `master` to the `public` branch. Even so, it will still be synchronized with the `public` branch at a later stage (within a few days), and later on it will migrate to the docs.microsoft.com site. We simply need to be patient, that is all. ⏳ 😉

**Comment by baardhermansen** [comment]
@illfated Ah, i see the error of my ways! Dammit, the culprit is still the guy behind this very keyboard... :P

**Pull request merged**
