### PR TITLE
Update event-4776.md

### PR DESCRIPTION
**Pull request by rathbuna**
Change lowercase c to uppercase C in line with other error codes.

### CODE REVIEW

**Review by JohanFreelancer9 — APPROVED** [review]
Copy review.

**Review by denisebmsft — APPROVED** [review]
Thank you @rathbuna

**Comment by denisebmsft** [comment]
@rathbuna Please don't forget to sign the Contributor License Agreement. We can't merge your pull request until that is done. Thank you!

**Comment by rathbuna** [comment]
Done!

**Pull request merged**
