### PR TITLE
Added question to General section about IoT support

### PR DESCRIPTION
**Pull request by brentkendall**
I accidentally made some edits to the other questions as well, but you can disregard those as I only changed spacing that doesn't actually show-up on the page.  The important change is the last question/answer I added around IoT support.

### CODE REVIEW

**Comment by e0i** [comment]
@greg-lindsay @Justinha Would you be able to merge this PR created by a MS contributor? Thanks.

**Comment by e0i** [comment]
@lizap Would you be able to merge this PR created by a MS contributor? Thanks.
Merge state

**Comment by e0i** [comment]
@lizap Any updates?

**Comment by greg-lindsay** [comment]
There's a conflict here, I never seem to be able to resolve these using the resolve button.  So, I'll add the file edits manually to my private branch and push them there, and close this PR.

**Pull request closed without merging**
