### PR TITLE
Update wufb-reports-admin-center-permissions.md

### PR DESCRIPTION
**Pull request by msbemba**
Made changes to the permissions needed 

Reference - MC397469 

fixes #https://github.com/MicrosoftDocs/windows-itpro-docs/issues/10757

### CODE REVIEW

**Comment by msbemba** [comment]
@JohanFreelancer9 Please copy review

**Comment by msbemba** [comment]
@yogkumgit The author is mstewart

**Review by JohanFreelancer9 — APPROVED** [review]

**Comment by yogkumgit** [comment]
@mestew Kindly update. Thanks

**Comment by mestew** [comment]
This edit is not correct. The target doc is only for the **Windows** tab within the **Software Updates** page in the admin center. For instance, the Azure AD role of **Office Apps Administrator** wouldn't have access to the **Windows** tab without one of the other roles such as *Windows updates deployment administrator** being assinged to the user as well.  Same thing for the other roles that were added such as Exchange Admin.

**Pull request closed without merging**
