### PR TITLE
fixed typo in line 65

### LINKED ISSUE #5742: typo
Press and for hold 5s  =&gt;  Press and hold for 5s

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: aa9cc734-aea5-0908-39a0-ebe924a6ae74
* Version Independent ID: 0f900a81-0196-e3f1-d64b-2cd8aaf45c1e
* Content: [Prepare a new HoloLens 2](https://docs.microsoft.com/en-us/hololens/hololens2-setup#feedback)
* Content Source: [devices/hololens/hololens2-setup.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/public/devices/hololens/hololens2-setup.md)
* Product: **hololens**
* Technology: **windows**
* GitHub Login: @scooley
* Microsoft Alias: **scooley**

### PR DESCRIPTION
**Pull request by mypil**
Resolves #5742

### CODE REVIEW

**Comment by mypil** [comment]
@scooley - PR is ready for final review based on issue #5742. This is just a typo issue. 

Thank you.

cc: @kenwith

**Comment by scooley** [comment]
Lgtm!

**Comment by mypil** [comment]
@scooley - would you be able to help merge this PR? 

Thank you.

**Comment by mypil** [comment]
@Dansimp - Can you possibly assist to merge this PR? This is just a simple typo issue and has been approved by @scooley.

Thank you.

**Comment by illfated** [comment]
Judging by the black tick mark (not green) in scooley's approval line, it appears that she might not have merging rights for this repository or part of it. This is in comparison to my ordinary user approval, it is also black, whereas any of the MS Docs managers with merging rights can be seen to have green tick marks in their approval event lines.

**Pull request merged**
