### PR TITLE
Windows Update resources: add MD code block

### PR DESCRIPTION
**Pull request by illfated**
**Description:**

The list of manual regsvr32.exe commands becomes translated in other languages, to the extent that extra words appear among the commands.
This is an attempt to mitigate this behavior in the machine translation, by adding a MarkDown code block around the list of commands.

**Proposed changes:**
- Add MD code block around the long list of regsvr32.exe commands
- Remove blank space characters at the end of each line (cosmetic)

**issue ticket reference or closure:**

Ref. #4800 (Spanish "translation" of commands)
Ref. #3569, #3570, #3571, #3572, #3574, #3575 ( [LOC] Back-Translation "regsvr32.exe [...]" )

**Additional note:**
Apologies in advance for adding more to the regular diff view than anticipated.
I thought I had only removed blank space characters after the code block I had selected.
Turns out that I cleaned up all trailing space for the entire file. Hope this still is OK.

### CODE REVIEW

**Comment by illfated** [comment]
For easier overview of the effective changes, see the Rich Text Diff:
https://github.com/MicrosoftDocs/windows-itpro-docs/pull/4812/files?short_path=e31aa55#diff-e31aa55e77816943ac0f5a51e2eb78aa

**Comment by e0i** [comment]
@illfated This is smart.

**Comment by illfated** [comment]
@greg-lindsay or @LauraWi : I don't know which one of you will have time to review this PR first, but if you find that this content has got too much change to be easy enough to review within your limited time, feel free to request a new PR containing only the list of `regsvr32.exe` commands in a code block without any of the extra MarkDown fix-up material.

**Comment by e0i** [comment]
@illfated Thank you for this smart hack that will possibly close many issues. Much appreciated.

**Comment by e0i** [comment]
@greg-lindsay The PR wraps certain commands within Markdown code blocks to avoid them interpreted literally by ML software, and will possibly close many associated issues. Please review as the time permits. Thanks.

**Comment by e0i** [comment]
@greg-lindsay Following up for updates. Thanks.

**Comment by LauraWi** [comment]
Adding @Greg Lindsay<mailto:Greg.Lindsay@microsoft.com>

**Pull request merged**
