### PR TITLE
Update feature-update-mission-critical.md

### PR DESCRIPTION
**Pull request by MaratMussabekov**
issue #2128

### CODE REVIEW

**Comment by MamaDoc** [comment]
Hi, Janet here.  I have been having issues with a hacker, over a month now.  They got all my personal info exposed everything on social media.   They have accessed all my PC’s.  The request using android phone and Mac computer.  Had to purchase another desktop.  I do not understand why this is not getting repaired.  They are running so much data through my phone my carrier is questioning what is going on.  I am loosing accounts deleting my google accounts also changing passwords on the accounts & deleted important files & data.  What do I have to do to get this resolved?   I cannot afford replacing any more devices.  Also my online presence has been defrauded & reputation is in question?  Please help tp resolve this matter.  Thank You

**Comment by mypil** [comment]
@nenonix @JohanFreelancer9 - kindly do the copy editor review for this PR. Thanks.

**Comment by mypil** [comment]
@greg-lindsay - Can you please assist to check, approve and merge the content of this PR based on issue #2128?

Thank you.

**Comment by mypil** [comment]
@greg-lindsay - We would like to follow up on this. Can you please assist to check, approve and merge the content of this PR based on issue #2128?

Thank you.

**Pull request merged**
