### PR TITLE
update net-framework-problems-with-ie11.md

### PR DESCRIPTION
**Pull request by MaratMussabekov**
issue #3246 
correcting registry path info

### CODE REVIEW

**Comment by mypil** [comment]
@shortpatti - Can you please assist to check, approve and merge the content for this PR based on issue #3246?

Thank you.

**Comment by mypil** [comment]
@lizap - there's another article found by @MaratMussabekov that needs to be updated with this information. Here's the article link- [Managed hosting controls are disabled in Internet Explorer from the .NET Framework 4](https://support.microsoft.com/en-us/help/2996039/managed-hosting-controls-are-disabled-in-internet-explorer-from-the-ne) . However, we discovered that this article is on support.office.com which is a different system and not GitHub based. Do you happen to know how we can update the support.office.com (SOC) article?

Thank you!

cc: @mypil @kenwith

**Comment by mypil** [comment]
@lizap - I would like to follow up with you. Can you share your thoughts on how we can update this support.office.com (SOC) article - [Managed hosting controls are disabled in Internet Explorer from the .NET Framework 4](https://support.microsoft.com/en-us/help/2996039/managed-hosting-controls-are-disabled-in-internet-explorer-from-the-ne)? Or do you know who we can reach out to get this fixed?

Thank you.

**Comment by illfated** [comment]
For what it's worth: I posted info about this PR and linked this page in the feedback feature "Did this solve your problem? [Yes] [No]" -- I clicked "No" and posted the link to this page and asked for this information to be considered used to update https://support.microsoft.com/en-us/help/2996039/managed-hosting-controls-are-disabled-in-internet-explorer-from-the-ne . I was logged in on my MS account while doing this (not my Github account).

**Comment by mypil** [comment]
@illfated - We appreciate your help. :smiley:

**Comment by mypil** [comment]
@illfated - Did you get any updates or any response after you posted info about this PR and linked this page in the feedback feature?

**Comment by illfated** [comment]
Thank you for asking, but unfortunately no luck so far. No replies yet.

**Comment by mypil** [comment]
@kenwith - No luck in finding out how we can edit the SOC article. Hope you can help in finding out who we can reach out to update the SOC article. Thank you.

**Pull request merged**
