### PR TITLE
added key path ,  made words in bold

### PR DESCRIPTION
**Pull request by RAJU2529**
as per the user report #8028 , so i modified this article by adding certain words, added key paths.

### CODE REVIEW

**Comment by illfated** [comment]
cc: @cinglis-msft (ref. comment https://github.com/MicrosoftDocs/windows-itpro-docs/issues/8028#issuecomment-672080756)

**Comment by cinglis-msft** [comment]
Looks good, thank you.

**Comment by illfated** [comment]
#sign-off

**Comment by RAJU2529** [comment]
@e0i , From yesterday night onwards i could not able to create post information in the discussions thread,  on **answers.microsoft.com**
 whenever i try to post, I am getting below error message.
**Oops! Something went wrong. Please try again**
error

Will you inform the error message to forum admin, solve this problem?

**Comment by illfated** [comment]
@RAJU2529 : You want to empty the cache of your browser, maybe even deactivate some of your addons in the browser, to see if that solves your forum issue.

**Comment by RAJU2529** [comment]
@illfated , One of the forum moderator solved that problem, afterwards i successfully created thread.

**Comment by e0i** [comment]
@Kateyanne This PR can be merged as it has been approved by article authors. Thank you.

**Pull request merged**
