### PR TITLE
added clarification about value 1

### PR DESCRIPTION
**Pull request by VLG17**
https://github.com/MicrosoftDocs/windows-itpro-docs/issues/3028

### CODE REVIEW

**Comment by mypil** [comment]
@Justinha - Not sure if @MariciaAlforque is still the author of this article but would you be able to merge the content of this PR or do you happen to know who is the new owner? 

Thank you.

**Comment by Justinha** [comment]
Thanks everyone!

**Comment by mypil** [comment]
@Justinha - Are you the new article author for this article? Kindly confirm so I can create a PR to correct the metadata of this article. Thank you.

**Comment by Justinha** [comment]
@mypil Sorry I am not, new author is till TBD right now.

**Pull request merged**
