### PR TITLE
Minor updates to "manage-connections-from-windows-operating-system-components-to-microsoft-services.md"

### PR DESCRIPTION
**Pull request by ChhornGLim**

### CODE REVIEW

**Comment by illfated** [comment]
Ref. closed PR #3723

**Comment by e0i** [comment]
@DaniHalfin Would you review and merge this PR based on one of your articles? The fixes address a few spelling errors.

**Comment by illfated** [comment]
@ChhornGLim : Are you able to rebase your PR branch on current master, or perform a merge from master to your PR branch?
Or would you like some help in form of a PR from me to your own repository PR branch?

**Comment by ChhornGLim** [comment]
@illfated - I was able to merge/rebase current master into my PR branch.

**Comment by e0i** [comment]
@DaniHalfin Would you review and merge this PR based on one of your articles? The fixes address a few spelling errors.

**Comment by e0i** [comment]
@medgarmedgar 

Would you be able to review and merge this PR that addresses a few spelling errors? Thank you.

**Comment by medgarmedgar** [comment]
Approved.

**Comment by e0i** [comment]
@AndreaBarr This PR that has been contributed by community has been approved and can now be merged. Thanks.

**Pull request merged**
