### PR TITLE
Command Update

### PR DESCRIPTION
**Pull request by joinimran**
There was an issue with the command arguments. Made adjustments in the command. 

Problem: https://github.com/MicrosoftDocs/windows-itpro-docs/issues/8721

### CODE REVIEW

**Review by illfated — APPROVED** [review]
Looks good to me. Tested and found to be correct by reporting ticket author @bencze1 .

**Comment by illfated** [comment]
#sign-off

**Comment by illfated** [comment]
Sorry, I was too quick to call this PR ready for final review. I found that all the vertical pipe characters used as logic 'or' between the parameter options are interpreted as cell dividers instead of being part of the text. Please review & merge my PR https://github.com/joinimran/windows-itpro-docs/pull/2  to this PR.

**Comment by joinimran** [comment]
@JohanFreelancer9 - kindly do the copy editor review for this PR. Thanks.

**Comment by illfated** [comment]
Thank you for adding my PR content. I almost worried you would suggest making those changes in a separate PR, and I would not blame you for saying so. 😉

**Review by illfated — APPROVED** [review]
- [X] **Rich Diff view:** https://github.com/MicrosoftDocs/windows-itpro-docs/pull/8797/files?short_path=f312cde#diff-f312cdea73274edbb322eb6c0978c908a54747ddecce1fa6f3fcb1b4a73e5192 (for easier visual view of the table improvements)

Looks quite good from my point of view.

**Review by JohanFreelancer9 — APPROVED** [review]

**Comment by illfated** [comment]
Fair point. @joinimran : Would you mind editing your main PR comment to change "Problem: #8721" => Closes #8721

**Comment by nam31** [comment]
@Dansimp PR has been copyedited and is ready for final review, could you please check and merge? Thanks!

**Review by illfated — APPROVED** [review]
Cool. Looks good to me.

**Pull request merged**
