### PR TITLE
 changed  the background to GOLD color

### PR DESCRIPTION
**Pull request by RAJU2529**
as per user report #5810 , changed  the background to GOLD color

### CODE REVIEW

**Comment by shivtorov** [comment]
there are no reasons to use any custom colors for table elements in this article.
all custom formatting should be removed.

**Comment by illfated** [comment]
According to https://www.color-hex.com/color/ffd700 , white text on gold is not a very good combination.

Have you considered removing the color codes entirely?

**Comment by RAJU2529** [comment]
I considered only background colour for the titles

**Comment by illfated** [comment]
You need to consider the foreground color too, because the original issue premise is that the table title row is currently of a light blue color. This color works OK with black text (Light theme), but if you switch to the Dark theme, the text becomes white (https://www.color-hex.com/color/ffffff) on a black background. If the text is white, there is a need for a darker color to make the white text more readable without straining your eyes (especially for older people and people who need glasses or lenses).

Using a darker background color can cause the original text in the Light theme to become less readable, so there is not any really good background color for both a black text and white text scenario.

See also the following Stack Exchange user experience topic:
https://ux.stackexchange.com/questions/73763/background-colour-suitable-for-both-black-and-white-text
The following answer is particularly of interest:
https://ux.stackexchange.com/questions/73763/background-colour-suitable-for-both-black-and-white-text/80339#80339

**Comment by RAJU2529** [comment]
@illfated. ok sir

**Comment by illfated** [comment]
You might also be interested in my attempt to resolve this type of issue by removing the colors based on the ticket #5819 and my rejected PR #5823 .

As you can see, there is now a file conflict due to the commit https://github.com/MicrosoftDocs/windows-itpro-docs/commit/5c2657d4bbd895119f0638fee2ffc2b6103cb844 (specifically the file https://github.com/MicrosoftDocs/windows-itpro-docs/commit/5c2657d4bbd895119f0638fee2ffc2b6103cb844#diff-fd341c319c5e228c1da26f7301855856 (`windows/deployment/windows-autopilot/add-devices.md`)), but the document author @greg-lindsay has not changed the color scheme for the table addressed in this PR, only added a `<br>` tag above the table. I don't know yet if this PR will be addressed by the author, so we will have to wait and see.

As a reference, this is the document metadata header:
```MarkDown
---
title: Adding devices
ms.reviewer: 
manager: laurawi
description: How to add devices to Windows Autopilot
keywords: mdm, setup, windows, windows 10, oobe, manage, deploy, autopilot, ztd, zero-touch, partner, msfb, intune
ms.prod: w10
ms.mktglfcycl: deploy
ms.localizationpriority: medium
ms.sitesec: library
ms.pagetype: deploy
audience: itpro
author: greg-lindsay
ms.author: greglin
ms.collection: M365-modern-desktop
ms.topic: article
---
```

**Comment by RAJU2529** [comment]
@illfated . I commented on that page #5819

**Comment by illfated** [comment]
Yes, that is OK. I simply mentioned those pages for reference.

**Comment by RAJU2529** [comment]
@illfated . How do I resolve the conflicting files

**Comment by illfated** [comment]
https://help.github.com/en/github/collaborating-with-issues-and-pull-requests/resolving-a-merge-conflict-on-github

image

... and so on. If you need more, please visit [the Help page](https://help.github.com/en/github/collaborating-with-issues-and-pull-requests/resolving-a-merge-conflict-on-github) and start from point 3 (as shown in the image).

**Comment by RAJU2529** [comment]
@illfated . Thanks  for the  help.
changed  font color to  #00008b and  background color to #fdd700.

**Comment by illfated** [comment]
OK, that is an interesting combination.
https://www.colorhexa.com/fdd700 as BGCOLOR
https://www.colorhexa.com/00008b as font color

So basically dark blue on gold (or as seen in https://www.htmlcsscolor.com/hex/FDD700 with black text).

Very well, let us wait and see what the document author (Greg Lindsay) thinks of this suggestion.

**Comment by e0i** [comment]
A quote from the document author from the associated issue, for the audience,

> I will test some colors and see what I can do to make the table appear better in dark theme.

https://github.com/MicrosoftDocs/windows-itpro-docs/issues/5810#issuecomment-573139009

**Comment by illfated** [comment]
Yes, I noticed. Looking forward to the subsequent results and feedback.

**Comment by Dansimp** [comment]
Typically we don't change the default colors in our docs, both from a branding perspective, but also an accessibility perspective. Some people need high contrast views and when we change colors, it might affect their experience. I'll connect with Greg on this and let you know what we decide. Thank you.

**Comment by RAJU2529** [comment]
@Danisimp.Thanks sir for replying. We will wait for the decision.

**Comment by illfated** [comment]
Just a thought, based on what has been discussed before:
If you have decided that you want to keep the current fixed BGCOLOR value (light blue), 
maybe it would be a good idea to set a fixed font color as well, 
to make it unaffected by the Dark theme CSS and the High contrast CSS?

**Comment by greg-lindsay** [comment]
This topic is already fixed.  There is no longer an issue with the display in dark theme.

**Pull request closed without merging**
