### PR TITLE
GPO update

### PR DESCRIPTION
**Pull request by NagaCSC**
- update about [Interactive logon Do not require CTRL+ALT+DEL (Windows 10) - Windows security | Microsoft Docs ]

### CODE REVIEW

**Review by NagaCSC — COMMENTED** [review]
updated

**Comment by paolomatarazzo** [comment]
Hello @NagaCSC , thank you for the feedback. I'm not entirely sure I understand your point. Once WHFB is provisioned, it becomes the default credential provider. If you have a biometric-capable device, you will use biometric as primary method for WHFB, with fall back to PIN in case of issues. The password would be a last-resort option, and you would need to explicitly select the password provider to log in with a password. I would argue that it's harder to spoof than CTRL-ALT-DELETE. Besides, if you change your provider to password, at the next login it will default again to WHFB. Can you please clarify your statement to ensure I didn't miss anything?

**Comment by NagaCSC** [comment]
updated again, please review

**Comment by paolomatarazzo** [comment]
Closing this PR. After reviewing latest recommendations and security baselines, we should not recommend enabling CAD to begin with.

**Pull request closed without merging**
