### PR TITLE
replaced word  TCM to TPM

### PR DESCRIPTION
**Pull request by RAJU2529**
as per the user report #8187 , so i replaced  TCM to TPM.

### CODE REVIEW

**Review by illfated — APPROVED** [review]
Looks good to me.

**Comment by Teresa-Motiv** [comment]
#sign-off
Can someone assign this to someone who can merge it?

**Comment by illfated** [comment]
@denisebmsft : The PR has been signed off by the document author, but the author does not have merging rights. Could you do the honors, or assign someone with merging rights?

**Comment by e0i** [comment]
@Kateyanne Can you merge this PR that has been approved by its article owner? Thank you.

**Pull request merged**
