### PR TITLE
WDDG & WDCG HW readiness tool: typo & Arch Locale

### LINKED ISSUE #6574: WDDG & WDCG hardware readiness tool: typo & locale issues
As discussed in ticket #5972 (even if that ticket is closed), the script on this page stops working in localized versions of Windows (Dutch mentioned in ticket #5972 specifically). This is caused by the difference in how the strings `64-bit` and `32-bit` occur in non-English localized versions of Windows.

The suggestion in ticket #5972 is to add some regex functionality inside `function CheckOSArchitecture`, like this:

```PowerShell
function CheckOSArchitecture
{
    $OSArch = $(gwmi win32_operatingsystem).OSArchitecture.ToLower()
    Log $OSArch 
    if($OSArch -match ("64\-?\s?bits?"))
    {
        LogAndConsoleSuccess "64 bit archictecture"
    }
    elseif($OSArch -match ("32\-?\s?bits?"))
    {
        LogAndConsoleError "32 bit  archictecture"   
        $DGVerifyCrit.AppendLine("32 Bit OS, OS Architecture failure.") | Out-Null
    }
    else
    {
        LogAndConsoleError "Unknown architecture"
        $DGVerifyCrit.AppendLine("Unknown OS, OS Architecture failure.") | Out-Null
    }
}
```

The word "archictecture" is also misspelled, twice in that function, luckily only in text strings used for logging.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c12e9c4a-af05-9ecd-a791-ac89aa43787c
* Version Independent ID: 76517523-a960-c5fb-ce76-2c3efe642f37
* Content: [Windows Defender Device Guard and Windows Defender Credential Guard hardware readiness tool - Microsoft 365 Security](https://docs.microsoft.com/en-us/windows/security/identity-protection/credential-guard/dg-readiness-tool)
* Content Source: [windows/security/identity-protection/credential-guard/dg-readiness-tool.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/public/windows/security/identity-protection/credential-guard/dg-readiness-tool.md)
* Product: **w10**
* Technology: **windows**
* GitHub Login: @SteveSyfuhs
* Microsoft Alias: **stsyfuhs**

### PR DESCRIPTION
**Pull request by illfated**
**Description:**

As pointed out in ticket #5972 (closed) and #6574 (my ticket), the script on this page stops working in localized versions of Windows (Dutch mentioned in ticket #5972 specifically). This is caused by the difference in how the strings "64-bit" and "32-bit" occur in non-English localized versions of Windows.

Thanks to @RvdHout (Ruud van den Hout) for suggesting the regex solution.

**Changes proposed:**
- `$OSArch.Contains("64-bit")` replaced with `$OSArch -match ("64\-?\s?bits?")`
- `$OSArch.Contains("32-bit")` replaced with `$OSArch -match ("32\-?\s?bits?")`
- Readiness Tool Version updated to 3.7.2 (thanks to RvdHout)
- Typo "archictecture" corrected to **architecture** (2 occurrences)
- Readability: initial PowerShell comment lines (2) expanded for better sentence grammar
- Remove all redundant end-of-line (EOL) whitespace (blanks)
- Reduce number of blank lines before the signature block, from 3 to 2
- Add back a blank line between the metadata section and the page title
- Add a blank line for readability between the top 2 PS comment lines and the code

**Ticket closure and references:**

Closes #6574

Ref. #5690 #5723 #6054 #6055
Ref. #5972 & #4679 (both closed)

### CODE REVIEW

**Comment by illfated** [comment]
Everyone involved in the linked tickets are invited to comment or suggest improvements in this PR.

**Comment by illfated** [comment]
#sign-off

**Comment by RvdHout** [comment]
```
function CheckOSArchitecture
{
    $OSArch = $(gwmi win32_operatingsystem).OSArchitecture.ToLower()
    Log $OSArch 
    if($OSArch -match ("^64\-?\s?bit"))
    {
        LogAndConsoleSuccess "64 bit archictecture"
    }
    elseif($OSArch -match ("^32\-?\s?bit"))
    {
        LogAndConsoleError "32 bit  archictecture"   
        $DGVerifyCrit.AppendLine("32 Bit OS, OS Architecture failure.") | Out-Null
    }
    else
    {
        LogAndConsoleError "Unknown architecture"
        $DGVerifyCrit.AppendLine("Unknown OS, OS Architecture failure.") | Out-Null
    }
}
```
maybe regex can be simplified, leaving out the last optional "s" (\s?)

With above modification it will accept at least
64-Bit (German)
64-bit (English)
64 bits (Dutch)

The old regex works, but this one is 'cleaner'

**Comment by illfated** [comment]
👍 Thank you for the suggestion. I will have a look at it later and consider making that change in my PR source.

**Comment by illfated** [comment]
#sign-off

**Comment by e0i** [comment]
@Dansimp Would you review this PR that addresses an issue that has attracted much community attention? Thank you in advance, and stay healthy.

**Comment by illfated** [comment]
Added a commit to preserve the typo corrections in the abandoned PR #5916 .
Thanks to @schneiderl for discovering & reporting the typos in the first place.

**Comment by illfated** [comment]
#sign-off

**Pull request merged**
