### PR TITLE
Revert "Update enterprise-mode-schema-version-2-guidance.md"

### PR DESCRIPTION
**Pull request by e0i**
Reverts MicrosoftDocs/windows-itpro-docs#4248

via https://github.com/MicrosoftDocs/windows-itpro-docs/pull/4248#issuecomment-518015887

### CODE REVIEW

**Comment by AndreaBarr** [comment]
@andrefboliveira does this make the changes you requested?

**Comment by illfated** [comment]
> **No changes to show.**
> This commit has no content.

**Comment by illfated** [comment]
@e0i : Please close this PR. It is already resolved.

**Comment by e0i** [comment]
@illfated Thank you for your generous assistance. Much appreciated.

**Comment by e0i** [comment]
@officedocsbot close

**Comment by andrefboliveira** [comment]
Thank you.
Now we are back to the previous stage of validation through PM 
[#4248](https://github.com/MicrosoftDocs/windows-itpro-docs/pull/4248#issuecomment-506296166
)
Please check the info, and create a new PR with the correct info

**Pull request closed without merging**
