### PR TITLE
LocURI locator is denoted with [\]

### PR DESCRIPTION
**Pull request by kannanb-github**
The LocURI has to be denoted with [/] a wrong separate was used in the URI, the file has been changed with correct separator.

### CODE REVIEW

**Comment by kannanb-github** [comment]
The LocURI path modification requested.

**Comment by illfated** [comment]
#sign-off

**Comment by martyav** [comment]
@illfated I'm on Dan's team and am helping clean up the backlog, particularly on the easier to resolve PR's

**Comment by kannanb-github** [comment]
This PR closes the issue https://github.com/MicrosoftDocs/windows-itpro-docs/issues/6082

**Comment by e0i** [comment]
Closes #6293.

**Comment by HenkPoley** [comment]
Hmm, did you make a typo in the issue number?

**Pull request merged**
