### PR TITLE
Use existing AllowSampleCollection documentation

### PR DESCRIPTION
**Pull request by iadgovuser1**
Wasn't obvious AllowSampleCollection was being discussed in the list, so add more information about it and use existing info from https://docs.microsoft.com/en-us/windows/security/threat-protection/windows-defender-atp/configure-endpoints-script-windows-defender-advanced-threat-protection#configure-sample-collection-settings

### CODE REVIEW

**Comment by lizap** [comment]
Thanks for you contribution! Before we can merge your changes, we need you to sign the CLA permitting us to use your work. 

Assuming you're the same contributor from PR #1001, we've reviewed the issue you raised around government employees and the potential complications regarding copyright with our legal team. 
The CLA covers the situation where you are contributing in the course of your employment, regardless of who that employer is. We ask you to certify that you have permission from your employer to make these contributions. (Because the work that you're doing for the government is not to specifically contribute to this content, and because this CLA does address doing the work in the course of your regular employment, no other CLA is required.)

If your reading of the situation is different than ours, then as much as we appreciate your contribution, we're not able to use it. Thanks.

**Comment by iadgovuser1** [comment]
@lizap Sounds like there's an issue with section 9 of the CLA. Something about state law. Lawyers will figure it out.

**Comment by shortpatti** [comment]
@mjcaparas, can we close this PR?

**Comment by mjcaparas** [comment]
Ok, we can close PR.

**Pull request closed without merging**
