### PR TITLE
fix: formatting of the important notice

### PR DESCRIPTION
**Pull request by profnandaa**
This commit formats the "important" notice so that it looks consistently 
with the other documentations e.g. the "important" on this[1] page.

[1] https://docs.microsoft.com/en-us/windows-hardware/drivers/debugger/debugger-download-symbols

### CODE REVIEW

**Comment by profnandaa** [comment]
If this is okay, I can go ahead and do one PR for all the pages within the Application Compatibility Toolkit (ACT) since that's what I'm going through right now.

**Comment by e0i** [comment]
@greg-lindsay @AndreaBarr  The PR that introduces a formatting fix is available for review. Thanks.

**Comment by e0i** [comment]
@greg-lindsay @AndreaBarr Following up for updates.

**Comment by AndreaBarr** [comment]
@greg-lindsay please review for merging

**Comment by profnandaa** [comment]
Fixing the merge conflict.

**Comment by profnandaa** [comment]
Reopend a separate PR due to merge conflicts and CRLF related file issues that was spoiling the diff -> #4678

**Pull request closed without merging**
