### PR TITLE
Item is missing from proxy/firewall requirements

### PR DESCRIPTION
**Pull request by JesseEsquivel**
Should be the same as this link (missing *.azure-automation.net).  The *.azure-automation.net url is also called out and checked in the defender for endpoint connectivity analyzer.
https://docs.microsoft.com/en-us/azure/azure-monitor/platform/log-analytics-agent#firewall-requirements

### CODE REVIEW

**Review by illfated — APPROVED** [review]
- [X] **Normal source view:** https://github.com/MicrosoftDocs/windows-itpro-docs/pull/8615/files
- [X] **Rich Diff view:** https://github.com/MicrosoftDocs/windows-itpro-docs/pull/8615/files?short_path=a0aacae#diff-a0aacae960603f1b418d2eca650dbb71cc334faca036fbdf92160385f737a668

Looks good to me, according to the sources referenced in the main PR comment.

**Comment by illfated** [comment]
#sign-off

**Comment by illfated** [comment]
Target page link, for extra reference:
- https://docs.microsoft.com/en-us/windows/security/threat-protection/microsoft-defender-atp/configure-proxy-internet#microsoft-monitoring-agent-mma---proxy-and-firewall-requirements-for-older-versions-of-windows-client-or-windows-server

**Review by denisebmsft — APPROVED** [review]
Thank you @JesseEsquivel

**Pull request merged**
