### PR TITLE
resolves #2745

### LINKED ISSUE #2745: Certificate and Key mixup
I believe the following phrase should be changed. See the crossed out word and my suggested word in bold instead.

> When using a certificate, the on-premises environment can use Windows Server 2008 R2 and later domain controllers, which removes the Windows Server 2016 domain controller requirement. However, single-sign on using a ~~key~~ **certificate** requires additional infrastructure to issue a certificate when the user enrolls for Windows Hello for Business.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7aeacc06-dbfc-07d8-d181-41d08d89e04b
* Version Independent ID: 6f16be7a-f5b1-fbad-15a2-18a2bc1a0716
* Content: [Azure AD Join Single Sign-on Deployment Guides](https://docs.microsoft.com/en-us/windows/security/identity-protection/hello-for-business/hello-hybrid-aadj-sso)
* Content Source: [windows/security/identity-protection/hello-for-business/hello-hybrid-aadj-sso.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/master/windows/security/identity-protection/hello-for-business/hello-hybrid-aadj-sso.md)
* Product: **w10**
* GitHub Login: @MikeStephens-MS
* Microsoft Alias: **mstephen**

### PR DESCRIPTION
**Pull request by gvijaikumar9**
resolves #2745 certificate key mixup

### CODE REVIEW

**Comment by gvijaikumar9** [comment]
resolves #2745

**Comment by illfated** [comment]
You should decide which one of these Pull Requests you want to keep,
either #3025 or #3035 (from what I can see, they are identical).

**Comment by illfated** [comment]
Ref. https://github.com/MicrosoftDocs/windows-itpro-docs/pull/3035#issuecomment-475885612:
> Keep this one.

Very well. then you can close this one (you should be able to do it from the web page).

**Comment by gvijaikumar9** [comment]
I was waiting for document owner to close.

**Comment by illfated** [comment]
Not necessary here on Github. You are the owner of this Pull Request, so you are free to close it whenever you want to (just like you can close issues also if you started/opened them).

**Comment by mypil** [comment]
@gvijaikumar9 - please close this PR. We will just use the new PR you created for this issue. Thank you.

**Pull request closed without merging**
