### PR TITLE
Update volume-activation-management-tool.md

### PR DESCRIPTION
**Pull request by msbemba**
Updated the versions of OS and Office that is supported by VAMT

Reference -https://github.com/MicrosoftDocs/windows-itpro-docs/blob/public/windows/deployment/volume-activation/use-the-volume-activation-management-tool-client.md and  https://github.com/MicrosoftDocs/OfficeDocs-DeployOffice/blob/live/DeployOffice/vlactivation/tools-to-manage-volume-activation-of-office.md

Fixes #https://github.com/MicrosoftDocs/windows-itpro-docs/issues/10994

### CODE REVIEW

**Comment by msbemba** [comment]
@JohanFreelancer9 Please copy review

**Review by JohanFreelancer9 — APPROVED** [review]

**Comment by frankroj** [comment]
Instead of listing all of the currently supported OSes, I think it is better that we word to instead say "VAMT is designed to manage volume activation for **all currently** supported versions of Windows, Windows Server, and Office." This will mean that we do not have to touch the article in the future when versions of Windows and Office are introduced or go out of support. Verifying with PMs if they are ok with this change.

**Comment by yogkumgit** [comment]
@msbemba

**Comment by msbemba** [comment]
@frankroj  Great idea. I have made the changes per your suggestion.

Thanks
Sri

**Comment by frankroj** [comment]
PM agreed that this change is OK. Signing off and merging request.

**Comment by frankroj** [comment]
PM agreed that this change is OK. Signing off and merging request.

**Pull request merged**
