### PR TITLE
Md branch3247912

### PR DESCRIPTION
**Pull request by ManikaDhiman**
Hi Nick,

Could you please do a quick peer review of the new EnrollmentStatusTracking CSP doc? Also, please let me know if this link is good for requesting tech review.

Thanks,
Manika

### CODE REVIEW

**Comment by nickbrower** [comment]
Looks good to me, I would just include the link to the file they will be most interested in here:

https://github.com/MicrosoftDocs/windows-itpro-docs/blob/98924855f0f3f0a41ba56f9431b8bc2855244b89/windows/client-management/mdm/enrollmentstatustracking-csp.md

**Comment by ManikaDhiman** [comment]
Thanks Nick!

**Comment by illfated** [comment]
@ManikaDhiman : Did you close this PR by mistake? (I have done that myself more than once, usually because the [**Close and comment**] button is a lot easier to hit than the [**Comment**] button.)

**Comment by ManikaDhiman** [comment]
No, I wanted to close this PR.

Thanks,
Manika

**Pull request closed without merging**
