### PR TITLE
Update network-security-allow-pku2u-authentication-requests-to-this-c…

### PR DESCRIPTION
**Pull request by RavennMSFT**
…omputer-to-use-online-identities.md

updated the security considerations section as it does not take Azure AD joined devices into consideration, which are verified and authenticated by Azure AD

### CODE REVIEW

**Comment by illfated** [comment]
Out of curiosity, do we presume that "Azure AD" is universally understood to mean "Azure Active Directory" straight away, as not being possible to misunderstand in any way? I am just trying to remember if this is the case and that we don't need to expand the first appearance of "Azure AD" to "Azure Active Directory", mostly with regard to the Microsoft Style Guide.

**Comment by RavennMSFT** [comment]
@illfated - Azure AD is the marketing approved term for all documentation - https://docs.microsoft.com/en-us/azure/active-directory/fundamentals/active-directory-whatis

**Review by illfated — APPROVED** [review]
Very good. No further questions. Looks good to me.

**Review by JohanFreelancer9 — APPROVED** [review]

**Comment by RavennMSFT** [comment]
@JohanFreelancer9 , @illfated - any reason this is not merged yet?

**Comment by illfated** [comment]
@RavennMSFT : No reason on our side, it is likely just a matter of when @Dansimp has got time to merge it (or someone else on his behalf).

**Comment by illfated** [comment]
#sign-off

**Comment by RavennMSFT** [comment]
@Dansimp can you pls merge this, there's an unwarranted concern from customers due to the previous language in this article, so would like to see this published soon

**Pull request merged**
