### PR TITLE
update path

### PR DESCRIPTION
**Pull request by VLG17**
https://github.com/MicrosoftDocs/windows-itpro-docs/issues/5412

### CODE REVIEW

**Comment by mypil** [comment]
@medgarmedgar - PR is ready for final review based on issue #5412 

Thank you.

cc: @kenwith

**Comment by illfated** [comment]
Very good & fair point. The doc text even says "**(note: there is no Group Policy for this setting)**", so it is only reasonable to document that the registry part of the setting does not belong within the hive branch **`HKLM\Software\Policies\Microsoft\`** .

**Comment by medgarmedgar** [comment]
We are actually missing the Inking regkey in the article as well.  

1. These 2 regkeys need to be added to the article

RestrictImplicitTextCollection registry REG_DWORD setting in HKEY_CURRENT_USER\Software\Microsoft\InputPersonalization needs to be set 1 (one)

RestrictImplicitInkCollection registry REG_DWORD setting in HKEY_CURRENT_USER\Software\Microsoft\InputPersonalization needs to be set 1 (one) 

2. The downloadable script also needs to be updated to remove them from machine.txt and add them to user.txt

**Comment by mypil** [comment]
@VLG17 - please see the recommended addition from medgarmedgar. Please create a new PR and add in the information. Thank you.

**Pull request merged**
