### PR TITLE
Update HostedInstall for EnterpriseModernAppManagement CSP

### PR DESCRIPTION
**Pull request by dianmsft**
The value for deployment options are not listed.  There are also other parameters for install not listed for the HostedInstall command.

### CODE REVIEW

**Comment by Dansimp** [comment]
Do not merge until this is resolved: - ValidateDependencies="1" - (need to check with dev on the actual functionality)

**Comment by dianmsft** [comment]
Updated to add the proper description.

**Comment by illfated** [comment]
Odd behaviour in the Rich Text Diff view (https://github.com/MicrosoftDocs/windows-itpro-docs/pull/5483/files?short_path=8774026#diff-877402675b48cb174de44da8cec1e748) :
the PR content seems to skip all natural line breaks (ordinary NewLine), making the added text section a continuous text section. I do not know if this is the actual behaviour when migrated to docs.microsoft.com , but it looks quite impractical at the moment (if the Rich Text Diff view can be trusted).

**Comment by illfated** [comment]
Very good, thanks for inserting the bullet point list. 
That resolved the issue of contiguous text without line breaks.

**Pull request merged**
