### PR TITLE
Updated new ownership to robsize

### PR DESCRIPTION
**Pull request by linque1**
Updated new ownership to robsize

### CODE REVIEW

**Comment by illfated** [comment]
From what I see in the PR, only the date is updated. I presume this is a follow-up to the changes between 7/7/2020 and now?

File commit history:
- https://github.com/MicrosoftDocs/windows-itpro-docs/commits/public/windows/privacy/manage-connections-from-windows-operating-system-components-to-microsoft-services.md

**Comment by linque1** [comment]
> From what I see in the PR, only the date is updated. I presume this is a follow-up to the changes between 7/7/2020 and now?
> 
> File commit history:
> 
> * https://github.com/MicrosoftDocs/windows-itpro-docs/commits/public/windows/privacy/manage-connections-from-windows-operating-system-components-to-microsoft-services.md

Somehow I edited the wrong file, but yes the msauthor was the intended update. Updating all Privacy docs ownership to robsize

**Comment by linque1** [comment]
#sign-off

**Comment by illfated** [comment]
Very good. Now I'm with you. Minor detail: it seems you managed to add 1 or 2 blank spaces after the date field. Not important, only cosmetic. Would you like to edit that, or would you like me to add an inline suggestion comment (to be merged) for removal of those blanks? Or would you prefer to leave it as is?

**Comment by linque1** [comment]
> Very good. Now I'm with you. Minor detail: it seems you managed to add 1 or 2 blank spaces after the date field. Not important, only cosmetic. Would you like to edit that, or would you like me to add an inline suggestion comment (to be merged) for removal of those blanks? Or would you prefer to leave it as is, for now?

Thanks for pointing that out. I just made the edit.

**Review by illfated — APPROVED** [review]
Very good. I concur.

**Comment by illfated** [comment]
#sign-off

**Pull request merged**
