### PR TITLE
Update use-windows-event-forwarding-to-assist-in-intrusion-detection.…

### PR DESCRIPTION
**Pull request by MaratMussabekov**
issue #1071
Removed reference to the supported OS, as it makes no sense (WEF could be used for any current Window OS and Windwos Server OS)

### CODE REVIEW

**Comment by mypil** [comment]
@tedhardyMSFT - can you please assist to check, approve and merge the content for this PR based on issue #1071?

Thank you.

**Comment by MaratMussabekov** [comment]
Hello @Justinha ,
As far as I understand, this feature works not only for Windows 10 and Windows Server 2016, but also for all OS that supports WinRM, that's why I think that "Applies to" shouldn't be used here.
What do you think?

Thank you

**Comment by egallagh** [comment]
If it does ally to the other versions of Windows then they should also be listed in the applies to section instead of removing the applies to section. This would create a positive affirmation of its relevance.

**Comment by illfated** [comment]
I concur, much better to confirm in which versions of Windows it actually works, than not saying anything about which versions are relevant.

**Comment by MaratMussabekov** [comment]
Dear @egallagh , @illfated ,
Don't you think that "Aplies to" should be for the features that works for some OS, but doesn't work for others?
As this feature works for ALL OS (at least since Windows Vista and Windows Server 2008), should we specify all OS there? What do you think?
Thank you

**Comment by illfated** [comment]
Well, you sort of have got a point there. Speaking for myself, I would (more often than not) expect from a Microsoft page to state in which OS **versions** the documented program or software package is supported (or is expected to work). If the versions are not listed, I would expect that the documented software would be available in _all_ versions of Windows (or the software environment in question).

I could very well be mistaken, so I refer to the Microsoft Docs team members for verification and proper feedback.

**Comment by MaratMussabekov** [comment]
Dear @Justinha , added Windows Server, as you recommended, could you please have a look?

Thank you

**Comment by Justinha** [comment]
@MaratMussabekov Thanks for the addition!

**Pull request merged**
