### PR TITLE
changed GPO reference

### PR DESCRIPTION
**Pull request by MaratMussabekov**
https://github.com/MicrosoftDocs/windows-itpro-docs/issues/6860

### CODE REVIEW

**Comment by MaratMussabekov** [comment]
Dear @JohanFreelancer9,
kindly do the copy editor review for this PR.

Dear @nam31, for your information

Thank you

**Review by JohanFreelancer9 — APPROVED** [review]

**Comment by nam31** [comment]
@ManikaDhiman PR has been copyedited and is ready for final review, could you please check and merge? Thanks!

**Comment by Cheoljin** [comment]
@MaratMussabekov I am not aware of any recent changes associate with this file. Can you explain why we try to make the change? What is the expected gain by updating this? Do you think this was a bug?

**Comment by MaratMussabekov** [comment]
Hello @Cheoljin ,
**Can you explain why we try to make the change?** - System/AllowLocation policy was referred to the wrong GPO. It duplicates functionality of *Let Windows apps access location* GPO, not of *Turn off location*
Thank you

**Comment by Cheoljin** [comment]
@MaratMussabekov I am from the Microsoft feature team to review. From my view, we should not make this change. 

For context, there are two policies, similar each other but different: (1) System/AllowLocation (2) Policy/LetAppsAccessLocation.

(2) is newer and extended version, containing the feature of (1), in terms of global/device-wide location access control. But (2) has additional feature to control per-app basis, e.g., LetAppsAccessAccountInfo_UserInControlOfTheseApps_List.

Thus, AppPrivacy.admx and Sensors.admx have different purpose and definition; i.e., mapping values for (a) user-control. (b) force-on. (c). force-off are different; for example Privacy/LetAppsAccessLocation defines "User-in-control" as 0, while System/AllowLocation defines 1 as "User-in-control".

Interestingly, sensors.admx does not match this right definition, though. This only defines on and off and their values are not correct.

However, updating Sensors.admx to AppPrivacy.admx (assuming that they are duplicate) is not correct too, causing more confusion, e.g., customer set "User-in-control" but ends up being another, i.e., ForceOFF.

I'd find the right admx file to replace (that has the following definition: MDMForceOFF -> 0. MDMNoControl -> 1. MDMForceON -> 2). Unfortunately, I was not able to do within a reasonable time I spent. If we cannot find the right one, I'd keep this as is - do you have a good reason that we should update this this time?

**Comment by MaratMussabekov** [comment]
Hello @Cheoljin , thank you for the detailed explanation.
I understand now why *Sensors.admx* shouldn't be replaced by *Appprivacy.admx* here. 
I proposed to change GP to LetAppsAccessLocation because I didn't know about Policy/LetAppsAccessLocation (as it is not presented in the original article).

However, the description of DisableLocation_2 GP is about the enabling/disabling the feature:
"If you enable this policy setting, the location feature is turned off, and all programs on this computer are prevented from using location information from the location feature.
If you disable or do not configure this policy setting, all programs on this computer will not be prevented from using location information from the location feature."
It is not related to the System/AllowLocation policy, which is about the possibility of the user to change the settings.  System/AllowLocation much more similar to the description of LetAppsAccessLocation GP:
"If you choose the "User is in control" option, employees in your organization can decide whether Windows apps can access location by using Settings > Privacy on the device.
If you choose the "Force Allow" option, Windows apps are allowed to access location and employees in your organization cannot change it.
If you choose the "Force Deny" option, Windows apps are not allowed to access location and employees in your organization cannot change it."

So if it is not possible to find the correct admx file right now, would it be possible to just remove "ADMX Info:" section for  System/AllowLocation policy? Or we cannot do this because of Policy CSP document template?

thank you

**Comment by Cheoljin** [comment]
@MaratMussabekov Current description makes sense more to me (unfortunately). If you go to (Computer Configuration -> Administrative Templates -> Windows Components -> Location And Sensors -> Turn off location), you see that the GP UX only provides three options with the radio button; "Not configured", "Enabled", and "Disabled", which are corresponding to "User-in-control", "ForceOFF", and "ForceON".

With that context, the description you provided me about DisableLocation_2 GP makes sense to me (although it could be misleading). Note that GP name is "Disable"-Location*, indicating that it is asking if customer wants to 'forcefully' disable all the apps by controlling the higher-order status. Again, if it is not Enabled (i.e., either Not configured or Disabled), it is valid to indicate that user can change the location settings in the Location->Privacy->Location.

Thus, I would not change anything. Let me know your point of view, though.

**Comment by MaratMussabekov** [comment]
hello @Cheoljin,
yes, sure, as you recommend, I can just close this PR, without any change.
Thank you

**Pull request closed without merging**
