### PR TITLE
Update filepath rules documentation

### PR DESCRIPTION
**Pull request by brbrahm**
Clarify wildcard syntax and new -Level options

### CODE REVIEW

**Comment by brbrahm** [comment]
I'm a WDAC feature team member. These updates are in order to resolve issue #4261

**Comment by illfated** [comment]
The only constructive detail I could imagine would be nice (but maybe cosmetic only?) would be to have the cardinal numbers 0-19 in **Table 2. Windows Defender Application Control policy - policy rule options** changed to ordinals (0.-19.) for better visual spacing. On the other hand, maybe that could change the logical interpretation of the numbers, I am not sure. What do you think?

( I presume the choice of starting the numbering from 0 signifies that the first one (0) is some kind of major default rule, otherwise I would have questioned why not use 1-20.)

**Comment by brbrahm** [comment]
Hi @illfated -- I agree that changing to ordinals might look better, but might also cause confusion. In order to set Enabled:UMCI, you'd need to run the command Set-RuleOption 0. Our current documentation also matches the style of the -help output users can see in PowerShell.

**Comment by illfated** [comment]
Very well, fair enough. Thank you. Based on your feedback, I see no need to pursue my previous train of thoughts.

@e0i : May we have a final review & merge by the document author or manager?

**Comment by e0i** [comment]
cc @jvsam

**Comment by jvsam** [comment]
Hi @Dansimp this pull request is ready for your review and approval. Please check, thanks.

**Comment by brbrahm** [comment]
Hi @Dansimp-- friendly request to review this PR

**Pull request merged**
