### PR TITLE
Adding Service Pack 2 for Microsoft SQL Server 2016

### PR DESCRIPTION
**Pull request by deepaksr06**
Adding Service Pack 2 for Microsoft SQL Server 2016.

### CODE REVIEW

**Comment by e0i** [comment]
@dansimp The PR that introduces a minor addition to a table in MBAM 25 Ssupported Cconfigurations page is available for a quick review. Thanks.

**Comment by DaniHalfin** [comment]
The default branch for this repository has changed. Commenting to remember to merge this to the new default, if this PR gets merged.

**Comment by e0i** [comment]
@deepaksr06 

The default branch for this repository has changed from `master` to `public`. Please edit your pull request to change the merge target to `public` via the `Edit` button at the top right corner. Thanks.

**Comment by deepaksr06** [comment]
As mentioned I have set it to public edited the pull request.
Thankyou

**Comment by illfated** [comment]
Looks like you pressed the wrong button, closing this PR instead of just posting your comment.
Please reopen this, unless you intend to recreate your repository and rebuild the PR.

**Pull request closed without merging**
