### PR TITLE
Remove reference to Microsoft Virtual Academy training video

### PR DESCRIPTION
**Pull request by cchapin2020**
I corrected an error in the original pull request and closed the comments, but it does not look like it has been merged.

### CODE REVIEW

**Comment by illfated** [comment]
Please be patient and keep the Pull Request(s) open until they can be answered or commented on by the Microsoft Docs team members. It may help a bit if you include references to any issue the PR may close or other PRs preceding the current one, in case of rebuilding the PR content from a new branch.

**Comment by illfated** [comment]
BTW, it can sometimes also be useful to keep some form of code style on the PR title, either by referencing the file directly (like in your closed PR) or name the overall concept of the PR content (something similar to **Remove reference to Microsoft Virtual Academy training video**).

Please also note that the opening PR comment usually needs some form of explanation of the PR content, like description of and reason for the changes.

**Comment by Justinha** [comment]
@cchapin2020 is there something wrong with the video? Or is there another reason why you want it removed?

**Comment by illfated** [comment]
@Justinha : in https://github.com/MicrosoftDocs/windows-itpro-docs/pull/3329 there is the following explanation:
> The Microsoft Virtual Academy site is being retired, removed references to the training video.

**Comment by Justinha** [comment]
@illfated Oh I see, thanks Trond. Well, I think we actually have this link in other Credential Guard topics too. If anyone can submit a pull request for those also I really appreciate it.

**Comment by Justinha** [comment]
@cchapin2020 Thanks for letting us know!

**Comment by illfated** [comment]
@Justinha : you may want to review the following Pull Requests 
from @cchapin2020 too, containing the same change:
- https://github.com/MicrosoftDocs/windows-itpro-docs/pull/3330
- https://github.com/MicrosoftDocs/windows-itpro-docs/pull/3331

**Comment by Justinha** [comment]
Got it - thanks folks!

**Pull request merged**
