### PR TITLE
Update start-secondary-tiles.md

### PR DESCRIPTION
**Pull request by nenonix**
Removes dead link (and note) and fixes MD error line 114. Resolves https://github.com/MicrosoftDocs/windows-itpro-docs/issues/4474

### CODE REVIEW

**Comment by illfated** [comment]
👍  Good job, thanks for opening this PR. I will get to the details soon enough.

BTW, have you verified that it is better to remove the tag `<span id="escape" />` than to add a blank line beneath it?

**Comment by nenonix** [comment]
@illfated the HTML tags are from the old content and they are all redundant now (the <a name tags were bookmarks) and the escape tag was not working...the headline after rendered as  
image

**Comment by jvsam** [comment]
Hello @Dansimp, this pull request is ready for your review and approval. Please merge if there are no issues. One of the updates is the removal of a dead link (buildmypinnedsite.com) Thank you. See: [changes](https://github.com/MicrosoftDocs/windows-itpro-docs/pull/4701/files).

**Comment by illfated** [comment]
This PR is one of the cases where the regular file view shows the changes better than the rich text diff.
This is mainly due to the section heading functionality of `#### Prepare the Start layout and Edge assets XML files`
instead of it being displayed as regular text.

**Comment by jvsam** [comment]
Hi again @Dansimp, just following up on this. I hope you'll have time to review and merge. Thanks again.

CC: @AndreaBarr

**Comment by jvsam** [comment]
Thank you for merging @Dansimp and for updating issue #4347.

**Pull request merged**
