### PR TITLE
change made to unrestricted powershell cmd

### PR DESCRIPTION
**Pull request by Jcoetsee**
change made to unrestricted powershell cmd
Please see https://github.com/MicrosoftDocs/windows-itpro-docs/issues/2739

### CODE REVIEW

**Comment by mypil** [comment]
@greg-lindsay - can you please assist to check, approve and merge the content for this PR based on issue #2739? 

Thank you.

**Comment by illfated** [comment]
Looks good to me. This is definitely an improvement on security behaviour for future users of this documentation.
The reasoning behind this change is documented in issue #2739 (as linked by the PR creator).

**Comment by mypil** [comment]
@greg-lindsay - I would like to follow up on this. Can you please assist to check, approve and merge the content for this PR based on issue #2739?

Thank you.

**Comment by mypil** [comment]
@greg-lindsay - I would like to follow up on this. Can you please assist to check, approve and merge the content for this PR based on issue #2739?

cc: @kenwith @AndreaBarr

**Comment by mypil** [comment]
@kenwith - Would you be able to merge the content for this PR?

Thanks.

**Pull request merged**
