### PR TITLE
Follow-up from users, network requirements

### PR DESCRIPTION
**Pull request by maximvelichko**

### CODE REVIEW

**Comment by jdeckerms** [comment]
@maximvelichko Just a note about Microsoft style - we don't use "click on". Where you have "Click on Open System Preferences...", it should be "Click Open System Preferences".

**Comment by egallagh** [comment]
@jdeckerms Is there a current Microsoft Style Guide available?

**Comment by jdeckerms** [comment]
@egallagh I don't think MSTP is available externally, but for all doc contributors, there's a public style guide at https://docs.microsoft.com/en-us/style-guide/welcome/

**Comment by jdeckerms** [comment]
And actually we're moving away from "click", toward "select", since mouse-and-keyboard aren't the only input methods anymore. But changing "click" should be throughout a topic.

**Pull request merged**
