### PR TITLE
Add .circleci/config.yml

### PR DESCRIPTION
**Pull request by Dmarch28**

### CODE REVIEW

**Review by JohanFreelancer9 — COMMENTED** [review]
Will do copy edit, if required, after technical review.

**Comment by denisebmsft** [comment]
Not sure what this submission is for.

**Comment by illfated** [comment]
This type of configuration is mostly used in repositories where one or more executable files are built as a result of compiling a dedicated source build.

Since MicrosoftDocs is not about compiling, I don't see a need for this type of config file, unless it can be documented that there are PowerShell files in need of testing before publishing to the docs.microsoft.com site.

@Dmarch28 : Do you have any documentation to show us how this can improve anything at all in the MS Docs repository?

**Comment by dstrome** [comment]
Closing PR. We don't accept changes of this type.

**Pull request closed without merging**
