### PR TITLE
Add location setting

### PR DESCRIPTION
**Pull request by yogeshasalkar**
'Windows Components/Location and Sensors/Windows Location Provider/Turn off Windows Location Provider' this Group policy can be configured via Intune using the OMA-URI './Device/Vendor/MSFT/Policy/Config/Location/EnableLocation'. This documentation is missing the 'Location' settings.
#6602

### CODE REVIEW

**Comment by yogeshasalkar** [comment]
@e0i please have a look.  Thanks

**Comment by ManikaDhiman** [comment]
Hi @yogeshasalkar, Thanks for adding the missing policy setting to the policy doc. However, the new MD file that you added is missing the required metadata details and footnotes section. You may refer to any existing policy CSP doc for the template structure. I did some digging and found that this policy was removed from the docs per this [PR](https://github.com/MicrosoftDocs/windows-itpro-docs/commit/cb8ae82f6613128fb18a35b1727b823f8f5e04e9#diff-c296d78b698976059a977928301da570).

On a side note, when adding a new setting to the policy CSP docs, in addition to updating it's policy doc, we need to update the following also:

- [Policy CSP index](https://docs.microsoft.com/en-us/windows/client-management/mdm/policy-configuration-service-provider) page, which lists all the policies settings for each area name. 
- TOC.md if a new area name is added. In this case, a new area name, "Location" is added, which must also be added to TOC. 
- Respective release section in the [What's new doc](https://docs.microsoft.com/en-us/windows/client-management/mdm/new-in-windows-mdm-enrollment-management) to indicate from which Windows 10 version the policy setting is available.

Hope these pointers will help you in making future updates to the policy CSP docs.

Thanks!

**Comment by yogeshasalkar** [comment]
Thanks, @ManikaDhiman for the contribution guide. I don't see the reasons why this policy setting was removed?

**Comment by ManikaDhiman** [comment]
Hi @yogeshasalkar, The product team confirmed that the Location/EnableLocation policy has been deprecated. The recommendation is to use System/AllowLocation. 

@e0i, @denisebmsft: Could you close this PR since no doc updates are required for this policy? I am not sure if I can close the PR as such.

Thanks!

**Pull request closed without merging**
