### PR TITLE
Auditing: Add an event example in event-5159.md

### LINKED ISSUE #3291: windows event log 5159 xml example
i found this page that hasn't example and i tested this event. 
below is event's xml content:

```xml
<Event
    xmlns="http://schemas.microsoft.com/win/2004/08/events/event">
    <System>
        <Provider Name="Microsoft-Windows-Security-Auditing" Guid="{54849625-5478-4994-A5BA-3E3B0328C30D}" />
        <EventID>5159</EventID>
        <Version>0</Version>
        <Level>0</Level>
        <Task>12810</Task>
        <Opcode>0</Opcode>
        <Keywords>0x8010000000000000</Keywords>
        <TimeCreated SystemTime="2019-04-18T07:36:55.955388300Z" />
        <EventRecordID>44097</EventRecordID>
        <Correlation />
        <Execution ProcessID="4" ThreadID="6480" />
        <Channel>Security</Channel>
        <Computer>NATHAN-AGENT2</Computer>
        <Security />
    </System>
    <EventData>
        <Data Name="ProcessId">7924</Data>
        <Data Name="Application">\device\harddiskvolume2\users\test\desktop\netcat\nc.exe</Data>
        <Data Name="SourceAddress">0.0.0.0</Data>
        <Data Name="SourcePort">5555</Data>
        <Data Name="Protocol">6</Data>
        <Data Name="FilterRTID">84614</Data>
        <Data Name="LayerName">%%14608</Data>
        <Data Name="LayerRTID">36</Data>
    </EventData>
</Event>
```
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 15180404-ee89-92c7-908a-f3d7d6802e44
* Version Independent ID: 56b2c2ab-d2f6-3085-7eed-755183e6eccb
* Content: [5159(F) The Windows Filtering Platform has blocked a bind to a local port. (Windows 10)](https://docs.microsoft.com/en-us/windows/security/threat-protection/auditing/event-5159)
* Content Source: [windows/security/threat-protection/auditing/event-5159.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/master/windows/security/threat-protection/auditing/event-5159.md)
* Product: **w10**
* Technology: **windows**
* GitHub Login: @Mir0sh
* Microsoft Alias: **justinha**

### PR DESCRIPTION
**Pull request by illfated**
**Description:**

The page [event-5159.md](https://docs.microsoft.com/en-us/windows/security/threat-protection/auditing/event-5159) does not yet contain any example outputs from the
event being triggered on a running computer or server.

**Pages referenced in this PR:**
- https://docs.microsoft.com/en-us/windows/security/threat-protection/auditing/event-5158
- https://docs.microsoft.com/en-us/windows/security/threat-protection/auditing/event-5159
- https://github.com/MicrosoftDocs/windows-itpro-docs/issues/3291

**Changes proposed:**

Add examples based on its predecessor page [event-5158.md](https://docs.microsoft.com/en-us/windows/security/threat-protection/auditing/event-5158)
and samples provided by audi5411 in issue ticket #3291
([windows event log 5159 xml example](https://github.com/MicrosoftDocs/windows-itpro-docs/issues/3291))

**To do:**

- [ ] Verify complete validity of the added content
- [ ] Get precise sample images from the docs team
- [ ] Get feedback regarding additional required information

Closes #3291

### CODE REVIEW

**Comment by illfated** [comment]
Opening the PR for review, need external feedback to make any changes.

**Comment by e0i** [comment]
@Justinha @Mir0sh Would you review this PR contributed by the community? Thanks.

**Comment by illfated** [comment]
😃 Thank you for accepting the contribution. In my mind, being as pedantic as me (I am mildly autistic), it would be a requirement to provide image examples using "contoso" or Microsoft example names used in the completed pages. Then again, I presume the current image contains a sufficient name to avoid confusion.

**Comment by Justinha** [comment]
@illfated great point. Mismatched computer names are fin in this case.

**Comment by illfated** [comment]
Linking issue #3292 as a reference, for future reading.

**Pull request merged**
