### PR TITLE
update description for 0xC000006E

### PR DESCRIPTION
**Pull request by VLG17**
https://github.com/MicrosoftDocs/windows-itpro-docs/issues/8219

### CODE REVIEW

**Comment by e0i** [comment]
@JohanFreelancer9 Copy editing is needed for this PR. Thanks.

**Review by JohanFreelancer9 — APPROVED** [review]

**Comment by illfated** [comment]
Sorry for bothering you with a cosmetic detail. Would you mind reducing the amount of whitespace at the end of the new sentence?

**Review by VLG17 — COMMENTED** [review]
reduced whitespace

**Review by illfated — APPROVED** [review]
Looks good to me.

**Pull request merged**
