### PR TITLE
Replaced video link with LinkedIn video

### PR DESCRIPTION
**Pull request by computeronix**
The MVA site is retired and the video is no longer valid.  I have provided the following suggested video from LinkedIn - course: Microsoft Cybersecurity Stack: Advanced Identity and Endpoint Protection

https://www.linkedin.com/learning/microsoft-cybersecurity-stack-advanced-identity-and-endpoint-protection/manage-credential-guard?u=3322

Note: you must have a LinkedIn Learning subscription to see the whole video

### CODE REVIEW

**Comment by e0i** [comment]
@DaniHalfin Would you review and merge this PR that suggests a proper MVA link? Thanks.

**Comment by e0i** [comment]
@DaniHalfin Any updates?

**Comment by illfated** [comment]
@computeronix : out of curiosity, are there more videos, like the one you suggest, on LinkedIn?
Do you know if there is one that could replace the link in my PR #3816 ?

**Comment by e0i** [comment]
@martyav @lizap Would you be able to merge this PR that addresses a known issue regarding MVA links? Thank you.

**Comment by martyav** [comment]
There have been conversations about avoiding pay-walled videos, because it would frustrate customers looking for quick information on a topic. I think in cases where the only viable option is paywalled, we should remove the dead link, and where appropriate, provide the paywalled version under a See Also section, with some indicator that you will need to subscribe to view it in full

**Comment by illfated** [comment]
I concur. There is already a dead link in the [**See also**](https://docs.microsoft.com/en-us/windows/security/identity-protection/credential-guard/credential-guard-protection-limits#see-also) section. That one should be replaced in favor of this one (in this PR) which should be removed completely, along with its sentence text.

**Comment by e0i** [comment]
cc @computeronix

**Comment by e0i** [comment]
@computeronix Any updates with suggested changes? Thank you.

**Comment by e0i** [comment]
@computeronix

We are closing this PR as there hasn't been a follow-up from your side regarding suggested changes.

Note that dead MVA links are a known issue and the links are being updated whenever applicable. 

Thank you for bringing the issue to our attention and for your contributions.

**Comment by e0i** [comment]
@officedocsbot close

**Pull request closed without merging**
