### PR TITLE
replaced mmd to mdm

### PR DESCRIPTION
**Pull request by RAJU2529**
as per the user report #8200  so I replaced mmd to mdm

### CODE REVIEW

**Comment by illfated** [comment]
Please also change the H3 Heading in line 83, the target of the link you have changed:

### Mobile Device Management (MMD)

Use the [./Vendor/MSFT/Policy/Config/Defender/EnableNetworkProtection](https://docs.microsoft.com/windows/client-management/mdm/policy-csp-defender#defender-enablenetworkprotection) configuration service provider (CSP) to enable or disable network protection or enable audit mode.

**Comment by RAJU2529** [comment]
ok I create

**Comment by illfated** [comment]
Uhm... oh well. I thought you had learned how to edit your own PR content.

**Comment by illfated** [comment]
What if you make a new PR again, this time with both line 83 and 44 edited together in the same PR?
Or maybe that is a bit too much to ask?

**Comment by levinec** [comment]
Updated the file to add the second change. 
image

**Pull request merged**
