### PR TITLE
minor edits

### PR DESCRIPTION
**Pull request by joinimran**
As user has mentioned that when he tried to run a delete function, it doesn't work. While checking for DMClient CSP, I have found that Provider/ProviderID/Push/PFN only supports Add, Get, and Replace function not Delete. See details at https://docs.microsoft.com/en-us/windows/client-management/mdm/dmclient-csp

Problem: https://github.com/MicrosoftDocs/windows-itpro-docs/issues/7061

### CODE REVIEW

**Comment by joinimran** [comment]
@JohanFreelancer9 - kindly do the copy editor review for this PR. Thanks.

**Comment by ManikaDhiman** [comment]
Reached out to the product team to confirm if this requires doc vs code changes. I will update the status as soon as I hear from the team. Thanks!

**Comment by e0i** [comment]
@ManikaDhiman Any updates from the product team regarding the updates? Thank you.

**Comment by ManikaDhiman** [comment]
This is only a doc fix, the actual DDF file will continue to show the Delete function until it is fixed in the code.

**Pull request merged**
