### PR TITLE
Event Forwarding: 1 word typo removal

### LINKED ISSUE #8361: TYPO ON MICROSOFT DOCS WEBSITE
Just a small typo, but still an error.  Am I only able to submit feedback for Microsoft through GitHub?

-Jennifer Cleveland

MicrosoftDocs_TYPO

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e5862cc7-3f36-5f2e-9ade-f7441f99f818
* Version Independent ID: b8bd1985-7b5b-ea79-976a-7d96ad69335c
* Content: [Use Windows Event Forwarding to help with intrusion detection (Windows 10) - Windows security](https://docs.microsoft.com/en-us/windows/security/threat-protection/use-windows-event-forwarding-to-assist-in-intrusion-detection)
* Content Source: [windows/security/threat-protection/use-windows-event-forwarding-to-assist-in-intrusion-detection.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/public/windows/security/threat-protection/use-windows-event-forwarding-to-assist-in-intrusion-detection.md)
* Product: **w10**
* GitHub Login: @DulceMontemayor
* Microsoft Alias: **dansimp**

### PR DESCRIPTION
**Pull request by illfated**
1 word typo removal: "there are two different **of** subscriptions published"

Thanks to @CLEVELAND2024 for reporting the typo and asking for correction.

Closes #8361

### CODE REVIEW

**Review by illfated — COMMENTED** [review]
- [X] **Rich diff** for easier pin-pointing of the changed text: https://github.com/MicrosoftDocs/windows-itpro-docs/pull/8362/files?short_path=19c4412#diff-19c441214b40e868911992155c10417f

**Comment by illfated** [comment]
#sign-off

**Comment by CLEVELAND2024** [comment]
It still isn’t correct. 
If there are two subscriptions, and each are different, then there are two different subscriptions. 
Please review for update. 
Thanks again
Jennifer Cleveland
    	
    	

    	Get Outlook for iOS
    
  




On Sat, Sep 26, 2020 at 2:52 PM -0700, "Trond B. Krokli" <notifications@github.com> wrote:















#sign-off

**Comment by illfated** [comment]
@CLEVELAND2024 : Thank you for the feedback. I don't know this topic well enough to immediately see what you mean. Could you possibly suggest the correct phrasing, either for additional text, or for what should be written instead of the existing text, to make it correct?

**Review by denisebmsft — APPROVED** [review]
Thank you @illfated

**Comment by illfated** [comment]
You are welcome. Thank you for merging.

@CLEVELAND2024 : If you do have more information on how the text needs to be changed, please open a new issue ticket to request that change.

**Pull request merged**
