### PR TITLE
Fix the table

### PR DESCRIPTION
**Pull request by DrPizza**
Markdown tables seem very fragile. Something was upsetting this one.

### CODE REVIEW

**Comment by illfated** [comment]
Nice job, I approve. 👍 MarkDown formatting is quite picky when it comes down to the number of spaces (or lack thereof) for text and table formatting. Following the same codestyle within the same paragraph or chapter is important too.

**Comment by DrPizza** [comment]
Yeah, it looks like the single space in the line before is what was throwing it off. Easy to fix, and yet, awkward to fix, since it's so hard to see invisible characters...

**Comment by illfated** [comment]
Even so, it looks like the public page https://docs.microsoft.com/windows/security/information-protection/bitlocker/bcd-settings-and-bitlocker is able to build its tables without issues, regardless of the state of the github page.

I suppose this change can be seen mostly as an improvement to keep the github page in order, just to make it easier to work on it later, if changes are needed.

**Comment by DrPizza** [comment]
It looks like someone must have gone in and fixed it, because it was broken when I clicked through to edit it--showing exactly the same broken table as github's markdown....

**Comment by illfated** [comment]
OK, it is possible that @Justinha has fixed it one way or other, skipping the github page.

**Comment by Justinha** [comment]
@illfated @DrPizza Thanks guys. I think we might have had some temp publishing errors. Should be all fixed now.

**Pull request merged**
