### PR TITLE
added one example

### PR DESCRIPTION
**Pull request by MaratMussabekov**
https://github.com/MicrosoftDocs/windows-itpro-docs/issues/6565

### CODE REVIEW

**Comment by MaratMussabekov** [comment]
Dear @JohanFreelancer9 ,
could you please perform a copy review?
Thank you

**Comment by mypil** [comment]
@JohanFreelancer9 - kindly do the copy editor review for this PR. Thanks.

**Comment by illfated** [comment]
The XML looks pretty good, I just wonder if the `<Data>` segment is supposed to be in 1 line, seeing that there are so many tags inside it.

Could it possibly be "beautified" as in using XML pretty print to form something like this? (See the code block hidden in the **Details** feature below.)

<details>

```xml
<SyncML
  xmlns="SYNCML:SYNCML1.2">
  <SyncBody>
    <Add>
      <CmdID>1</CmdID>
      <Item>
        <Target>
          <LocURI>./Device/Vendor/MSFT/WiredNetwork/LanXML</LocURI>
        </Target>
        <Meta>
          <Format
            xmlns="syncml:metinf">chr
          </Format>
        </Meta>
        <Data>
          <?xml version="1.0"?>
          <LANProfile
            xmlns="http://www.microsoft.com/networking/LAN/profile/v1">
            <MSM>
              <security>
                <OneXEnforced>false</OneXEnforced>
                <OneXEnabled>true</OneXEnabled>
                <OneX
                  xmlns="http://www.microsoft.com/networking/OneX/v1">
                  <EAPConfig>
                    <EapHostConfig
                      xmlns="http://www.microsoft.com/provisioning/EapHostConfig">
                      <EapMethod>
                        <Type
                          xmlns="http://www.microsoft.com/provisioning/EapCommon">25
                        </Type>
                        <VendorId
                          xmlns="http://www.microsoft.com/provisioning/EapCommon">0
                        </VendorId>
                        <VendorType
                          xmlns="http://www.microsoft.com/provisioning/EapCommon">0
                        </VendorType>
                        <AuthorId
                          xmlns="http://www.microsoft.com/provisioning/EapCommon">0
                        </AuthorId>
                      </EapMethod>
                      <Config
                        xmlns="http://www.microsoft.com/provisioning/EapHostConfig">
                        <Eap
                          xmlns="http://www.microsoft.com/provisioning/BaseEapConnectionPropertiesV1">
                          <Type>25</Type>
                          <EapType
                            xmlns="http://www.microsoft.com/provisioning/MsPeapConnectionPropertiesV1">
                            <ServerValidation>
                              <DisableUserPromptForServerValidation>false</DisableUserPromptForServerValidation>
                              <ServerNames></ServerNames>
                            </ServerValidation>
                            <FastReconnect>true</FastReconnect>
                            <InnerEapOptional>false</InnerEapOptional>
                            <Eap
                              xmlns="http://www.microsoft.com/provisioning/BaseEapConnectionPropertiesV1">
                              <Type>26</Type>
                              <EapType
                                xmlns="http://www.microsoft.com/provisioning/MsChapV2ConnectionPropertiesV1">
                                <UseWinLogonCredentials>false</UseWinLogonCredentials>
                              </EapType>
                            </Eap>
                            <EnableQuarantineChecks>false</EnableQuarantineChecks>
                            <RequireCryptoBinding>false</RequireCryptoBinding>
                            <PeapExtensions>
                              <PerformServerValidation
                                xmlns="http://www.microsoft.com/provisioning/MsPeapConnectionPropertiesV2">true
                              </PerformServerValidation>
                              <AcceptServerName
                                xmlns="http://www.microsoft.com/provisioning/MsPeapConnectionPropertiesV2">false
                              </AcceptServerName>
                              <PeapExtensionsV2
                                xmlns="http://www.microsoft.com/provisioning/MsPeapConnectionPropertiesV2">
                                <AllowPromptingWhenServerCANotFound
                                  xmlns="http://www.microsoft.com/provisioning/MsPeapConnectionPropertiesV3">true
                                </AllowPromptingWhenServerCANotFound>
                              </PeapExtensionsV2>
                            </PeapExtensions>
                          </EapType>
                        </Eap>
                      </Config>
                    </EapHostConfig>
                  </EAPConfig>
                </OneX>
              </security>
            </MSM>
          </LANProfile>
        </Data>
      </Item>
    </Add>
  </SyncBody>
</SyncML>
```

</details>

Please note: I am not fluent in XML or SyncML , so I could easily be mistaken when it comes to details like this. Besides the fact that the current XML may be correct, it could also be a question whether the XML should use 2 space indents or 4 space indents. (My suggestion uses 2 space indents, to keep the horizontal indentation within reasonable limits.)

**Comment by MaratMussabekov** [comment]
Hello @illfated ,
I believe it should be left as it is.
What did I done:
1. exported the LAN profile (netsh lan export profiles) as XML file
2. convert XML file into a string (as Data should be a string)
3. added string to the Data section of SyncML 

I did it the same as it is shown [here](https://docs.microsoft.com/en-us/windows/client-management/mdm/wifi-csp).
Thank you

**Comment by illfated** [comment]
Very well, thank you for linking a related example. That is good enough for me.

**Comment by mypil** [comment]
@ManikaDhiman - PR has been copy edited and is ready for final review. This is based on issue #6565.

Thank you.

cc: @kenwith

**Comment by ManikaDhiman** [comment]
Hi @mypil, I have reached out to the product team to verify these changes. I will update this as soon as I hear from them. Thanks!

**Pull request merged**
