### PR TITLE
Remove apostrophes that cause bug

### LINKED ISSUE #6326: Can't run DG_Readiness_Tool_v3.7
Can't run 
```
At <path-to-script>/DG_Readiness_Tool_v3.6.ps1:135 char:48
+ function CheckFailedDriver($_ModName, $CIStats)''
+                                                ~
Missing function body in function declaration.
    + CategoryInfo          : ParserError: (:) [], ParseException
    + FullyQualifiedErrorId : MissingFunctionBody
```

### PR DESCRIPTION
**Pull request by rluvaton**
Fix #6326

### CODE REVIEW

**Comment by illfated** [comment]
@e0i : Please assign a tech writer or author to verify this change. There is hardly any text to proofread there, mostly only source code.

**Comment by rluvaton** [comment]
@illfated Updated the version number as suggested

**Comment by illfated** [comment]
Oh. That was not what I had in mind at all. Please note that if I wanted to suggest a change in the source code, I would have commented on _this_ page or _directly in the code_ .

What I commented on, is in your issue ticket **Can't run DG_Readiness_Tool_v3.6** **#6326**, the title says "3.6" instead of **3.7**.

**Comment by illfated** [comment]
Please revert the latest commit, if you can.

**Comment by rluvaton** [comment]
> Please revert the latest commit, if you can.

But the version needed to be changed anyway, no?

**Comment by illfated** [comment]
Also, if your title is based on a link from a different page, but still saying **DG_Readiness_Tool_v3.6**, please comment on that in your issue ticket so we can take a look at the originating page and decide if that page can be updated.

**Comment by illfated** [comment]
Sorry, I don't know with 100% certainty if the readiness tool version number needs to be updated, but you have got a fair point insofar as to remove a bug from the code.

I will leave that question for the moderator, document author or project manager to decide.

**Comment by illfated** [comment]
(ref. #6326 )

**Pull request merged**
