### PR TITLE
Documenting MBSA issue with latest cab file

### PR DESCRIPTION
**Pull request by andreiztm**

### CODE REVIEW

**Comment by andreiztm** [comment]
Just as FYI, the note was taken from this page:
https://docs.microsoft.com/en-us/windows/win32/wua_sdk/using-wua-to-scan-for-updates-offline

**Comment by andreiztm** [comment]
Specifically this commit: https://github.com/MicrosoftDocs/win32/commit/8f29b4d8c69a38568198b2b1ea9929b82c07c303#diff-4d05c816b88a7098856ed36e4990fa7f

**Comment by andreiztm** [comment]
Hi, could someone please share an update on this? Thank you.

**Comment by e0i** [comment]
@andreiztm The PR has been escalated for review. Thank you for following up.

**Comment by andreiztm** [comment]
@e0i thanks for the info, looking forward to any updates.

**Comment by andreiztm** [comment]
@e0i do we have any update? Just as FYI, I wrote this article.

**Comment by e0i** [comment]
The content is going to be merged by a vendor with merge permissions soon, thank you.

**Comment by andreiztm** [comment]
Thank you for the confirmation.

**Comment by andreiztm** [comment]
Thank you everyone!

**Pull request merged**
