### PR TITLE
Updated Note section of Kiosk Browser

### PR DESCRIPTION
**Pull request by Chandanahk**

### CODE REVIEW

**Comment by jdeckerms** [comment]
@Chandanahk You have a typo in the word "browser", please fix. Also, what is your source for this information? Thanks!

**Comment by Chandanahk** [comment]
Hi Jeanie,

I have fixed the typo and here is the source for this:

**Comment by Chandanahk** [comment]
Sorry, hit the send button too soon.

I have fixed the typo and here is the source for this:
https://www.microsoft.com/en-us/p/kiosk-browser/9ngb5s5xg2kp?activetab=pivot%3Aoverviewtab

Additional information section(Permissions info) in the above article.

Regards,
Chandana



From: Chandana Hoblegowda Krishnappa
Sent: Wednesday, March 27, 2019 12:00 AM
To: MicrosoftDocs/windows-itpro-docs <reply@reply.github.com>; MicrosoftDocs/windows-itpro-docs <windows-itpro-docs@noreply.github.com>
Cc: Mention <mention@noreply.github.com>
Subject: RE: [MicrosoftDocs/windows-itpro-docs] Updated Note section of Kiosk Browser (#3067)

Hi Jeanie,

I have fixed the typo and here is the source for this:

**Comment by jdeckerms** [comment]
Thanks, @Chandanahk , but there's nothing there about intranets, so I'll need to confirm the changes with the product team before I can merge this.

**Comment by Chandanahk** [comment]
Sure Jeanie. Appreciate your help.

**Pull request merged**
