### PR TITLE
Reg key breaks Windows Store connectivity

### PR DESCRIPTION
**Pull request by VLG17**
https://github.com/MicrosoftDocs/windows-itpro-docs/issues/6600

### CODE REVIEW

**Comment by jaimeo** [comment]
@VLG17 i'm a little unclear on your edit. What is "Group Policy Management Editor?" Do you mean "Group Policy Management Console?" And if so, I don't think you can edit regkeys in GMPC. Do you mean to use Registry Editor to check that that key is not enabled?

**Comment by VLG17** [comment]
@jaimeo What i wanted to say was to use gpedit.msc to verify thaat specific key is not enabled.

**Comment by jaimeo** [comment]
@VLG17 maybe I'm just not awake yet, but can you check whether a regkey is enabled in GPMC? Wouldn't you use Regedit.exe for that?

**Comment by VLG17** [comment]
@jaimeo you're right, i think it's me who's not awake. It needs to be checked with Regedit...don't know why i said Group Policy Management Editor, i'll change that to Registry Editor

**Comment by jaimeo** [comment]
@VLG17 no worries! I was thinking "gee did they add some new feature to GPMC?" :^)

**Pull request merged**
