### PR TITLE
Added Most Asked Queries

### PR DESCRIPTION
**Pull request by rahulkumarsingh73690**

### CODE REVIEW

**Comment by e0i** [comment]
@greg-lindsay Would you be able to review this PR that is contributed by the community? Thanks.

**Comment by e0i** [comment]
@greg-lindsay Any updates with the PR? Thanks.

**Comment by illfated** [comment]
I recommend closing this PR. The contributor is suggesting a non-Microsoft page, not even belonging to a Microsoft partner. As a matter of fact, this is self promotion, which Microsoft will not accept at all.

**Comment by e0i** [comment]
@rahulkumarsingh73690 As mentioned by @illfated , third party links outside the Microsoft domains are not referenced within the docs.

Thank you for taking the time to contribute to docs, any other contributions are always welcome.

**Comment by e0i** [comment]
@officedocsbot close

**Pull request closed without merging**
