### PR TITLE
Update enterprise-mode-schema-version-2-guidance.md

### PR DESCRIPTION
**Pull request by andrefboliveira**
Added more details on the release of Windows 10 for which schema v2 applies.
allow-redirect flag is only available starting from RS3 (v 1709)

### CODE REVIEW

**Comment by andrefboliveira** [comment]
Maybe it is best to add that warning on the allow-redirect sections (line block 197 - 206).
Please check what is the best place to add the warning, but is important to add this information.

For example:

```
<td>allow-redirect</td>
<td>A boolean attribute of the &lt;open-in&gt; element that controls the behavior for redirected sites. Setting this attribute to &quot;true&quot; indicates that the site will open in IE11 or Microsoft Edge even if the site is navigated to as part of a HTTP or meta refresh redirection chain. Omitting the attribute is equivalent to &quot;false&quot; (sites in redirect chain will not open in another browser).
This feature is only available for Windows 10 v1709 and higher.
<p><b>Example</b>
<pre class="syntax">
&lt;site url=&quot;contoso.com/travel&quot;&gt;
  &lt;open-in allow-redirect=&quot;true&quot;&gt;IE11&lt;/open-in&gt;
&lt;/site&gt;</pre>
In this example, if <a href="https://contoso.com/travel" data-raw-source="https://contoso.com/travel">https://contoso.com/travel</a> is encountered in a redirect chain in Microsoft Edge, it will be opened in Internet Explorer.</td>
<td>Internet Explorer 11 and Microsoft Edge</td>
</tr>
```

**Comment by e0i** [comment]
@lomayor A community contributed PR is available for review. Thanks.

**Comment by lomayor** [comment]
@e0i, can you validate this change with dev/PM? Also, "version 1709 or newer" is better phrasing, but I actually suggest explicitly listing versions known to support this.

**Comment by andrefboliveira** [comment]
@lomayor Thank you very much for the feedback. This is my first contribution to Microsoft Docs. So, I am very receptive to feedback on how to improve.
We (CSS) validated with PG about the allow-redirect option. You can re-check to be sure.
Also can you please check if only the allow-redirect option is available starting from v1709, or if the full v2 schema is supported only on v1709 and newer?
Just to make sure that the live version of this document is clear.

**Comment by andrefboliveira** [comment]
Please refer to [commit f5a9f055c70053f755a9fe3407b2780a139ca16d](https://github.com/MicrosoftDocs/windows-itpro-docs/commit/f5a9f055c70053f755a9fe3407b2780a139ca16d)
which adds the "allow-redirect" option to the documentation

**Comment by e0i** [comment]
PR Noted for validation through PM.

**Comment by andrefboliveira** [comment]
Also please check if the option "allow-redirect" is available for Windows 7 and 8.1. If so, it is best to reference the availability of this option in the "allow-redirect" section rather than in the header of the page (that refers to the full v2 schema)

**Comment by andrefboliveira** [comment]
@e0i and @lomayor any update on this?
Thanks in advance

**Comment by e0i** [comment]
@andrefboliveira Apologies, The delay is due to a mix-up on notes from my side. Confirming.

**Comment by andrefboliveira** [comment]
Hi @AndreaBarr 
This should not have been merged without checking the issues raised in the comment section.
It seems that only the "allow-redirect" is available on Windows 10 versions greater than v1709.

It is not the same for the other tags.
This page needs be revised by the engineering team, to make sure that availability of every tag is clear.

@e0i and @lomayor can you help review the change?

Thanks in advance.

**Comment by e0i** [comment]
@andrefboliveira The PR contents have been reverted (see https://github.com/MicrosoftDocs/windows-itpro-docs/pull/4684#issuecomment-521043411)

**Comment by andrefboliveira** [comment]
Hi @e0i 
Thanks. Now, the wrong information for all tags is fixed.

But can you please add the disclaimer for the _allow-redirect_ tag?
Also check with Dev/PM availability of the other tags.

Please fix the _allow-redirect_ info was son as possible.
_allow-redirect_ seems to be only available for Windows 10 versions greater than v1709 (v1709, v1803 v1809, v1903).

Thanks in advance.

**Comment by e0i** [comment]
@andrefboliveira The investigation is still in progress. Thank you for your contributions and taking the time to follow-up. Much appreciated.

**Comment by andrefboliveira** [comment]
@e0i any update?

**Comment by illfated** [comment]
Based on your comment 21 days ago (https://github.com/MicrosoftDocs/windows-itpro-docs/pull/4248#issuecomment-521719161), I suggest opening a new Pull Request to have the confirmed information added where you know it belongs. Of course, if you are still waiting for some or all of the information to be confirmed, feel free to wait for necessary feedback. You could also choose to create more than one PR, separate ones for only the already confirmed information, if some of it is validated already.

**Comment by e0i** [comment]
@andrefboliveira 

There are internal difficulties regarding re-organization that makes escalations for this specific issue difficult. It is likely that the escalations are going to take a longer time. 

 Thank you for taking the time to invest in fixing this issue.

**Pull request merged**
