### PR TITLE
added  simplifying deployment of SSU link

### PR DESCRIPTION
**Pull request by RAJU2529**
as per the user feedback #8478, so i added a simplifying-on-premises-deployment-of-SSU link.

### CODE REVIEW

**Comment by illfated** [comment]
I don't necessarily have a firm opinion on this added line, only the notion that this type of added documentation is usually listed in some form of "See also:" section or specific "References:" section at the bottom of the page.

I am not sure if the link and text belongs in the currently selected section, so I defer to the document author (Jaime Ondrusek) and our familiar copy reviewer, JohanFreelancer9, to approve and confirm this new content.

**Comment by e0i** [comment]
@JohanFreelancer9 Copy editing is needed for this PR. Thanks.

**Comment by jaimeo** [comment]
@arcarley let's remember to incorp the blog information into this article.

**Comment by arcarley** [comment]
@jaimeo I think we should wait on updating docs until the blog content (simplifying SSU +LCU changes) are actually in Public preview or live.

**Comment by felizondojr** [comment]
A link to the Windows 10 IT Pro blogs should be found in the Windows 10 documentation for IT Pros. It makes things much easier when we have a single point of reference.

**Pull request merged**
