### PR TITLE
Unfurl the list, perform link maintenance

### PR DESCRIPTION
**Pull request by skycommand**
From top to bottom, I propose the following changes without prejudice:

1. Convert the heaped mass of links into an accessible list, compliant with Microsoft Docs guideline.
2. Delete the second, redundant instance of the link to "Release Notes for MBAM 2.5/2.0".
3. Delete the link to "MDOP TechCenter Page". This page is now deleted. The link redirects to "MDOP Information Experience" to which there is already a link in the page.
4. Delete feedback links (email, Twitter, and Facebook). These channels have been defunct since 2015.
5. Delete the entire "Got a suggestion for MBAM" section. Both links in it are dead. The UserVoice channel and TechNet subforum have been gone for a long time now.

### CODE REVIEW

**Comment by e0i** [comment]
@jamiejdt A new PR for a document of your authorship is available for review. Thanks.

**Comment by e0i** [comment]
@nenonix @JohanFreelancer9 Copy editing is needed for this community contribured PR. Thanks.

**Comment by e0i** [comment]
@jamiejdt Any updates with the PR? Thanks.

**Comment by e0i** [comment]
@jamiejdt Following up for updates.

**Comment by e0i** [comment]
@jamiejdt Following up for updates.

**Comment by e0i** [comment]
@jamiejdt Following up for updates.

**Comment by skycommand** [comment]
@e0i Hi. Are you certain you are pinging the right person? This account, @jamiejdt seems to have had no contributions on GitHub since 2016. No wonder they have not been responding since 20 days ago.

**Comment by illfated** [comment]
Seeing that this content is security related (MBAM), I presume it will be just as practical to ask if @Justinha or @martyav are available for approval and merging this, or point to who should approve this before merge.

**Comment by Justinha** [comment]
@skycommand thanks for the help! @e0i sorry I think our metadata is outdated in this case but I'm unsure how to correct it.

@ thanks for the assist as always!

**Comment by Justinha** [comment]
@illfated thanks for the assist as always!

**Comment by e0i** [comment]
> @e0i sorry I think our metadata is outdated in this case but I'm unsure how to correct it.

Corrected via #4563. Thanks.

**Pull request merged**
