### PR TITLE
Update microsoft-recommended-block-rules.md

### PR DESCRIPTION
**Pull request by brunocarranca**
Removed Intune Agent from xml since blocking it get the machine into unsupported scenario regarding Intune

## Why

- Closes #[Issue Number]

### CODE REVIEW

**Review by JohanFreelancer9 — APPROVED** [review]

**Comment by jsuther1974** [comment]
The block is version specific, though, and only targets an old version of Intune. What's the scenario where this is actually causing a functional break to Intune?

**Comment by aczechowski** [comment]
@brunocarranca can you please clarify your intent with this edit, see Jeffrey's question:

> The block is version specific, though, and only targets an old version of Intune. What's the scenario where this is actually causing a functional break to Intune?

**Comment by aczechowski** [comment]
Sent internal email to followup

**Comment by vinaypamnani-msft** [comment]
Closing this PR per internal thread.

**Pull request closed without merging**
