### PR TITLE
Update kernel-dma-protection-for-thunderbolt.md

### PR DESCRIPTION
**Pull request by msbemba**
Made changes to the driver requirements/

### CODE REVIEW

**Comment by mypil** [comment]
@AaDake - can you please assist to check, approve and merge the content for this PR based on issue #2947?

Thank you.

**Comment by AaDake** [comment]
> Made changes to the driver requirements/
The link to the OEM documentation is: https://partner.microsoft.com/en-us/dashboard/collaborate/packages/4142

**Comment by mypil** [comment]
@msbemba - please check on the comment from AaDake and do the needful. Thanks.

**Comment by illfated** [comment]
Is the page https://partner.microsoft.com/en-us/dashboard/collaborate/packages/4142 restricted or limited to allow only Microsoft employees?
When I click the link, my browser redirects me to https://partner.microsoft.com/en-us/dashboard/directory , no matter what I do.

**Comment by msbemba** [comment]
@illfated  You can try to register yourself under Microsoft collaborate and then navigate to the desired URL

**Comment by Justinha** [comment]
I misunderstood this one. I thought we were removing the reference to the link and merged that change before AaDake provided the correct link to the Partner Center. So I've added the link from AaDake to our private repo on my side and that should publish later this morning. Thanks to everyone here for their help!

**Comment by illfated** [comment]
I don't think you misunderstood the intention in the PR.
AaDake provided the new/missing link after the merge.
Fair job from what I can see. Thanks for the follow-up.

**Pull request merged**
