### PR TITLE
removed outdated videos

### PR DESCRIPTION
**Pull request by MaratMussabekov**
https://github.com/MicrosoftDocs/windows-itpro-docs/issues/9043

### CODE REVIEW

**Comment by MaratMussabekov** [comment]
Dear @JohanFreelancer9,
kindly do the copy editor review for this PR.

Dear @nam31, for your information

Thank you

**Review by JohanFreelancer9 — APPROVED** [review]

**Comment by nam31** [comment]
@Dansimp PR has been copyedited and is ready for final review, could you please check and merge? Thanks!

**Comment by adirdidi** [comment]
Being discussed with marketing. The video may stay.

**Comment by adirdidi** [comment]
Marketing are already working on updating the videos. The links stay.

**Comment by illfated** [comment]
Thanks. Nice to know.

**Pull request closed without merging**
