### PR TITLE
update detect-block-potentially-unwanted-apps-windows-defender-antivi…

### PR DESCRIPTION
**Pull request by MaratMussabekov**
…rus.md
issue #1967, added windows defender antivirus into "Applies to" section
source: https://www.winhelponline.com/blog/defender-enable-pua-pup-adware-protection/

### CODE REVIEW

**Comment by mypil** [comment]
@Justinha - Can you please assist to check, approve and merge the content of this PR based on issue #1967?

Thank you.

**Comment by mypil** [comment]
@Justinha - We would like to follow up. Can you please assist to check, approve and merge the content of this PR based on issue #1967?

Thank you.

**Comment by mypil** [comment]
@Justinha - Would you be able to merge the PR content?

**Comment by Justinha** [comment]
@mypil sorry for delay. the change looks good to me but I think @mjcaparas or @DaniHalfin should approve.

**Comment by mjcaparas** [comment]
No. Microsoft Defender Antivirus is not an official product name. It's still Windows Defender Antivirus. 
Also, technically Windows Defender Antivirus is part of the Microsoft Defender ATP platform so saying that it applies to Microsoft Defender ATP means that it also applies to Windows Defender Antivirus.

**Comment by mypil** [comment]
@MaratMussabekov - please make the recommended changes to the PR as suggested by @mjcaparas. Thank you.

**Comment by MaratMussabekov** [comment]
Dear @mjcaparas ,
thank you for your review! 
Dear @mypil, if I understand it correctly, there is no need to make change to PR, as the PR is not necessary ("WDAV is part of MDATP. No need for specific mention")
I think issue #1967 could be closed as well
Thank you

**Pull request closed without merging**
