### PR TITLE
Text Update

### PR DESCRIPTION
**Pull request by joinimran**
The syntax in the document doesn't reflect the correct syntax that can be used. I have updated the syntax. 

Problem: https://github.com/MicrosoftDocs/windows-itpro-docs/issues/8989

### CODE REVIEW

**Comment by joinimran** [comment]
@JohanFreelancer9 - kindly do the copy editor review for this PR. Thanks.

**Review by JohanFreelancer9 — APPROVED** [review]

**Comment by illfated** [comment]
Just a note about the preceding documentation: Line 430 states the following:

`If you don’t use proxy servers, you must also include the "," delimiter just before the "|".`

The change made in this PR seems to go against that statement. Should it be removed, if testing has proved it to be incorrect?

**Review by illfated — APPROVED** [review]
Looks quite OK and in accordance with the issue ticket. 2 questions. though:
1. Should the last comma be removed too?
2. Any plans to adapt the affected text above?

**Comment by nam31** [comment]
@Dansimp, PR has been copyedited and is ready for final review, could you please check and merge? Thanks!

**Pull request merged**
