### PR TITLE
CI103175

### PR DESCRIPTION
**Pull request by Deland-Han**
This is a known issue with MBR2GPT.exe. See [103175](https://dev.azure.com/ContentIdea/ContentIdea/_queries/edit/103175/?triage=true) for details.

### CODE REVIEW

**Comment by Deland-Han** [comment]
#sign-off

**Comment by e0i** [comment]
@greg-lindsay A new PR that supplements a new known issue to the document is available for review. Thanks.

**Comment by e0i** [comment]
@greg-lindsay Any updates with the PR? Thanks.

**Comment by e0i** [comment]
@greg-lindsay Any updates with this community contributed PR? We'd like to follow-up. Thanks.

cc @laurawi

**Pull request merged**
