### PR TITLE
update headers to support In This Article

### PR DESCRIPTION
**Pull request by ChadSimmons**
Update headers to support "In This Article" like newer documentation such as https://docs.microsoft.com/en-us/mem/intune/protect/security-baselines-configure

### CODE REVIEW

**Review by yanezerick — APPROVED** [review]

**Comment by illfated** [comment]
I presume this change will add the H2 sections to the "In This Article" link section, but I don't remember if they will be linkable individually, thereby losing their anchors. I defer to the MS Docs team members for approval of the current format of changes in this PR.

**Comment by ChadSimmons** [comment]
@illfated That is the goal.  It should make reading and navigation much easier.

**Review by JohanFreelancer9 — APPROVED** [review]

**Review by illfated — APPROVED** [review]

**Comment by ChadSimmons** [comment]
It doesn't appear that the updates have been pushed to the production branch as there is no visible change on the public web page.

What's the publication timeframe? I know edits I make to the MEM docs (ConfigMgr / Intune, etc.) are generally 1 day after they are approved.

Thank you

**Comment by illfated** [comment]
@Dansimp : Sorry for pinging you, I am aware that your schedule is quite full already.
Would you have time to review and merge this PR?

**Comment by illfated** [comment]
#sign-off

**Comment by ChadSimmons** [comment]
Looks great!   Thank you.

**Comment by illfated** [comment]
Thank you for the PR. I presume the document is up to MS standards now.

**Pull request merged**
