### PR TITLE
remove comma "," when not using proxy

### PR DESCRIPTION
**Pull request by VLG17**
https://github.com/MicrosoftDocs/windows-itpro-docs/issues/9095

Tests showed that comma after URL is not needed when no proxy is used.

### CODE REVIEW

**Comment by nam31** [comment]
@JohanFreelancer9 please do the copy editor review for this PR.
Thank you

**Review by JohanFreelancer9 — APPROVED** [review]

**Review by illfated — APPROVED** [review]
Thank you. The correction update looks very good to me.

**Comment by illfated** [comment]
#sign-off

**Comment by nam31** [comment]
@Dansimp PR has been copyedited and is ready for final review, could you please check and merge? Thanks!

**Comment by VLG17** [comment]
> #sign-off

@illfated could you please help me with the conflicts? I don't know what i need to remove/change to resolve the conflicts.

**Comment by illfated** [comment]
https://github.com/VLG17/windows-itpro-docs/tree/patch-126 : This branch is 1 commit ahead, 1024 commits behind MicrosoftDocs:public.

It may just as well be easier to close this PR and create a new one based on the existing document page.
Had you been using any Git tools to keep your branches updated, it might have been easier to give advice.

**Comment by illfated** [comment]
I mean, I could try editing your PR branch document and see if it would be possible to update it to current content, but it could also cause a lot of merge conflicts in my tree/fork/branch tool "Git Extensions", simply because of the amount of changes this page has been through in the meanwhile.

**Pull request closed without merging**
