### PR TITLE
defined credentials

### PR DESCRIPTION
**Pull request by VLG17**
https://github.com/MicrosoftDocs/windows-itpro-docs/issues/1240

### CODE REVIEW

**Comment by mypil** [comment]
@JohanFreelancer9 - kindly do the copy editor review for this PR. Thanks.

**Comment by mypil** [comment]
@DaniHalfin - can you please assist to check, approve and merge the content for this PR based on issue #1240?

Thank you.

**Comment by mypil** [comment]
@DaniHalfin  - I would like to follow up on this. Can you please assist to check, approve and merge the content for this PR based on issue #1240?

Thank you.

**Comment by DaniHalfin** [comment]
This looks good. Checking with team to verify.

**Comment by DaniHalfin** [comment]
Upon talking to the PM owner, I think it's better to clarify further.
Add a note that clarifies that with Windows 10, version 1703 and newer, supplied credentials are used to obtain a Kerberos ticket, which in turn is sent to the remote device.

Use the following formatting for the note : 
```
> [!NOTE]
> Text
```

**Comment by DaniHalfin** [comment]
@SteveSyfuhs FYI

**Comment by SteveSyfuhs** [comment]
The original text is technically correct. Supplied credentials refers to how to derived Kerberos ticket is acquired, not what is sent to the remote machine. I would propose removing the bracketed text and adding something to the effect of 

"...which is sent to the remote device. This allows users to run as different users without having to send credentials to the remote machine."

Or similar.

**Comment by mypil** [comment]
@VLG17 - Please see the comments from DaniHalfin and SteveSyfuhs. Kindly make the recommended changes to the PR you created. Thank you.

**Comment by mypil** [comment]
@DaniHalfin - I would like to follow up on this. Can you please assist to check, approve and merge the content for this PR based on issue #1240?

Thank you.

**Comment by mypil** [comment]
@DaniHalfin - I would like to follow up on this. Can you please assist to check, approve and merge the content for this PR based on issue #1240?

@AndreaBarr @kenwith - Would you be able to merge the content of this PR?

Thank you.

**Comment by mypil** [comment]
@DaniHalfin - I would like to follow up on this. Can you please assist to check, approve and merge the content for this PR based on issue #1240?

@AndreaBarr @kenwith - Would you be able to merge the content of this PR?

Thank you.

**Pull request merged**
