### PR TITLE
SetupDiag link fixed

### PR DESCRIPTION
**Pull request by Malind19**
Removed .md from the link

### CODE REVIEW

**Comment by mypil** [comment]
@greg-lindsay @TrudyHa - can you please assist to check, approve and merge the content for this PR based on issue #2631?

Thank you.

**Comment by jdeckerms** [comment]
@Malind19 If the link isn't working, the problem is something other than the file suffix. When we link within a project (as opposed to a URL), we must include the .md suffix. In this case, I think the issue is with the relative path. Rather than change it in your pull request, I'm going to fix the link on our side (quicker to publish that way). Thanks for pointing out that the link doesn't work.

**Comment by Malind19** [comment]
@jdeckerms Ok thanks. When I removed the .md suffx it worked. Same happened with another issue.

**Comment by illfated** [comment]
@Malind19 : The problem seems to be that the migration process copying the Github version of the document (containing the link with the `.md` suffix) to the docs.microsoft.com site did not remove the .md suffix, even though it is supposed to do so. This error needs to be fixed by Microsoft internal technicians with access to the public pages, because the Github pages need the .md suffix.

**Pull request closed without merging**
