### PR TITLE
Microsoft Edge/kiosk mode: broken relative links

### LINKED ISSUE #4275: Thumbnail images not available on "Deploy Microsoft Edge kiosk mode" page
The images (https://docs.microsoft.com/en-us/images/Picture1.png) linked in this page give a 404.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f840fa14-a379-d297-c3f7-ada05ec299d6
* Version Independent ID: 81396f7b-7506-43cd-fd9a-4066719a6eb2
* Content: [Deploy Microsoft Edge kiosk mode](https://docs.microsoft.com/en-us/microsoft-edge/deploy/microsoft-edge-kiosk-mode-deploy)
* Content Source: [browsers/edge/microsoft-edge-kiosk-mode-deploy.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/master/browsers/edge/microsoft-edge-kiosk-mode-deploy.md)
* Product: **edge**
* Technology: **microsoft-edge**
* GitHub Login: @eavena
* Microsoft Alias: **eravena**

### PR DESCRIPTION
**Pull request by illfated**
**Description:**

The 4 images in the subsection "Supported configuration types" are supposed to be linked to their image files,
but the relative links have been broken by not containing the needed parent directory dots.

**Proposed change:**

Add the required parent directory dots to enable the links to point to the files as intended (even if not strictly needed to begin with).

It may not be easy to spot the changes due to the text layout and HTML linking format,
so a meta-diff for the 4 individual link changes should be more useful:
```diff
- |**Single-app**<p><a href="/images/Picture1.png" alt="Full-sized view single-app
+ |**Single-app**<p><a href="../images/Picture1.png" alt="Full-sized view single-a

- <p>&nbsp;<p><a href="/images/Picture2.png" alt="Full-sized view single-app
+ <p>&nbsp;<p><a href="../images/Picture2.png" alt="Full-sized view single-a

- | **Multi-app**<p><a href="/images/Picture5.png" alt="Full-sized view multi-app
+ | **Multi-app**<p><a href="../images/Picture5.png" alt="Full-sized view multi-a

- <p>&nbsp;<p><a href="/images/Picture6.png" alt="Full-sized view multi-app
+ <p>&nbsp;<p><a href="../images/Picture6.png" alt="Full-sized view multi-a
```

**Issue ticket reference or closure:**

Closes #4275

### CODE REVIEW

**Comment by e0i** [comment]
cc @jvsam (via `#4285`)

**Comment by jvsam** [comment]
Hi @nenonix and @JohanFreelancer9 for copy review, as per process. Thank you.

**Comment by jvsam** [comment]
Hi @eavena this pull request has been copy edited and is ready for your final review and approval. Please let us know if there are outstanding issues to be resolved prior to merge. Thank you. See: [commits](https://github.com/MicrosoftDocs/windows-itpro-docs/pull/4325/commits) and [changes](https://github.com/MicrosoftDocs/windows-itpro-docs/pull/4325/files).

**Comment by jvsam** [comment]
Hi again @eavena, kindly review this pull request when time permits. Thank you.

**Comment by jvsam** [comment]
Hi again @eavena how are you? Can you please review this PR and merge if there are no issues? Thank you.

Hi @AndreaBarr can you help us with this? Thank you in advance.

**Comment by jvsam** [comment]
Thank you @AndreaBarr for your help.

**Pull request merged**
