### PR TITLE
Microsoft Defender ATP: amend broken link

### LINKED ISSUE #4832: Get started hyperlink is broken
Not working

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2bdb99e4-289a-c09a-c35c-2774fc52a402
* Version Independent ID: 4d325389-c9b8-2601-0ff4-c7b6bf5a6c28
* Content: [Microsoft Defender Advanced Threat Protection](https://docs.microsoft.com/en-us/windows/security/threat-protection/microsoft-defender-atp/microsoft-defender-advanced-threat-protection)
* Content Source: [windows/security/threat-protection/microsoft-defender-atp/microsoft-defender-advanced-threat-protection.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/master/windows/security/threat-protection/microsoft-defender-atp/microsoft-defender-advanced-threat-protection.md)
* Product: **w10**
* Technology: **windows**
* GitHub Login: @mjcaparas
* Microsoft Alias: **macapara**

### PR DESCRIPTION
**Pull request by illfated**
**Description:**
The link "Get started" at the end of the page "Microsoft Defender Advanced Threat Protection" points to a non-existing page.
It may have been renamed and the name "Get started" appropriated as one of the expandable sections in the left hand side index/TOC section.

**Proposed changes:**
The suggested change is to replace the broken link `get-started.md` with `minimum-requirements.md` found at the same directory level.

Broken link:
- https://github.com/MicrosoftDocs/windows-itpro-docs/blob/master/windows/security/threat-protection/microsoft-defender-atp/get-started.md

Replacement link:
- https://github.com/MicrosoftDocs/windows-itpro-docs/blob/master/windows/security/threat-protection/microsoft-defender-atp/minimum-requirements.md

I have also included a few MarkDown blockquote spaces where a single space was missing.

**issue ticket closure or reference:**
Closes #4832

Thanks to @xNiklasJern for discovering the broken link.

### CODE REVIEW

**Comment by illfated** [comment]
As usual, the easy way to view the effective change is to use the Rich Text Diff view:
https://github.com/MicrosoftDocs/windows-itpro-docs/pull/4891/files?short_path=04dc23c#diff-04dc23c15a739fe2ab8ee75db77d6a4c

**Comment by jvsam** [comment]
Hello @mjcaparas this pull request is ready for your review. Please approve and merge if there are no issues. Thank you.

**Comment by DaniHalfin** [comment]
The default branch for this repository has changed. Commenting to remember to merge this to the new default, if this PR gets merged.

**Comment by e0i** [comment]
@illfated 

The default branch for this repository has changed from `master` to `public`. Please edit your pull request to change the merge target to `public` via the `Edit` button at the top right corner. Thanks.

**Comment by illfated** [comment]
Thank you for approving this PR. Would you also be able to merge it, 
or does this content need additional review?

**Comment by jvsam** [comment]
Hi @mjcaparas, it appears all is good. Can you please merge this PR? Thank you.

**Pull request merged**
