### PR TITLE
Update deploying-the-app-v-51-server.md

### PR DESCRIPTION
**Pull request by baardhermansen**
Added markdown for Important and Notes.
Removed extra line shifts.

### CODE REVIEW

**Comment by baardhermansen** [comment]
> Will be interesting to see whether or not the removal of blank lines at the end will have any effect on the Feedback section on the docs.microsoft.com page.

It shouldn't, should it? Don't recall seeing that many number of line shifts on other, newer, pages. I've only encountered those on older style formatted docs.

**Comment by illfated** [comment]
I know, normally it should not. I just looked at a completely different page, which I also had not checked before the PR update, but found that the page did not have a Feedback section. Maybe I am just overthinking this and perhaps the problem does not exist at all. (Maybe I should have posted a question if that docs.microsoft.com page was supposed to have a Feedback section or not.)

**Comment by baardhermansen** [comment]
A page that can be edited but doesn't have a Feedback section? That's a combination i've never seen before. On pages that are either well and truly old or for some reason editing is not desired, both Edit and Feedback is missing.

**Comment by illfated** [comment]
Thanks for the details. I will keep that in mind and see if I can trace my way back to the PR where I found the page to be missing the Feedback section.

**Pull request merged**
