### PR TITLE
Added the most asked question about windows 10

### PR DESCRIPTION
**Pull request by rahulkumarsingh73690**
Added the most asked question about Windows 10 (what is the pc requirement for installing windows 10)

### CODE REVIEW

**Comment by rahulkumarsingh73690** [comment]
> Added the most asked question about Windows 10 (what is the pc requirement for installing windows 10)

Please Check and Merge @shortpatti

**Comment by illfated** [comment]
Microsoft Docs will not accept a non-Microsoft link unless it is a partner link (and labeled as such).
Please use https://www.microsoft.com/windows/windows-10-specifications#primaryR2 instead.

**Comment by rahulkumarsingh73690** [comment]
Is going through shortlink allowed or not? I am just trying to know how much clicks going throw my link..

That's all Noting Else More.

**Comment by jdeckerms** [comment]
@rahulkumarsingh73690 Use the full URL (without language codes). Do not use link shorteners.

**Comment by illfated** [comment]
@rahulkumarsingh73690 : Just so you know, only Microsoft internals have access to Microsoft.com domain URL shortening.
For all us others, we have to stick with full-length URLs when contributing to Microsoft Docs.
(And contributed material becomes Microsoft property, no longer your personal property.)

**Comment by rahulkumarsingh73690** [comment]
Sorry. Microsoft have own URL shortner or not?

**Comment by jdeckerms** [comment]
@rahulkumarsingh73690  I'm closing this pull request without merging. If you want to resubmit it, please use the full URL, without a language code.

**Comment by jdeckerms** [comment]
to clarify about the language code: 

This URL is okay: https://www.microsoft.com/windows/windows-10-specifications
This URL is not: https://www.microsoft.com**/en-us**/windows/windows-10-specifications

**Comment by illfated** [comment]
@rahulkumarsingh73690 : Just to clarify, regarding your question about Microsoft's own URL shortener:
Only Microsoft employees (specific ones with database access) can create Microsoft short URLs.
When needed, Microsoft will replace frequently used URLs with shortened ones.
That usually happens on official .com pages, but rarely in pure documentation pages.
For all us others, we can only use the normal URLs like mentioned above.

**Comment by rahulkumarsingh73690** [comment]
Okay no problem I am just confirming about Microsoft URL Shortner.

**Comment by illfated** [comment]
Not that I know of, I have not seen any publicly open and available Microsoft URL shortener yet.
I can only hope there will be one in the future, because it saves some space when editing longer lines
of documentation. especially when editing bigger chunks of text where the long URLs have a tendency
to make the text less readable during editing.

And as mentioned earlier, we can only use official Microsoft links in Microsoft Documentation pages.

**Comment by egallagh** [comment]
I like that the Microsoft URL shortener has very narrow availability. I can let those go through my security. We block URLs shortened by publicly available shorteners because they are being used by bad actors to obfuscate links in malicious emails.

**Comment by illfated** [comment]
Just a brainstorming idea: Would it be possible for Microsoft to configure/define/develop the URL shortener to only accept official Microsoft sites as input to keep it safe?

**Pull request closed without merging**
