### PR TITLE
Addition of add-on license option

### PR DESCRIPTION
**Pull request by guygregory**
Included additional option for licensing Microsoft Defender ATP, and link to announcement of the add-on SKU for M365 E3: https://www.microsoft.com/microsoft-365/blog/2019/01/02/introducing-new-advanced-security-and-compliance-offerings-for-microsoft-365/

### CODE REVIEW

**Comment by illfated** [comment]
#sign-off

**Comment by e0i** [comment]
Closing based on the review of the document author.

**Comment by guygregory** [comment]
Hi @mjcaparas, please could we get a second opinion on this? In my pull request, I linked to the announcement from Ron Markezich which says that Microsoft Defender ATP (formerly known as Windows Defender ATP) is available as part of the add-on security license. Happy to discuss offline with the M365 marketing team if necessary. Thanks! Guy (gugregor)

**Comment by guygregory** [comment]
@mjcaparas - I’ve also checked another resource that confirms Microsoft Defender ATP is included in the Identity & Threat Protection step-up SKU:
https://www.microsoft.com/microsoft-365/partners/resources/e5-security-and-compliance-offering-partner-faq

In the FAQ it mentions “Windows Defender ATP”, but as I’m sure you’re aware, this was renamed to Microsoft Defender ATP in March this year:
https://www.microsoft.com/security/blog/2019/03/21/microsoft-defender-atp-for-mac-new-threat-and-vulnerability-management-capabilities/

**Pull request closed without merging**
