### PR TITLE
Minor Changes for Consistency

### PR DESCRIPTION
**Pull request by AdamGrossTX**

### CODE REVIEW

**Comment by illfated** [comment]
Please note: Your PR targets the [`MicrosoftDocs:master`](https://github.com/MicrosoftDocs/windows-itpro-docs/tree/master) branch instead of the [`MicrosoftDocs:public`](https://github.com/MicrosoftDocs/windows-itpro-docs/tree/public) branch.
Please be aware of the potential consequences, which may include delayed migration to the docs.microsoft.com pages.

Current master branch status: This branch is 8 commits ahead, 413 commits behind public.

**Comment by e0i** [comment]
@AdamGrossTX We'll move forward with the PR when the target branch is changed to `public`. You may change the target branch by simply clicking `Edit` at the top right corner of the PR and clicking the branch link. Thanks.

**Comment by AdamGrossTX** [comment]
Ok. Changes the target. Please let me know if I need to do anything else.

**Comment by illfated** [comment]
@e0i : Looks like we are ready for final review by the manager (Daniel Simpson).

**Comment by e0i** [comment]
@illfated Will be ready after copy review. Thanks.

@nenonix @JohanFreelancer9 Copy editing is needed for this PR. Thanks.

**Comment by e0i** [comment]
@Dansimp The PR that has passed copy and technical review by the document author is ready to be merged. Thanks.

**Pull request merged**
