### PR TITLE
Windows Sandbox configuration: Organization

### PR DESCRIPTION
**Pull request by skycommand**
- Use Markdown heading syntax instead of the bold and italic syntax
- Add "Creating a configuration file" section
- Add "Using a configuration file" section
- Fix language code for code snippets; "shell" is for Bash sessions only

### CODE REVIEW

**Review by illfated — COMMENTED** [review]
- [X] **Normal source view:** https://github.com/MicrosoftDocs/windows-itpro-docs/pull/8641/files
- [X] **Hide whitespace changes:** https://github.com/MicrosoftDocs/windows-itpro-docs/pull/8641/files?diff=unified&w=1
- [X] **Rich diff view:** https://github.com/MicrosoftDocs/windows-itpro-docs/pull/8641/files?diff=unified&w=1&short_path=b9328b9#diff-b9328b9edfa6a54a31b8de3ba5b2065b929a2157bf8c50a72af44fa04087ead1

**Review by illfated — APPROVED** [review]
Looks pretty good to me. Remaining question: Would it be more precise to have Example 1 & Example 2 as H3 headings and their subsections as H4 headings?

**Comment by skycommand** [comment]
I thought the same thing. I originally intended to make them a sub-heading of the "Creating a configuration file" section. But when I wanted to file the PR, I asked people around me for feedback. (Since the COVID-19 pandemic, there are more people around me. Sometimes, asking for feedback takes a few minutes.) They didn't think so. As they saw it, those sections were examples of "Windows Sandbox configuration" not examples of creating them.

Of course, the way they are, they have the advantage of being included in the article's TOC on Microsoft Docs.

**Comment by illfated** [comment]
Well reasoned. I concur.

**Comment by illfated** [comment]
#sign-off

**Review by denisebmsft — APPROVED** [review]
thank you

**Comment by skycommand** [comment]
Any time! 😊

**Pull request merged**
