### PR TITLE
removed broken link. added correct link

### PR DESCRIPTION
**Pull request by RAJU2529**
as per the user report #8351 . so I removed invalid link , added correct link.
This PR editied using Android smartphone.

### CODE REVIEW

**Comment by MissWorld666** [comment]
oh thank all of you for all the reactions and actions I'm putting you on the days platform discovering pretty much things and basically also a lot of cyber web and I TO games so I'm so far not equipped with android I am somehow on the other side of the line but I'm sure it's really interesting and I look forward to just some interesting interaction again thank you love you take care

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by illfated** [comment]
@e0i : The previous comment appears to be a spam message unrelated to this PR. Could you check if there is some way to minimize or remove the comment?

**Review by illfated — APPROVED** [review]
The link update appears to be quite correct. Thank you for providing this update.

**Comment by illfated** [comment]
@denisebmsft : knowing that you have got access rights to merge pull requests like this, would it be possible for you to remove the unwanted spam comment in this PR?

**Comment by e0i** [comment]
@JohanFreelancer9 Copy editing is needed for this PR. Thanks.

**Pull request merged**
