### PR TITLE
Update index.md

### PR DESCRIPTION
**Pull request by essdeekay**
Typo - corrected 'Diagnotic' to 'Diagnostic'

### CODE REVIEW

**Comment by e0i** [comment]
@AndreaBarr A PR with a minor typo fix is available for review. Thanks.

**Comment by AndreaBarr** [comment]
@essdeekay please correct the conflicts so that I can merge this.

**Comment by illfated** [comment]
@essdeekay : will you be able to rebase your PR or merge the master branch into your PR branch?
Or would you prefer a PR to your own repository to get the file conflict resolved?

**Comment by e0i** [comment]
@essdeekay Would you be able to resolve merge conflicts? We would like to merge this contribution. Thanks.

**Comment by illfated** [comment]
With the current vacation season in mind, it could be the case for @essdeekay to be on vacation this week (and maybe more). We may need to have some patience with this PR.

**Comment by e0i** [comment]
@essdeekay Following up for updates.

**Comment by e0i** [comment]
@essdeekay 

Closing  PR as there has been no response regarding revisions. Feel free to  re-submit the PR so that your contributions can be merged. Thanks.

**Comment by e0i** [comment]
@officedocsbot close

**Pull request closed without merging**
