### PR TITLE
update content of upgrade mbam2.5 sp1

### PR DESCRIPTION
**Pull request by TobyTu**

### CODE REVIEW

**Comment by TobyTu** [comment]
@greg-lindsay I see the article is not live on Docs, could you help check this?

**Comment by illfated** [comment]
While waiting for a reply from the document owner, I can only verify
that your contributed content is not yet live on docs.microsoft.com .

Currently, your content is only available on the Github master branch,
https://github.com/MicrosoftDocs/windows-itpro-docs/blob/master/mdop/mbam-v25/upgrade-mbam2.5-sp1.md ,
but it may take a couple of days more before it migrates to the public page,
https://docs.microsoft.com/en-us/microsoft-desktop-optimization-pack/mbam-v25/upgrade-mbam2.5-sp1

**Comment by TobyTu** [comment]
@illfated Thanks for checking, yes, it's live on the master branch, but not on docs.microsoft.com, hope @greg-lindsay can help fix it.

**Comment by illfated** [comment]
Fair enough. Normally, it _can_ take up to 7 days (although it should take less), so we can only presume something is holding it back from the script queue to be migrated. Should it last 8 days or more, From what I have noticed, Greg Lindsay is often quite busy, so I can only hope he can "chime in" with news about how much time it will take before your contribution gets migrated.

**Comment by greg-lindsay** [comment]
I have just initiated a pull from pull https://github.com/microsoftdocs/windows-itpro-docs into a branch off the private master and a push to preview. Assuming the preview doesn't have any errors to correct I will submit a private PR to get this into the public page.

FYI, I know the terms public and private a confusing in this context because the public repo doesn't public to the public page, only the private repo does :)  Bottom line is hopefully this will go live today.

**Comment by greg-lindsay** [comment]
There were 3 warnings and 5 suggestions. The warnings are the only things that are of concern and they refer to invalid graphics links in the file "introduction-page-file.md" I'll see if I can fix these.

**Pull request merged**
