### PR TITLE
Update hello-hybrid-cert-trust-prereqs.md

### PR DESCRIPTION
**Pull request by secherka**
To avoid customers and support engineers confusion I would recommend following change in the mentioned part of the documentation (replace first two sentences):
Windows Hello for Business hybrid certificate trust requires Active Directory being federated with Azure Active Directory and needs Windows Server 2016 Active Directory Federation Services or newer. Windows Hello for Business hybrid certificate trust doesn’t support Managed Azure Active Directory using Pass-through authentication or password hash sync.

### CODE REVIEW

**Comment by mapalko** [comment]
@DaniHalfin to review the change.

**Comment by DaniHalfin** [comment]
I think there's a middle ground here. The inital text does some explaning that provides context, before going into requirement and what's not supported. I would like to keep that first part in for context and state requirements and unsuppored scenario more clearly (as done in the change) after.
@secherka

**Comment by DaniHalfin** [comment]
and also, thanks for taking the time to contribute here!!

**Comment by secherka** [comment]
If I understood correct, you want to keep the first sentence for general education and just replace second sentence with proposed two sentences?

**Pull request merged**
