### PR TITLE
Update controlled-folders.md

### PR DESCRIPTION
**Pull request by amirsc3**
Some customers opened support tickets wanting to know why CFA blocks did not create alerts in our portal... so I think we should add this note to avoid customer confusion...

### CODE REVIEW

**Review by denisebmsft — APPROVED** [review]
Thank you @amirsc3

**Comment by illfated** [comment]
Nice update. Thank you! 👍🏻

**Comment by beerisgood** [comment]
Isn't 
> Protect important folders **against** ransomware 

Instead of
> Protect important folders from ransomware 

Better?

**Comment by illfated** [comment]
Sure, it is slightly better and more precise from a grammar perspective. Then again, it is almost on a nuance level.

**Pull request merged**
