### PR TITLE
Fixing typo in Federation with Azure Section

### PR DESCRIPTION
**Pull request by mapalko**
You cannot deploy both password sync and PTA in the same environment. The changed statement is being fixed to reflect either can be deployed but not both.

### CODE REVIEW

**Comment by illfated** [comment]
Nice, `and/or` logic switch. 👍 😄

**Comment by e0i** [comment]
@DaniHalfin This PR that has been created by the content author themselves could probably be merged. Thanks.

**Comment by illfated** [comment]
@mapalko : Would you mind rebasing your PR branch to align your change with current content?

**Comment by e0i** [comment]
@DaniHalfin This PR that has been created by the content author themselves could probably be merged. Thanks.

**Comment by illfated** [comment]
Merging this PR will most likely trigger a merge conflict that needs to be resolved.
([`This branch`](https://github.com/mapalko/windows-itpro-docs/tree/patch-5) is 1 commit ahead, 2130 commits behind [`MicrosoftDocs:master`](https://github.com/MicrosoftDocs/windows-itpro-docs).)

**Comment by e0i** [comment]
@lizap This PR that has been created by the content author themselves could probably be merged. Thanks.

**Comment by e0i** [comment]
@mjcaparas @dansimp @lizap This PR that has been created by the content author themselves (Matthew P.) could probably be merged. Thanks.

**Comment by e0i** [comment]
@mjcaparas @lizap Following up for updates.

**Comment by e0i** [comment]
@mapalko Would you be able to resolve conflicts so that the approved contributions be merged? Thank you.

**Comment by Dansimp** [comment]
resolved conflict w what was in patch branch. Can revert back if needed.

**Comment by e0i** [comment]
@Dansimp Thank you.

**Pull request merged**
