### PR TITLE
Fixing formatting of some paragraphs

### PR DESCRIPTION
**Pull request by jonyee**

### CODE REVIEW

**Comment by e0i** [comment]
@jonyee Thank you for your contributions. Would you be able to resolve the merge conflicts to proceed with the review?

**Comment by illfated** [comment]
@jonyee : Nice, good job correcting the whitespace formatting.
Can I ask you to add MarkDown quote indent marker compatibility space (1 blank space) in your modified content?
If yes, are you able to edit and modify the notes yourself, or would you like me to add Github merge suggestions for the lines I am talking about?

Example:
```diff
- >[!Important]
+ > [!Important]
- >Note that if you have [Office diagnostic data viewing enabled](#view-office-diagnostic-data), the Office data history is fixed at 1 GB and cannot be modified.
+ > Note that if you have [Office diagnostic data viewing enabled](#view-office-diagnostic-data), the Office data history is fixed at 1 GB and cannot be modified.
```

**Comment by jonyee** [comment]
@illfated Sure - I added the spaces.  Let me know if that looks right.  The github preview doesn't really look the same as on msdn, so I'm not sure if the markdown is correct, but I think it should be an improvement.

**Comment by illfated** [comment]
Note to the document author: there is a missing image for the following link:
```
![Change the size of your data history through the app settings](images/ddv-change-db-size.png)
```
There is no image file named `ddv-change-db-size.png` in https://github.com/MicrosoftDocs/windows-itpro-docs/tree/public/windows/privacy/images

If you want that image to be part of the document, it needs to be added to the /windows/privacy/images/ directory.

**Pull request merged**
