### PR TITLE
Update waas-delivery-optimization.md

### PR DESCRIPTION
**Pull request by davguent**
Updated to specifically add PRO SKU which offers same functionality.  Current revision implies Windows Pro doesn't support DO which is not correct.

### CODE REVIEW

**Comment by jaimeo** [comment]
@davguent, have you confirmed this with the PM?

**Comment by jaimeo** [comment]
PM confirmed.

**Comment by davguent** [comment]
I was onsite this week with UPS and discovered they were using Windows 10 Pro.  I reached out to Narkis Engler naengler@microsoft.com<mailto:naengler@microsoft.com> who confirmed Windows 10 Pro support.  My pull request is to simply provide this clarification on their behalf to reduce confusion in omission meaning its not supported.

Dave Guenthner

**Comment by illfated** [comment]
Thank you for this update. Funny how obvious this looks now, because I have noticed this setting in default Windows 10 Pro (not Enterprise) for quite some time now, working in a small business office (20-25 computers).

**Pull request merged**
