### PR TITLE
Update credential-guard.md: remove link to retired MVA course

### LINKED ISSUE #3796: Video link is no longer valid
MVA course in the link is retired.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 87ec66f8-6598-5751-a10f-55951c08b3ff
* Version Independent ID: c3bb99fb-ec6f-638f-fb26-af3142f5d49c
* Content: [Protect derived domain credentials with Windows Defender Credential Guard (Windows 10)](https://docs.microsoft.com/en-us/windows/security/identity-protection/credential-guard/credential-guard#feedback)
* Content Source: [windows/security/identity-protection/credential-guard/credential-guard.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/master/windows/security/identity-protection/credential-guard/credential-guard.md)
* Product: **w10**
* Technology: **windows**
* GitHub Login: @DaniHalfin
* Microsoft Alias: **daniha**

### PR DESCRIPTION
**Pull request by illfated**
**Description:**

The linked video course from Microsoft Virtual Academy has been retired.

**Proposed change:**

Removing the link and the related text lines based on user report from @Scriptimus (Andrew Barnes).

Closes #3796

### CODE REVIEW

**Comment by e0i** [comment]
@DaniHalfin Would you review and merge this PR contributed by the community? Thanks.

**Comment by illfated** [comment]
Looks like I should reconsider removing the material and instead look for matching material to replace the existing link(s):
https://www.linkedin.com/learning/search?keywords=Deep+Dive+into+Windows+Defender+Credential+Guard

**Comment by e0i** [comment]
See: #3513

**Comment by illfated** [comment]
According to commit https://github.com/MicrosoftDocs/windows-itpro-docs/commit/1c2cfc87779b6432791196262572b5e61e4aba8c , the Deep Dive course is already retired, and no replacement course exists.

Based on this information, I leave the PR content as is, unless any team member recommends otherwise.

**Comment by illfated** [comment]
I have suggested to martyav that I close this PR, because his PR (#3875) seems more complete (more whitespace removal).

**Comment by illfated** [comment]
Closing this, since the other one is merged (problem solved).

**Pull request closed without merging**
