### PR TITLE
clarification about steps to be skipped added

### PR DESCRIPTION
**Pull request by MaratMussabekov**
#5243

### CODE REVIEW

**Comment by mypil** [comment]
@nenonix @JohanFreelancer9 - kindly do the copy editor review for this PR. Thanks.

**Comment by mypil** [comment]
@mapalko - PR has been copy edited and is ready for final review based on issue #5243.

Thank you.

cc: @kenwith

**Comment by illfated** [comment]
Same here. PM/DM follow-up is needed for the final merge operation.

**Comment by mypil** [comment]
@Dansimp - Please assist to merge this PR as approved by @mapalko.

Thank you.

cc: @kenwith

**Pull request merged**
