### PR TITLE
Update configure-proxy-internet-windows-defender-advanced-threat-prot…

### PR DESCRIPTION
**Pull request by nenonix**
…ection.md

Note added. Resolves https://github.com/MicrosoftDocs/windows-itpro-docs/issues/2784

### CODE REVIEW

**Comment by mypil** [comment]
@mjcaparas - can you please assist to check, approve and merge the content for this PR based on issue #2784?

Thank you.

**Comment by mjcaparas** [comment]
Please use the full product name Windows Defender ATP and not "WDATP".

**Comment by nenonix** [comment]
Thanks @mjcaparas - have done.

**Comment by mypil** [comment]
@mjcaparas - can you please assist to check, approve and merge the content for this PR based on issue #2784?

Thank you.

**Comment by mypil** [comment]
@mjcaparas - I would like to follow up on this. Can you please assist to check, approve and merge the content for this PR based on issue #2784?

Thank you.

**Pull request merged**
