### PR TITLE
Update bitlocker-csp.md

### PR DESCRIPTION
**Pull request by chblac**

### CODE REVIEW

**Comment by illfated** [comment]
Looks like all the issue tickets (https://github.com/MicrosoftDocs/windows-itpro-docs/issues?utf8=%E2%9C%93&q=%221fd9efc2-8946-75e4-27f3-95ac43a9d987%22&in=body) connected to this page (https://docs.microsoft.com/en-us/windows/client-management/mdm/bitlocker-csp) are closed already, so I presume this PR is not based on any known existing ticket.

**Review by illfated — APPROVED** [review]
Content swap between the error codes 2 and 7.
Looks OK to me, at least format-wise, as long as this correction has been verified internally.

**Comment by chblac** [comment]
+@Stan White<mailto:Stan.White@microsoft.com>, @Rahul Muthoo<mailto:ramuthoo@microsoft.com>

I submitted the change for the CSP documentation, but I don’t have an appropriate bug handy.  Can you guys confirm/approve?

Thanks,
Chris

**Comment by chblac** [comment]
@Chris<mailto:Christopher.Black@microsoft.com>, I am not sure how can I help here. Do you want us to create a documentation bug?

From: Chris Black (INTUNE) <Christopher.Black@microsoft.com>
Sent: Friday, December 11, 2020 11:29 AM
To: MicrosoftDocs/windows-itpro-docs <reply@reply.github.com>; MicrosoftDocs/windows-itpro-docs <windows-itpro-docs@noreply.github.com>; Stan White <Stan.White@microsoft.com>; Rahul Muthoo <ramuthoo@microsoft.com>
Cc: Author <author@noreply.github.com>
Subject: RE: [MicrosoftDocs/windows-itpro-docs] Update bitlocker-csp.md (#8775)

+@Stan White<mailto:Stan.White@microsoft.com>, @Rahul Muthoo<mailto:ramuthoo@microsoft.com>

I submitted the change for the CSP documentation, but I don't have an appropriate bug handy.  Can you guys confirm/approve?

Thanks,
Chris

**Comment by chblac** [comment]
I’m not sure either 😊  I hoped if you say “Yes, I own that and the change is correct”, that would either be sufficient or the “windows-itpro-docs” alias could tell us what else they need.

Chris

From: Rahul Muthoo <ramuthoo@microsoft.com>
Sent: Friday, December 11, 2020 11:45
To: Chris Black (INTUNE) <Christopher.Black@microsoft.com>; MicrosoftDocs/windows-itpro-docs <reply@reply.github.com>; MicrosoftDocs/windows-itpro-docs <windows-itpro-docs@noreply.github.com>; Stan White <Stan.White@microsoft.com>
Cc: Author <author@noreply.github.com>
Subject: RE: [MicrosoftDocs/windows-itpro-docs] Update bitlocker-csp.md (#8775)

@Chris<mailto:Christopher.Black@microsoft.com>, I am not sure how can I help here. Do you want us to create a documentation bug?

From: Chris Black (INTUNE) <Christopher.Black@microsoft.com<mailto:Christopher.Black@microsoft.com>>
Sent: Friday, December 11, 2020 11:29 AM
To: MicrosoftDocs/windows-itpro-docs <reply@reply.github.com<mailto:reply@reply.github.com>>; MicrosoftDocs/windows-itpro-docs <windows-itpro-docs@noreply.github.com<mailto:windows-itpro-docs@noreply.github.com>>; Stan White <Stan.White@microsoft.com<mailto:Stan.White@microsoft.com>>; Rahul Muthoo <ramuthoo@microsoft.com<mailto:ramuthoo@microsoft.com>>
Cc: Author <author@noreply.github.com<mailto:author@noreply.github.com>>
Subject: RE: [MicrosoftDocs/windows-itpro-docs] Update bitlocker-csp.md (#8775)

+@Stan White<mailto:Stan.White@microsoft.com>, @Rahul Muthoo<mailto:ramuthoo@microsoft.com>

I submitted the change for the CSP documentation, but I don’t have an appropriate bug handy.  Can you guys confirm/approve?

Thanks,
Chris

**Comment by illfated** [comment]
No worries. This PR will be reviewed, approved, and merged, either by the current document author or manager, depending on MS Docs team decisions.

**Comment by e0i** [comment]
@JohanFreelancer9 Copy editing is needed for this PR. Thanks.

**Review by JohanFreelancer9 — APPROVED** [review]

**Pull request merged**
