### PR TITLE
More details on Allowed and Not Allowed

### PR DESCRIPTION
**Pull request by MandiOhlinger**
Worked with Defender AV PM to explain what **Allowed** and **Not Allowed** do for the following CSPs:

Defender/AllowArchiveScanning
Defender/AllowBehaviorMonitoring
Defender/AllowCloudProtection
Defender/AllowEmailScanning
Defender/AllowFullScanOnMappedNetworkDrives
Defender/AllowFullScanRemovableDriveScanning
Defender/AllowRealtimeMonitoring
Defender/AllowScanningNetworkFiles
Defender/AllowUserUIAccess

### CODE REVIEW

**Comment by illfated** [comment]
May I suggest either a comma or a dash between the existing `Allowed` / `Not allowed` text and the added descriptions? I think adding a comma or dash (turns into _en_ dash on the page) would put the focus back on the values 0/1 as well as showing that the added text is additional explanation to the Allowed / Not allowed text.

**Comment by e0i** [comment]
@manikadhiman The PR that provides further details on "allowed" and "not allowed" for certain CSPs in the _Policy CSP - Defender_ page is available for review. Thanks.

**Comment by MandiOhlinger** [comment]
#sign-off  PR is ready to merge to master/live.

**Comment by ManikaDhiman** [comment]
Hi @MandiOhlinger, Thanks for the updates. Could you please incorporate edits suggested by @illfated? Thanks!

**Comment by MandiOhlinger** [comment]
@ManikaDhiman No - I don't feel comfortable making those changes. I use these CSPs, but I'm not with that specific doc team.

**Comment by ManikaDhiman** [comment]
@MandiOhlinger. No worries. I have made the edits. Thanks for updating this doc!

**Comment by illfated** [comment]
👍 Good job. Could not have picked a better solution myself.

**Pull request merged**
