### PR TITLE
Updating PS script link after gallery.technet removal

### PR DESCRIPTION
**Pull request by andreiztm**
Also adding download link for the cab file directly.

### CODE REVIEW

**Review by JohanFreelancer9 — APPROVED** [review]

**Review by illfated — APPROVED** [review]
Looks good to me.

**Comment by illfated** [comment]
#sign-off

**Comment by adirdidi** [comment]
Using a personal GitHub repo and not an official one in the official documentation is feeling phishy.
The script should be re-uplodaded to the gallery (or to one of the Microsoft official GitHub repos) instead.

**Comment by andreiztm** [comment]
I don't really have another option since gallery.technet.com was unexpectedly removed without any warning or consideration given to alternative hosting of the scripts there. This was hosted until now over on the technet gallery on my account. I'm also marked as MSFT here, so it should be the same.

**Comment by adirdidi** [comment]
There are Microsoft owned repos in GitHub that this script can reside at reside.
You can't expect customers to check your GitHub profile and assess based on that, plus - you are working in Microsoft today, that might change in the future.

**Comment by andreiztm** [comment]
Are there any instructions on how to get the script in one of those repoes?

**Comment by illfated** [comment]
@jaimeo : Do you have any recommendations for how the missing TechNet Gallery pages should be handled? Could they be moved to Microsoft Docs GitHub repository pages instead, or do we need to wait for them to be placed in the docs.microsoft.com hierarchy?

**Comment by jaimeo** [comment]
We cannot host the scripts by this method. PS scripts need to go in the PowerShell Gallery. The other scripts (that were in the Script Center) are going to have to go in the Download Center.

I am working on this. In the meantime, _nobody is to do any other hosting solution_ for these scripts. Please let us handle it.

**Comment by illfated** [comment]
Thank you for the authoritative reply. Very good.

**Comment by adirdidi** [comment]
The respectable PMs should know, and I believe the tech writers know as well (or at least have a way to reach the PMs). I'm not part of that product group so can't tell you where it should sit (but I can say that a private repo isn't the right place).
This page is not at the TOC, are you sure it's still a relevant page and that it shouldn't be deleted?

**Comment by andreiztm** [comment]
Please keep in mind this script has over 13000 downloads on the old gallery site:
https://web.archive.org/web/20201123171354/https://gallery.technet.microsoft.com/Using-WUA-to-Scan-for-f7e5e0be

In the retirement announcement it also said that GitHub is fine for small project/scripts:

> Now it's time to say goodbye to the TechNet Gallery. There's several reasons why we feel this is the right decision to make:
> 
> **Small tools, scripts, and utilities are best hosted with alongside their source code, with transparent licensing and documentation in GitHub projects.**
> Social media and tech blogs have become the primary way that people post and share tips and tools with one another.
> The migration of MSDN and TechNet to docs.microsoft.com.
> Very low utilization of most of the content on the TechNet Gallery.

We need a timely solution to this. Thank you.

**Comment by jaimeo** [comment]
We have been told we have to have these scripts reviewed and possibly re-written by internal product people. Sorry, but that is taking a little while to accomplish. We are working on it.

**Comment by andreiztm** [comment]
Thank you. Could you please add me on the internal thread? astoica@

**Comment by andreiztm** [comment]
@jaimeo could you please add me to any internal discussion? What is the current status? Thanks.

**Comment by jaimeo** [comment]
@andreiztm done

**Comment by jaimeo** [comment]
@andreiztm thanks so much for fixing that! And sorry for all the confusion.

**Comment by andreiztm** [comment]
Hi @jaimeo I submitted another commit to update the link to the PowerShell gallery:
https://github.com/MicrosoftDocs/windows-itpro-docs/pull/9154/commits/5622d4f8f945dbcf92c3d82fb9c031ebefcff5a3

Please review when you can and approve is all is well.

Thank you,
Andrei

**Comment by andreiztm** [comment]
Thank you, appreciate the help, no worries :D

**Pull request merged**
