### PR TITLE
replaced incorrect term

### PR DESCRIPTION
**Pull request by MaratMussabekov**
https://github.com/MicrosoftDocs/windows-itpro-docs/issues/8919

### CODE REVIEW

**Comment by MaratMussabekov** [comment]
Dear @JohanFreelancer9,
kindly do the copy editor review for this PR.

Dear @nam31, for your information

Thank you

**Review by JohanFreelancer9 — APPROVED** [review]

**Review by illfated — APPROVED** [review]
Rich Diff view: https://github.com/MicrosoftDocs/windows-itpro-docs/pull/8939/files?short_path=08a3ecf#diff-08a3ecf1411414d2c482a969f5344c352e43a95ad6933dc3cf617c4dccc4ac9f

Looks good to me.

**Comment by nam31** [comment]
@greg-lindsay, PR has been copyedited and is ready for final review, could you please check and merge? Thanks!

**Comment by illfated** [comment]
#sign-off

**Pull request merged**
